DROP PROCEDURE IF EXISTS CARS_CMR_CONTENT_REPORTS;
DELIMITER $$
CREATE PROCEDURE CARS_CMR_CONTENT_REPORTS (IN period_id INTEGER,IN excludeAcceptedFlag INTEGER,IN i_subques_id INTEGER, IN i_hdramend_id TEXT)
proc_label: BEGIN

    DECLARE v_Status_Text TEXT DEFAULT NULL;
	DECLARE v_hdramendid_Text TEXT DEFAULT NULL;
	DECLARE v_select_Text TEXT DEFAULT NULL;
	DECLARE v_join_Text TEXT DEFAULT NULL;
    DECLARE v_sql TEXT DEFAULT NULL;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_CMR_CONTENT_REPORTS');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_CMR_CONTENT_REPORTS', 'Started', NOW());	

IF IFNULL(i_subques_id,'')!='' THEN
IF excludeAcceptedFlag = 1 THEN SET v_Status_Text = ' AND  A.STATUS_TEXT <> ''Accepted'' ' ;
ELSE SET v_Status_Text = '  ' ;
END IF;

IF TRIM(i_hdramend_id)!='' THEN SET v_hdramendid_Text = CONCAT(' AND  A.HDR_AMEND_ID IN ( ',i_hdramend_id,') ') ;
ELSE SET v_hdramendid_Text = '  ' ;
END IF;

IF i_subques_id = 1 THEN 

SET v_select_Text = ' CN.ANS_TEXT AS ''Contact Name'',
AD.ANS_TEXT AS ''Address'',
PH.ANS_TEXT AS ''Phone Number'',
FN.ANS_TEXT AS ''Fax Number'',
EA.ANS_TEXT AS ''Email Address'' ' ;

SET v_join_Text = CONCAT(' LEFT JOIN (SELECT N.ANS_TEXT,A.HDR_AMEND_ID  
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Name:'') AS CN ON CN.HDR_AMEND_ID=A.HDR_AMEND_ID

LEFT JOIN (SELECT N.ANS_TEXT,A.HDR_AMEND_ID 
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Address:'') AS AD ON AD.HDR_AMEND_ID=A.HDR_AMEND_ID

LEFT JOIN (SELECT N.ANS_TEXT,A.HDR_AMEND_ID 
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Phone Number:'') AS PH ON PH.HDR_AMEND_ID=A.HDR_AMEND_ID

LEFT JOIN (SELECT N.ANS_TEXT,A.HDR_AMEND_ID 
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Fax Number:'') AS FN ON FN.HDR_AMEND_ID=A.HDR_AMEND_ID

LEFT JOIN (SELECT N.ANS_TEXT,A.HDR_AMEND_ID 
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Email Address:'') AS EA ON EA.HDR_AMEND_ID=A.HDR_AMEND_ID ') ;

ELSE 
SET v_select_Text = ' MR.ANS_DEC AS ''Mandatory: $'',
DR.ANS_DEC AS ''Discretionary: $'',
PR.ANS_TEXT AS ''Project Name'' ' ;



SET v_join_Text = CONCAT(' LEFT JOIN (SELECT N.ANS_DEC,A.HDR_AMEND_ID  
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Mandatory: $'') AS MR ON MR.HDR_AMEND_ID=A.HDR_AMEND_ID
LEFT JOIN (SELECT N.ANS_DEC,A.HDR_AMEND_ID 
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Discretionary: $'') AS DR ON DR.HDR_AMEND_ID=A.HDR_AMEND_ID
LEFT JOIN (SELECT N.ANS_TEXT,A.HDR_AMEND_ID 
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID IN (',period_id,')
JOIN CARS_CMR_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID 
JOIN CARS_CMR_SUBQUES_RESP B
ON N.SUBQUES_RESP_ID = B.SUBQUES_RESP_ID AND B.RESP_LABEL_TEXT=''Name of Project:'') AS PR ON PR.HDR_AMEND_ID=A.HDR_AMEND_ID ') ;
END IF;

SET v_sql = 
CONCAT('
SELECT DISTINCT
E.ENTITY_NAME AS ''Lead Agency'',
E.OGM_TRIBAL_CD AS ''Tribal Code'',
ST.ENTITY_NAME AS ''State'',
R.ENTITY_NAME AS ''Region'',
I.ALLOCATION_SIZE AS ''Allocation'',
CONCAT("Request #",A.AMEND_SEQ_NUM) AS ''Request #'',

',v_select_Text,'

FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_CMR_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID

JOIN CARS_ENTITY E ON (H.ENTITY_ID = E.ENTITY_ID and E.ENTITY_TYPE_CD = ''TRIBE'')
JOIN CARS_TRIBE_INFO I ON (H.ENTITY_ID = I.TRIBE_ID and H.PERIOD_ID = I.PERIOD_ID)
JOIN CARS_ENTITY R ON (E.REGION_ID = R.ENTITY_ID and R.ENTITY_TYPE_CD = ''REGION'')
JOIN CARS_ENTITY ST ON (E.ENTITY_STATE_CD = ST.ENTITY_STATE_CD and ST.ENTITY_TYPE_CD = ''STATE-TER'')

',v_join_Text,'
			WHERE H.PERIOD_ID IN (',period_id,')', v_Status_Text,v_hdramendid_Text, '  
            ORDER BY H.ENTITY_NAME'
			)
			;

EXECUTE IMMEDIATE v_sql;
END IF;

IF i_subques_id = 1 THEN 	
	SELECT 'Lead Agency' AS 'Lead Agency','Tribal Code' AS 'Tribal Code', 'State' AS 'State', 'Region' AS 'Region',
	'Allocation' AS 'Allocation','Request #' AS 'Request','Status' AS 'Status','Requested By' AS 'Requested By','Requested Time' AS 'Requested Time','Contact Name' AS 'Contact Name',
	'Address' AS 'Address','Phone Number' AS 'Phone Number','Fax Number' AS 'Fax Number','Email Address' AS 'Email Address';
ELSE
	SELECT 'Lead Agency' AS 'Lead Agency','Tribal Code' AS 'Tribal Code', 'State' AS 'State', 'Region' AS 'Region',
	'Allocation' AS 'Allocation','Request #' AS 'Request','Status' AS 'Status','Requested By' AS 'Requested By','Requested Time' AS 'Requested Time','Mandatory: $' AS 'Mandatory:',
	'Discretionary: $' AS 'Discretionary:','Project Name' AS 'Project Name';
END IF;

UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_CMR_CONTENT_REPORTS');
		
	
END$$
DELIMITER ;