DELIMITER $$
CREATE PROCEDURE `CARS_NAT_PROG_PROFILE_PROC`(
 p_PERIOD_ID INT,
 p_ENTITY_ID VARCHAR(4000),
 p_PROGRAM_477_FLAG INT,
 p_ALLOCATION_SIZE VARCHAR(50)
)
BEGIN 

DECLARE v_ENTITY_ID TEXT;
DECLARE v_PROGRAM_477_FLAG TEXT;
DECLARE v_ALLOCATION_SIZE TEXT;
DECLARE v_SQL_1 TEXT;


IF p_ENTITY_ID IS NULL THEN SET v_ENTITY_ID=' '; 
END IF;
IF p_ENTITY_ID IS NOT NULL THEN SET v_ENTITY_ID = CONCAT(' AND ENTITY_ID IN (',  p_ENTITY_ID ,') ');
END IF;

IF p_PROGRAM_477_FLAG = 1  THEN SET v_PROGRAM_477_FLAG = ' ';
END IF;
IF p_PROGRAM_477_FLAG = 0 THEN SET v_PROGRAM_477_FLAG = ' AND PROGRAM_477_FLAG <> 1 ';
END IF;
IF p_PROGRAM_477_FLAG IS NULL THEN SET v_PROGRAM_477_FLAG = ' AND PROGRAM_477_FLAG <> 1 ';
END IF;

SET p_ALLOCATION_SIZE=
REPLACE(
REPLACE(    
REPLACE(p_ALLOCATION_SIZE
,'Large','"Large"') 
,'Medium', '"Medium"')
,'Small', '"Small"')  ;
 

IF p_ALLOCATION_SIZE IS NULL THEN SET v_ALLOCATION_SIZE = ' '  ;

#IF p_ALLOCATION_SIZE = 'Medium' THEN SET v_ALLOCATION_SIZE = ' (AND ALLOCATION_SIZE ="Medium" OR ALLOCATION_SIZE IS NULL)  ' ; 
#END IF;
ELSEIF p_ALLOCATION_SIZE IS NOT NULL AND  p_ALLOCATION_SIZE LIKE  '%Medium%' THEN SET v_ALLOCATION_SIZE = CONCAT('AND ( ALLOCATION_SIZE IN ( ', p_ALLOCATION_SIZE,') OR ALLOCATION_SIZE IS NULL) ');

ELSEIF p_ALLOCATION_SIZE IS NOT NULL AND  p_ALLOCATION_SIZE NOT LIKE  '%Medium%' THEN SET v_ALLOCATION_SIZE = CONCAT('AND ( ALLOCATION_SIZE IN ( ', p_ALLOCATION_SIZE,') ) ');
END IF;



SET v_SQL_1=
'SELECT 
SUM(FAM_COUNT) AS FAM_COUNT,
SUM(CHILD_COUNT) AS CHILD_COUNT,
SUM(CHILD_COUNT_MO) AS CHILD_COUNT_MO,
ROUND(SUM(AVG_SUBSIDY * CHILD_COUNT_PER_MO) / SUM(CHILD_COUNT_SUBS)) AS AVG_SUBS_PERCHILD,
ROUND(SUM(AVG_COPAY * CHILD_COUNT_PER_MO) / SUM(CHILD_COUNT_COPAY)) AS AVG_COPAY_PERCHILD,
ROUND(SUM(AVG_HOURS * CHILD_COUNT_PER_MO) / SUM(CHILD_COUNT_HOURS)) AS AVG_HOURS_PERCHILD
FROM 
VW_CARS_NAT_PROG_PROFILE
WHERE 
1=1
AND PERIOD_ID = ';

#select CONCAT(v_SQL_1,p_PERIOD_ID, v_ENTITY_ID, v_PROGRAM_477_FLAG, v_ALLOCATION_SIZE) AS a;
EXECUTE IMMEDIATE CONCAT(v_SQL_1,p_PERIOD_ID, v_ENTITY_ID, v_PROGRAM_477_FLAG, v_ALLOCATION_SIZE) ;

END$$
DELIMITER ;