DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_218_SECTION_REVIEW_STATUS`(IN i_amend_id INT, OUT OutputString Longtext)
proc_label: BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_218_SECTION_REVIEW_STATUS');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_218_SECTION_REVIEW_STATUS', 'Started', NOW());	
SET SESSION group_concat_max_len = 10000000;
	
WITH CTE AS(SELECT
 DISTINCT S.SECT_ID,SQR.REVIEW_DECISION_TEXT
FROM CARS_218_QUES  Q
JOIN CARS_218_SUBSECT SS
ON SS.SUBSECT_ID = Q.SUBSECT_ID
JOIN CARS_218_SECT S
ON S.SECT_ID = SS.SECT_ID
JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
WHERE SQR.HDR_AMEND_ID = i_amend_id AND SQR.REVIEW_STATUS_TEXT='Recommend for Acceptance Review'),
CTE2 AS(SELECT SECT_ID,'UNDECIDED' AS REVIEW_DECISION_TEXT FROM CTE WHERE
        (REVIEW_DECISION_TEXT='' OR REVIEW_DECISION_TEXT IS NULL OR REVIEW_DECISION_TEXT='Undecided')),
CTE3 AS(SELECT SECT_ID,REVIEW_DECISION_TEXT FROM CTE WHERE REVIEW_DECISION_TEXT='Need more Information from State/Territory'
        AND SECT_ID NOT IN(SELECT SECT_ID FROM CTE2)),
        CTE4 AS(
        SELECT SECT_ID,REVIEW_DECISION_TEXT FROM CTE WHERE SECT_ID NOT IN(SELECT SECT_ID FROM CTE2)
        AND SECT_ID NOT IN(SELECT SECT_ID FROM CTE3))
                
        SELECT CONCAT('{',
    	Group_Concat( '"SECT_ID":"',SECT_ID,'","REVIEW_DECISION_TEXT":"',REVIEW_DECISION_TEXT,'"'
                   SEPARATOR ',
                    '),'}') AS 'Output' INTO OutputString
    			FROM(
        SELECT SECT_ID,REVIEW_DECISION_TEXT FROM CTE4
        UNION ALL
        SELECT SECT_ID,REVIEW_DECISION_TEXT FROM CTE3
        UNION ALL
        SELECT SECT_ID,REVIEW_DECISION_TEXT FROM CTE2) AS G;
		

UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_218_SECTION_REVIEW_STATUS');
		
END$$
DELIMITER ;
        
     
        

