DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_118A_CLONE_AMENDMENT`(
	IN i_hdramend_id INT(11))

BEGIN
	DECLARE v_hdramend_id INTEGER DEFAULT 0 ; 
	DECLARE v_seq_num INTEGER DEFAULT 0 ;
	DECLARE v_seq_nums INTEGER DEFAULT 0 ;
	DECLARE v_modhdr_id INTEGER DEFAULT 0 ;
	
	-- process error handle
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		 
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_118A_CLONE_AMENDMENT');
		COMMIT; 

	END;	
	
	-- insert log record
	INSERT INTO CARS_SP_LOG (`SP_NAME`, `START_TS`, `END_TS`)
		VALUES( 'CARS_118A_CLONE_AMENDMENT', NOW(), NOW());
		
	SELECT MODULE_HDR_ID INTO v_modhdr_id FROM CARS_118A_HDR_AMEND WHERE HDR_AMEND_ID =i_hdramend_id LIMIT 1;
	SELECT MAX(AMEND_SEQ_NUM) INTO v_seq_num FROM CARS_118A_HDR_AMEND WHERE MODULE_HDR_ID=v_modhdr_id;
	IF (v_seq_num IS NULL) THEN
	    SET v_seq_num=1;
	ELSE
	    SET v_seq_num=v_seq_num+1;
	END IF;
	
	
	INSERT INTO CARS_118A_HDR_AMEND(MODULE_HDR_ID,AMEND_SEQ_NUM)	
	SELECT v_modhdr_id,v_seq_num;	
	
	SELECT LAST_INSERT_ID() INTO v_hdramend_id;
	
	UPDATE CARS_MODULE_PERIOD_HDR
	SET STATUS_TEXT='Work in Progress'
	WHERE MODULE_HDR_ID = v_modhdr_id;
	
	CREATE OR REPLACE TEMPORARY TABLE CARS_118A_CLONE_AMENDMENT_TEMP AS
	SELECT v_hdramend_id AS 'vhdramendid',SUBQUES_ID,'Recommendation Review' AS RR,'Recommend' AS R,'SYSTEM' AS S,now() AS 'now'
	FROM CARS_118A_SUBQUES
	UNION ALL
	SELECT v_hdramend_id,SUBQUES_ID,'Validation Review','Agree','SYSTEM',now()
	FROM CARS_118A_SUBQUES;
	
	INSERT INTO CARS_118A_HDR_SUBQUES_REVIEW(HDR_AMEND_ID,SUBQUES_ID,REVIEW_STATUS_TEXT,REVIEW_DECISION_TEXT,READY_VALIDATION_FLAG,
	LAST_UPD_TS,LAST_UPD_BY,RETURNED_RO_LEAST_ONCE_FLAG,RETURNED_GRANTEE_LEAST_ONCE_FLAG,RETURNED_GRANTEE_FLAG,CENTRAL_OFFICE_FLAG,LATE_AMENDMENT,
    NEW_EFFECTIVE_DATE)
	SELECT v_hdramend_id,SUBQUES_ID,REVIEW_STATUS_TEXT, CASE WHEN REVIEW_STATUS_TEXT='Validation Review' AND (IFNULL(REVIEW_DECISION_TEXT,'')='' OR 
    REVIEW_DECISION_TEXT='N/A') AND EXISTS(SELECT 1 FROM CARS_118A_HDR_SUBQUES_REVIEW AS B WHERE B.HDR_AMEND_ID=i_hdramend_id AND B.SUBQUES_ID=A.SUBQUES_ID
	AND B.REVIEW_STATUS_TEXT='Recommendation Review' AND B.REVIEW_DECISION_TEXT!='N/A') THEN 'Agree' ELSE 
	REVIEW_DECISION_TEXT END,READY_VALIDATION_FLAG,NOW(),'SYSTEM',
    NULL,NULL,NULL,NULL,NULL,NULL	FROM CARS_118A_HDR_SUBQUES_REVIEW AS A
	WHERE HDR_AMEND_ID=i_hdramend_id; 
	
	
	INSERT INTO CARS_118A_SUBQUES_AMENDMENT(HDR_AMEND_ID,SUBQUES_ID,IS_AMENDED,AMENDMENT_DUE_TO_COMPLIANCE,EFFECTIVE_DATE,DESCRIPTION,
	LAST_UPD_BY,LAST_UPD_TS)
	SELECT DISTINCT vhdramendid,SUBQUES_ID,0,0,NULL,NULL,
	S,now FROM CARS_118A_CLONE_AMENDMENT_TEMP;	
		
	INSERT INTO CARS_118A_HDR_ANS(
    HDR_AMEND_ID,
    SUBQUES_RESP_ID,
    ANS_BOOL,
    ANS_INTEGER,
    ANS_DEC,
    ANS_TEXT,
    ANS_DATE,
    ANS_STATUS_TEXT
)

SELECT 
    v_hdramend_id,
    SUBQUES_RESP_ID,
    ANS_BOOL,
    ANS_INTEGER,
    ANS_DEC,
    ANS_TEXT,
    ANS_DATE,
    ANS_STATUS_TEXT
	FROM CARS_118A_HDR_ANS
	WHERE HDR_AMEND_ID=i_hdramend_id;
	
	INSERT INTO CARS_118A_CHILD_COUNT(
    HDR_AMEND_ID,
    ENTITY_ID,
    MAND_CHILD_COUNT,
    DISCR_CHILD_COUNT,
    DECLR_DOC_ID,
    DEMO_DOC_ID,
    LAST_UPD_BY,
	LAST_UPD_TS
)

SELECT 
    v_hdramend_id,
    ENTITY_ID,
    MAND_CHILD_COUNT,
    DISCR_CHILD_COUNT,
    DECLR_DOC_ID,
    DEMO_DOC_ID,
    'SYSTEM',
	NOW()
	FROM CARS_118A_CHILD_COUNT
	WHERE HDR_AMEND_ID=i_hdramend_id;
	
	SELECT v_hdramend_id AS 'o_newhdramend_id';

	UPDATE CARS_SP_LOG
		SET SP_STATUS_TEXT= CONCAT('Success. Locks released: ',0), END_TS=NOW()
	WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME='CARS_118A_CLONE_AMENDMENT');
	COMMIT;	
	
	

END$$
DELIMITER ;