DELIMITER $$
CREATE OR REPLACE PROCEDURE CARS_118_TEXT_STRING_PROC(IN i_period_id INTEGER, IN i_entity_id TEXT, IN i_string TEXT)
BEGIN
DECLARE v_sql1 TEXT DEFAULT NULL ; 
DECLARE v_sql TEXT DEFAULT NULL ; 
DECLARE v_entities TEXT DEFAULT NULL;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_118_TEXT_STRING_PROC');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_118_TEXT_STRING_PROC', 'Started', NOW());	

IF i_entity_id IS NULL OR i_entity_id = '' 
THEN SET v_entities = ' ';
ELSE SET v_entities = CONCAT(' AND E.ENTITY_ID IN (', i_entity_id, ')');
END IF;


SET v_sql1 = CONCAT('
SELECT
E.ENTITY_NAME AS ''State_Territory'',
RE.ENTITY_NAME AS ''Region'',
RE.ENTITY_ID AS ''REGION_ID'',
CASE WHEN A.AMEND_SEQ_NUM>1 THEN CONCAT(''Amendment #'',A.AMEND_SEQ_NUM-1) ELSE ''Initial Plan'' END AS ''Plan'',
CASE WHEN SUBSTR(S.SUBQUES_NAME, 1, LOCATE('' '', S.SUBQUES_NAME) - 1) = ''.'' THEN SUBSTR(S.SUBQUES_NAME, 1, LOCATE('' '', S.SUBQUES_NAME) - 2)
	 ELSE SUBSTR(S.SUBQUES_NAME, 1, LOCATE('' '', S.SUBQUES_NAME) - 1) END AS ''Question'',
N.ANS_TEXT AS ''Respone''
FROM CARS_MODULE_PERIOD_HDR H
JOIN (	SELECT 
		A1.MODULE_HDR_ID, A1.HDR_AMEND_ID,A2.AMEND_SEQ_NUM 
		FROM CARS_118_HDR_AMEND A1
		JOIN 
		(
			SELECT MODULE_HDR_ID, MAX(AMEND_SEQ_NUM) AS AMEND_SEQ_NUM 
			FROM CARS_118_HDR_AMEND 
			GROUP BY MODULE_HDR_ID
		) A2
		ON A1.MODULE_HDR_ID = A2.MODULE_HDR_ID
		AND A1.AMEND_SEQ_NUM = A2.AMEND_SEQ_NUM
	  ) A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID
JOIN CARS_118_HDR_ANS N
ON A.HDR_AMEND_ID = N.HDR_AMEND_ID
JOIN CARS_118_SUBQUES_RESP R
ON N.SUBQUES_RESP_ID = R.SUBQUES_RESP_ID
JOIN CARS_118_SUBQUES S
ON R.SUBQUES_ID = S.SUBQUES_ID
JOIN CARS_ENTITY E
ON H.ENTITY_ID = E.ENTITY_ID
entity_list
AND E.ENTITY_TYPE_CD = ''STATE-TER''
JOIN CARS_ENTITY RE
ON E.REGION_ID = RE.ENTITY_ID
AND RE.ENTITY_TYPE_CD = ''REGION''

WHERE H.PERIOD_ID = replace_period_id  


AND N.ANS_TEXT LIKE ''%',  'replace_string', '%''
ORDER BY 1,4
'
)
;

SET v_sql = REPLACE(REPLACE(REPLACE(v_sql1, 'replace_period_id', i_period_id), 'replace_string', i_string), 'entity_list' , v_entities);

EXECUTE IMMEDIATE (v_sql);

SELECT 'State/Territory' AS 'State/Territory','Region' AS 'Region', 'Region_ID' AS 'Region_ID', 'Plan' AS 'Plan', 'Question' AS 'Question', 'Response' AS 'Response';


UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_118_TEXT_STRING_PROC');
		
END$$
DELIMITER ;