DELIMITER $$
CREATE OR REPLACE PROCEDURE CARS_118_LEGACY_TEXT_STRING_PROC(IN i_period_id INTEGER, IN i_entity_id TEXT, IN i_string TEXT)
BEGIN
DECLARE v_sql1 TEXT DEFAULT NULL ; 
DECLARE v_sql TEXT DEFAULT NULL ; 
DECLARE v_entities TEXT DEFAULT NULL;
DECLARE v_period_desc INTEGER DEFAULT NULL;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_118_LEGACY_TEXT_STRING_PROC');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_118_LEGACY_TEXT_STRING_PROC', 'Started', NOW());	

IF i_entity_id IS NULL OR i_entity_id = '' 
THEN SET v_entities = ' ';
ELSE SET v_entities = CONCAT(' AND E.ENTITY_ID IN (', i_entity_id, ')');
END IF;

SELECT 
CAST(SUBSTR(PERIOD_DESC, 4,4) AS INTEGER) INTO v_period_desc
FROM CARS_PERIOD P
WHERE PERIOD_ID = i_period_id
;


SET v_sql = CONCAT('
SELECT
State_Territory,
Region,
REGION_ID,
Plan,
Question,
Response
FROM 
(
SELECT 
info.STATE_NAME AS ''State_Territory'', 
RE.ENTITY_NAME AS ''Region'',
RE.ENTITY_ID AS ''REGION_ID'',
CASE WHEN mv.MAX_VERSION = 1 THEN ''Initial Plan'' ELSE CONCAT(''Amendment #'', mv.MAX_VERSION-1) END AS ''Plan'',
q.STPLAN_SEC_QUEST_NAME AS ''Question'', 
r.STPLAN_RESP_DESC AS ''Response'' 
FROM CARS_LEGACY_118_STPLAN_STATE_INFO_REF info
JOIN 
(
SELECT info.STATE_NAME, MAX(r.STPLAN_RESP_VERSION) AS MAX_VERSION 
FROM CARS_LEGACY_118_STPLAN_SECT_RESP r 
JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF info   
WHERE info.STATE_CODE = r.STPLAN_STATE_CODE 
AND r.STPLAN_YEAR = replace_period
GROUP BY info.state_name
) mv
ON info.STATE_NAME = mv.STATE_NAME

JOIN CARS_LEGACY_118_STPLAN_SECT_RESP r
ON mv.MAX_VERSION = r.STPLAN_RESP_VERSION 
AND info.STATE_CODE = r.STPLAN_STATE_CODE 
AND r.STPLAN_RESP_DESC LIKE ''%replace_string%''

JOIN CARS_LEGACY_118_STPLAN_SECT_QUEST q
ON r.STPLAN_SECT_QUEST_ID = q.STPLAN_SECT_QUEST_ID

JOIN CARS_ENTITY E
ON info.STATE_NAME = E.ENTITY_NAME
AND E.ENTITY_TYPE_CD = ''STATE-TER''
entity_list

JOIN CARS_ENTITY RE
ON E.REGION_ID = RE.ENTITY_ID
AND RE.ENTITY_TYPE_CD = ''REGION''

WHERE q.stplan_year = replace_period

UNION ALL 

SELECT 
info.STATE_NAME AS ''State_Territory'', 
RE.ENTITY_NAME AS ''Region'',
RE.ENTITY_ID AS ''REGION_ID'',
CASE WHEN mv.MAX_VERSION = 1 THEN ''Initial Plan'' ELSE CONCAT(''Amendment #'', mv.MAX_VERSION-1) END AS ''Plan'',
q.STPLAN_SEC_QUEST_NAME AS ''Question'', 
r.STPLAN_RESP_TEXT AS ''Response'' 
FROM CARS_LEGACY_118_STPLAN_STATE_INFO_REF info
JOIN 
(
SELECT info.STATE_NAME, MAX(r.STPLAN_RESP_VERSION) AS MAX_VERSION 
FROM CARS_LEGACY_118_STPLAN_SECT_RESP r 
JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF info   
WHERE info.STATE_CODE = r.STPLAN_STATE_CODE 
AND r.STPLAN_YEAR = replace_period
GROUP BY info.state_name
) mv
ON info.STATE_NAME = mv.STATE_NAME

JOIN CARS_LEGACY_118_STPLAN_SECT_RESP r
ON mv.MAX_VERSION = r.STPLAN_RESP_VERSION 
AND info.STATE_CODE = r.STPLAN_STATE_CODE 
AND r.STPLAN_RESP_TEXT LIKE ''%replace_string%''

JOIN CARS_LEGACY_118_STPLAN_SECT_QUEST q
ON r.STPLAN_SECT_QUEST_ID = q.STPLAN_SECT_QUEST_ID

JOIN CARS_ENTITY E
ON info.STATE_NAME = E.ENTITY_NAME
AND E.ENTITY_TYPE_CD = ''STATE-TER''
entity_list

JOIN CARS_ENTITY RE
ON E.REGION_ID = RE.ENTITY_ID
AND RE.ENTITY_TYPE_CD = ''REGION''

WHERE q.stplan_year = replace_period
) A

ORDER BY State_Territory, Question
'
)
;


EXECUTE IMMEDIATE REPLACE(REPLACE(REPLACE(v_sql, 'replace_string', i_string), 'entity_list', v_entities), 'replace_period', v_period_desc);

SELECT 'State/Territory' AS 'State/Territory','Region' AS 'Region', 'Region_ID' AS 'Region_ID', 'Plan' AS 'Plan', 'Question' AS 'Question', 'Response' AS 'Response';

UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_118_LEGACY_TEXT_STRING_PROC');
		
END$$
DELIMITER ;