DROP PROCEDURE IF EXISTS CARS_801_AGGN_SP_RUNALL;
DELIMITER //

CREATE PROCEDURE CARS_801_AGGN_SP_RUNALL(IN i_aggn_ref_id INT, OUT o_Proc_Success TINYINT(1))

proc_label: BEGIN

DECLARE v_Status_Text TEXT;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		 
		UPDATE CARS_801_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_801_SP_LOG WHERE SP_NAME='CARS_801_AGGN_SP_RUNALL');
		
	END;	
	
	INSERT INTO CARS_801_SP_LOG ( SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES( 'CARS_801_AGGN_SP_RUNALL', 'Started', NOW());	
	
	UPDATE CARS_801_AGGN_REF
	    SET AGG_START_TS=NOW(), AGG_END_TS = NULL
	WHERE AGGN_REF_ID=i_aggn_ref_id;
	
	/****   REPORT 101   ****/
	CALL CARS_801_AGGN_SP_FAMILY_CHILD_COUNT (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_FAMILY_CHILD_COUNT');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;

	
	/****   REPORTS 200, 206, AND 207   ****/
	CALL CARS_801_AGGN_SP_REASON_FOR_CARE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_REASON_FOR_CARE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORT 210   ****/
	CALL CARS_801_AGGN_SP_INCOME_SOURCE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_INCOME_SOURCE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;	
	
	
	/****   REPORTS 220 AND 230   ****/
	CALL CARS_801_AGGN_SP_SEPARATE_INCOME_SOURCE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_SEPARATE_INCOME_SOURCE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORT 280   ****/
	CALL CARS_801_AGGN_SP_SINGLE_PARENT (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_SINGLE_PARENT');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORTS 301 AND 302   ****/
	CALL CARS_801_AGGN_SP_AGE_GROUP (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_AGE_GROUP');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORT 310   ****/
	CALL CARS_801_AGGN_SP_RACE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_RACE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORT 320   ****/
	CALL CARS_801_AGGN_SP_ETHNICITY (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_ETHNICITY');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
			
	/****   REPORTS 330 AND 503   ****/
	CALL CARS_801_AGGN_SP_AGE_GROUP_HOURS_SUBSIDY (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_AGE_GROUP_HOURS_SUBSIDY');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORTS 406 AND 407   ****/
	CALL CARS_801_AGGN_SP_AGE_GROUP_CARE_TYPE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_AGE_GROUP_CARE_TYPE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
		
	/****   REPORT 423   ****/
	CALL CARS_801_AGGN_SP_AGE_GROUP_CARE_TYPE_HOURS_SUBSIDY (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_AGE_GROUP_CARE_TYPE_HOURS_SUBSIDY');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORT 433   ****/
	CALL CARS_801_AGGN_SP_CARE_TYPE_HOURS_SUBSIDY (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_CARE_TYPE_HOURS_SUBSIDY');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORTS 451 AND 452   ****/
	CALL CARS_801_AGGN_SP_CARE_TYPE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_CARE_TYPE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
		
	/****   REPORT 460   ****/
	CALL CARS_801_AGGN_SP_LIC_LEG_CARE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_LIC_LEG_CARE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
		
	/****   REPORTS 511 AND 512   ****/
	CALL CARS_801_AGGN_SP_INCOME_CAT (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_INCOME_CAT');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORTS 531 AND 532   ****/
	CALL CARS_801_AGGN_SP_INCOME_POVERTY (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_INCOME_POVERTY');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
    
		/****   CARS_801_AGGN_SP_INCOME_POVERTY_THRESH   ****/
	CALL CARS_801_AGGN_SP_INCOME_POVERTY_THRESH (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_INCOME_POVERTY_THRESH');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	/****   REPORTS 551 AND 552   ****/
	CALL CARS_801_AGGN_SP_INCOME_POVERTY_COPAY (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_INCOME_POVERTY_COPAY');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
		/****   CARS_801_AGGN_SP_INCOME_POVERTY_COPAY_THRESH   ****/
	CALL CARS_801_AGGN_SP_INCOME_POVERTY_COPAY_THRESH (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_INCOME_POVERTY_COPAY_THRESH');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORTS 561 AND 562   ****/
	CALL CARS_801_AGGN_SP_COPAY_CAT (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_COPAY_CAT');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   REPORT 591   ****/
	CALL CARS_801_AGGN_SP_MEAN_COPAY_INCOME (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_MEAN_COPAY_INCOME');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
		/****   REPORT ASPE   ****/
	CALL CARS_801_AGGN_SP_ASPE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_ASPE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
			/****   REPORT RACE AND ETHNICITY   ****/
	CALL CARS_801_AGGN_SP_RACE_ETHNICITY (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_RACE_ETHNICITY');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
			/****   Children Below Poverty   ****/
	CALL CARS_801_AGGN_SP_PRIORITIES (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_PRIORITIES');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	
	/****   CARS_801_AGGN_SP_MISSING_MONTHS_FOOTNOTE   ****/
	CALL CARS_801_AGGN_SP_MISSING_MONTHS_FOOTNOTE (i_aggn_ref_id);
	
	SELECT SP_STATUS_TEXT INTO v_Status_Text FROM CARS_801_SP_LOG 
	WHERE SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME = 'CARS_801_AGGN_SP_MISSING_MONTHS_FOOTNOTE');
	
	IF v_Status_Text NOT LIKE '%Success%' THEN
		SET o_Proc_Success = 0;
		LEAVE proc_label;
	END IF;
	
	

	UPDATE CARS_801_SP_LOG
		SET SP_STATUS_TEXT= CONCAT('Success'), END_TS=NOW()
	WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME='CARS_801_AGGN_SP_RUNALL');

	UPDATE CARS_801_AGGN_REF
	    SET AGG_END_TS=NOW()
	WHERE AGGN_REF_ID=i_aggn_ref_id;

	SET o_Proc_Success = 1;
	
END //
    
DELIMITER  ;
	
