DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_218_QPR_QUESTION_REVIEW_DETAILS_REPORT`(IN period_id INTEGER,IN entity_id TEXT,IN i_section_id TEXT)
proc_label: BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_218_QPR_QUESTION_REVIEW_DETAILS_REPORT');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_218_QPR_QUESTION_REVIEW_DETAILS_REPORT', 'Started', NOW());	


IF TRIM(i_section_id)!='' AND TRIM(entity_id)!='' THEN


WITH RecommendforAcceptanceReview AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Recommend for Acceptance Review'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.REVIEW_STATUS_TEXT='Recommend for Acceptance Review' AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
	AcceptanceReview AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Acceptance Review'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.REVIEW_STATUS_TEXT='Acceptance Review' AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
	RPM_FLAG AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for RPM'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.RPM_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
	CENTRAL_OFFICE_FLAG AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for CO'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.CENTRAL_OFFICE_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)))	
		
	
	
	SELECT DISTINCT H.ENTITY_NAME AS 'State/Territory',R.ENTITY_NAME AS 'Region',SQ.SUBQUES_NAME AS Question,
C.`Recommend for Acceptance Review`,D.`Acceptance Review`,EE.`Flag for RPM`,F.`Flag for CO`, SQ.SUBQUES_ID AS 'View Comments', 
R.ENTITY_ID AS 'REGION_ID', (
    substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 1)*10000 + 
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 2), '.', -1)*1000 +
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 3), '.', -1)*100
)  AS 'subQuesNumber'
		
		FROM (
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RecommendforAcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM AcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RPM_FLAG UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM CENTRAL_OFFICE_FLAG) AS A
	LEFT JOIN RecommendforAcceptanceReview C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN AcceptanceReview D ON A.SUBQUES_ID=D.SUBQUES_ID AND D.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN RPM_FLAG EE ON  A.SUBQUES_ID=EE.SUBQUES_ID AND EE.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN CENTRAL_OFFICE_FLAG F ON A.SUBQUES_ID=F.SUBQUES_ID AND F.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
    AND A.SUBQUES_ID=SQR.SUBQUES_ID
	JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID	
	JOIN CARS_218_HDR_AMEND AM ON AM.HDR_AMEND_ID=A.HDR_AMEND_ID	
    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = AM.MODULE_HDR_ID	
	JOIN CARS_ENTITY E
	ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
	JOIN CARS_ENTITY R
	ON E.REGION_ID = R.ENTITY_ID
	AND R.ENTITY_TYPE_CD = 'REGION'
	ORDER BY H.ENTITY_ID,SQ.SUBQUES_ID;	
	
SELECT 'State/Territory' AS 'StateTerritory','Region' AS 'Region','Question' AS 'Question',
	'Recommend for Acceptance Review' AS 'RecommendforAcceptanceReview','Acceptance Review' AS 'AcceptanceReview','Flag for RPM' AS 'FlagforRPM','Flag for CO' AS 'FlagforCO', 'View Comments' AS 'ViewComments', 'REGION_ID' AS 'REGION_ID', 'subQuesNumber' AS 'subQuesNumber';

			
	ELSEIF TRIM(i_section_id)='' AND TRIM(entity_id)!='' THEN
		WITH RecommendforAcceptanceReview AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Recommend for Acceptance Review'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.REVIEW_STATUS_TEXT='Recommend for Acceptance Review'),
	AcceptanceReview AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Acceptance Review'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.REVIEW_STATUS_TEXT='Acceptance Review'),
	RPM_FLAG AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for RPM'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.RPM_FLAG=1),
	CENTRAL_OFFICE_FLAG AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for CO'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.CENTRAL_OFFICE_FLAG=1)	
		
	SELECT DISTINCT H.ENTITY_NAME AS 'State/Territory',R.ENTITY_NAME AS 'Region',SQ.SUBQUES_NAME AS Question,
    C.`Recommend for Acceptance Review`,D.`Acceptance Review`,EE.`Flag for RPM`,F.`Flag for CO`, SQ.SUBQUES_ID AS 'View Comments', 
	R.ENTITY_ID AS 'REGION_ID', (
    substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 1)*10000 + 
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 2), '.', -1)*1000 +
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 3), '.', -1)*100
)  AS 'subQuesNumber'
		
		FROM (
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RecommendforAcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM AcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RPM_FLAG UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM CENTRAL_OFFICE_FLAG) AS A
	LEFT JOIN RecommendforAcceptanceReview C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN AcceptanceReview D ON A.SUBQUES_ID=D.SUBQUES_ID AND D.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN RPM_FLAG EE ON  A.SUBQUES_ID=EE.SUBQUES_ID AND EE.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN CENTRAL_OFFICE_FLAG F ON A.SUBQUES_ID=F.SUBQUES_ID AND F.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
    AND A.SUBQUES_ID=SQR.SUBQUES_ID
	JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID	
	JOIN CARS_218_HDR_AMEND AM ON AM.HDR_AMEND_ID=A.HDR_AMEND_ID	
    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = AM.MODULE_HDR_ID	
	JOIN CARS_ENTITY E
	ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
	JOIN CARS_ENTITY R
	ON E.REGION_ID = R.ENTITY_ID
	AND R.ENTITY_TYPE_CD = 'REGION'
	ORDER BY H.ENTITY_ID,SQ.SUBQUES_ID;	
	
	SELECT 'State/Territory' AS 'StateTerritory','Region' AS 'Region','Question' AS 'Question',
	'Recommend for Acceptance Review' AS 'RecommendforAcceptanceReview','Acceptance Review' AS 'AcceptanceReview','Flag for RPM' AS 'FlagforRPM','Flag for CO' AS 'FlagforCO', 'View Comments' AS 'ViewComments', 'REGION_ID' AS 'REGION_ID', 'subQuesNumber' AS 'subQuesNumber';

	ELSEIF TRIM(i_section_id)!='' AND TRIM(entity_id)='' THEN
		WITH RecommendforAcceptanceReview AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Recommend for Acceptance Review'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.REVIEW_STATUS_TEXT='Recommend for Acceptance Review' AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
	AcceptanceReview AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Acceptance Review'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.REVIEW_STATUS_TEXT='Acceptance Review' AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
	RPM_FLAG AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for RPM'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.RPM_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
	CENTRAL_OFFICE_FLAG AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for CO'
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.CENTRAL_OFFICE_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)))	
		
	
	
	SELECT DISTINCT H.ENTITY_NAME AS 'State/Territory',R.ENTITY_NAME AS 'Region',SQ.SUBQUES_NAME AS Question,
    C.`Recommend for Acceptance Review`,D.`Acceptance Review`,EE.`Flag for RPM`,F.`Flag for CO`, SQ.SUBQUES_ID AS 'View Comments',
	R.ENTITY_ID AS 'REGION_ID', (
    substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 1)*10000 + 
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 2), '.', -1)*1000 +
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 3), '.', -1)*100
) AS 'subQuesNumber'	
		FROM (
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RecommendforAcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM AcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RPM_FLAG UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM CENTRAL_OFFICE_FLAG) AS A
	LEFT JOIN RecommendforAcceptanceReview C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN AcceptanceReview D ON A.SUBQUES_ID=D.SUBQUES_ID AND D.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN RPM_FLAG EE ON  A.SUBQUES_ID=EE.SUBQUES_ID AND EE.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN CENTRAL_OFFICE_FLAG F ON A.SUBQUES_ID=F.SUBQUES_ID AND F.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
    AND A.SUBQUES_ID=SQR.SUBQUES_ID
	JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID	
	JOIN CARS_218_HDR_AMEND AM ON AM.HDR_AMEND_ID=A.HDR_AMEND_ID	
    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = AM.MODULE_HDR_ID	
	JOIN CARS_ENTITY E
	ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
	JOIN CARS_ENTITY R
	ON E.REGION_ID = R.ENTITY_ID
	AND R.ENTITY_TYPE_CD = 'REGION'
	ORDER BY H.ENTITY_ID,SQ.SUBQUES_ID;	
	
	SELECT 'State/Territory' AS 'StateTerritory','Region' AS 'Region','Question' AS 'Question',
	'Recommend for Acceptance Review' AS 'RecommendforAcceptanceReview','Acceptance Review' AS 'AcceptanceReview','Flag for RPM' AS 'FlagforRPM','Flag for CO' AS 'FlagforCO', 'View Comments' AS 'ViewComments', 'REGION_ID' AS 'REGION_ID', 'subQuesNumber' AS 'subQuesNumber';

ELSE
		WITH RecommendforAcceptanceReview AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Recommend for Acceptance Review'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.REVIEW_STATUS_TEXT='Recommend for Acceptance Review'),
	AcceptanceReview AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,SQR.REVIEW_DECISION_TEXT AS 'Acceptance Review'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.REVIEW_STATUS_TEXT='Acceptance Review'),
	RPM_FLAG AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for RPM'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.RPM_FLAG=1),
	CENTRAL_OFFICE_FLAG AS(SELECT
		 DISTINCT SQR.SUBQUES_ID,A.HDR_AMEND_ID,'Yes' AS 'Flag for CO'
		FROM CARS_218_HDR_SUBQUES_REVIEW SQR 
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE SQR.CENTRAL_OFFICE_FLAG=1)	
		
	SELECT DISTINCT H.ENTITY_NAME AS 'State/Territory',R.ENTITY_NAME AS 'Region',SQ.SUBQUES_NAME AS Question,
C.`Recommend for Acceptance Review`,D.`Acceptance Review`,EE.`Flag for RPM`,F.`Flag for CO`, SQ.SUBQUES_ID AS 'View Comments', R.ENTITY_ID AS 'REGION_ID', 
(
    substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 1)*10000 + 
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 2), '.', -1)*1000 +
    substring_index(substring_index(SUBSTRING(SQ.SUBQUES_NAME, 1, LOCATE(' ', SQ.SUBQUES_NAME)), '.', 3), '.', -1)*100
)  AS 'subQuesNumber'
		
		FROM (
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RecommendforAcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM AcceptanceReview UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM RPM_FLAG UNION
		SELECT SUBQUES_ID,HDR_AMEND_ID FROM CENTRAL_OFFICE_FLAG) AS A
	LEFT JOIN RecommendforAcceptanceReview C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN AcceptanceReview D ON A.SUBQUES_ID=D.SUBQUES_ID AND D.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN RPM_FLAG EE ON  A.SUBQUES_ID=EE.SUBQUES_ID AND EE.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN CENTRAL_OFFICE_FLAG F ON A.SUBQUES_ID=F.SUBQUES_ID AND F.HDR_AMEND_ID=A.HDR_AMEND_ID
	LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
    AND A.SUBQUES_ID=SQR.SUBQUES_ID
	JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID	
	JOIN CARS_218_HDR_AMEND AM ON AM.HDR_AMEND_ID=A.HDR_AMEND_ID	
    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = AM.MODULE_HDR_ID	
	JOIN CARS_ENTITY E
	ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
	JOIN CARS_ENTITY R
	ON E.REGION_ID = R.ENTITY_ID
	AND R.ENTITY_TYPE_CD = 'REGION'
	ORDER BY H.ENTITY_ID,SQ.SUBQUES_ID;	
	
	SELECT 'State/Territory' AS 'StateTerritory','Region' AS 'Region','Question' AS 'Question',
	'Recommend for Acceptance Review' AS 'RecommendforAcceptanceReview','Acceptance Review' AS 'AcceptanceReview','Flag for RPM' AS 'FlagforRPM','Flag for CO' AS 'FlagforCO', 'View Comments' AS 'ViewComments', 'REGION_ID' AS 'REGION_ID', 'subQuesNumber' AS 'subQuesNumber';

END IF;

					  
UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_218_QPR_QUESTION_REVIEW_DETAILS_REPORT');
		
END$$
DELIMITER ;