DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_218_DECISION_HISTORY_REPORT`(IN period_id INTEGER,IN entity_id TEXT,IN i_section_id TEXT)
proc_label: BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_218_DECISION_HISTORY_REPORT');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_218_DECISION_HISTORY_REPORT', 'Started', NOW());	


IF TRIM(i_section_id)!='' AND TRIM(entity_id)!='' THEN


WITH RO AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_RO_LEAST_ONCE_FLAG
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.RETURNED_RO_LEAST_ONCE_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
	GRANTEE AS(SELECT
		 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_GRANTEE_LEAST_ONCE_FLAG
		FROM CARS_218_QUES  Q
		JOIN CARS_218_SUBSECT SS
		ON SS.SUBSECT_ID = Q.SUBSECT_ID
		JOIN CARS_218_SECT S
		ON S.SECT_ID = SS.SECT_ID
		JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
		JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
		JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
		WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.RETURNED_GRANTEE_LEAST_ONCE_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)))
	
		SELECT H.ENTITY_NAME AS 'State_Territory',R.ENTITY_NAME AS REGION,S.SECT_NAME AS Section,SQ.SUBQUES_NAME AS Question,B.RETURNED_RO_LEAST_ONCE_FLAG AS 'Sent_to_RO_RPM_At_Least_Once'
			,C.RETURNED_GRANTEE_LEAST_ONCE_FLAG AS 'Sent_to_State_Territory_at_Least_Once' 
		
            FROM (SELECT SUBQUES_ID,HDR_AMEND_ID FROM RO
		UNION SELECT  SUBQUES_ID,HDR_AMEND_ID FROM GRANTEE) AS A
		LEFT JOIN RO B ON A.SUBQUES_ID=B.SUBQUES_ID AND A.HDR_AMEND_ID=B.HDR_AMEND_ID
		LEFT JOIN GRANTEE C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID	        
		LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
        AND A.SUBQUES_ID=SQR.SUBQUES_ID
		JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
        	JOIN CARS_218_QUES Q ON SQ.QUES_ID=Q.QUES_ID 
        JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_HDR_AMEND CC ON A.HDR_AMEND_ID=CC.HDR_AMEND_ID            
			JOIN CARS_MODULE_PERIOD_HDR H
			ON H.MODULE_HDR_ID = CC.MODULE_HDR_ID
			JOIN CARS_ENTITY E
			ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
			JOIN CARS_ENTITY R
			ON E.REGION_ID = R.ENTITY_ID
			AND R.ENTITY_TYPE_CD = 'REGION'
			ORDER BY A.HDR_AMEND_ID,A.SUBQUES_ID,SQ.SUBQUES_ID;			
		
		SELECT 'State/Territory' AS 'State/Territory','Region' AS REGION,'Section' AS Section,
		'Question' AS Question,'Sent to RO/RPM At Least Once' AS 'Sent to RO/RPM_At Least Once'
			,'Sent to State/Territory at Least Once' AS 'Sent to State/Territory at Least Once';

	ELSEIF TRIM(i_section_id)='' AND TRIM(entity_id)!='' THEN
		WITH RO AS(SELECT
			 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_RO_LEAST_ONCE_FLAG
			FROM CARS_218_QUES  Q
			JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
			JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
			JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
			WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.RETURNED_RO_LEAST_ONCE_FLAG=1),
		GRANTEE AS(SELECT
			 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_GRANTEE_LEAST_ONCE_FLAG
			FROM CARS_218_QUES  Q
			JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
			JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
			JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
			WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
	from json_table(
	  replace(json_array(entity_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)) AND SQR.RETURNED_GRANTEE_LEAST_ONCE_FLAG=1)
		
		
			
		SELECT H.ENTITY_NAME AS 'State_Territory',R.ENTITY_NAME AS REGION,S.SECT_NAME AS Section,SQ.SUBQUES_NAME AS Question,B.RETURNED_RO_LEAST_ONCE_FLAG AS 'Sent_to_RO_RPM_At_Least_Once'
			,C.RETURNED_GRANTEE_LEAST_ONCE_FLAG AS 'Sent_to_State_Territory_at_Least_Once' 
			
            FROM (SELECT SUBQUES_ID,HDR_AMEND_ID FROM RO
		UNION SELECT  SUBQUES_ID,HDR_AMEND_ID FROM GRANTEE) AS A
		LEFT JOIN RO B ON A.SUBQUES_ID=B.SUBQUES_ID AND A.HDR_AMEND_ID=B.HDR_AMEND_ID
		LEFT JOIN GRANTEE C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID	        
		LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
        AND A.SUBQUES_ID=SQR.SUBQUES_ID
		JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
        	JOIN CARS_218_QUES Q ON SQ.QUES_ID=Q.QUES_ID 
        JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_HDR_AMEND CC ON A.HDR_AMEND_ID=CC.HDR_AMEND_ID            
			JOIN CARS_MODULE_PERIOD_HDR H
			ON H.MODULE_HDR_ID = CC.MODULE_HDR_ID
			JOIN CARS_ENTITY E
			ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
			JOIN CARS_ENTITY R
			ON E.REGION_ID = R.ENTITY_ID
			AND R.ENTITY_TYPE_CD = 'REGION'
			ORDER BY A.HDR_AMEND_ID,A.SUBQUES_ID,SQ.SUBQUES_ID;		

		SELECT 'State/Territory' AS 'State/Territory','Region' AS REGION,'Section' AS Section,
		'Question' AS Question,'Sent to RO/RPM At Least Once' AS 'Sent to RO/RPM_At Least Once'
			,'Sent to State/Territory at Least Once' AS 'Sent to State/Territory at Least Once';	


	ELSEIF TRIM(i_section_id)!='' AND TRIM(entity_id)='' THEN
		WITH RO AS(SELECT
			 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_RO_LEAST_ONCE_FLAG
			FROM CARS_218_QUES  Q
			JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
			JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
			JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
			WHERE SQR.RETURNED_RO_LEAST_ONCE_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))),
		GRANTEE AS(SELECT
			 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_GRANTEE_LEAST_ONCE_FLAG
			FROM CARS_218_QUES  Q
			JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
			JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
			JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
			WHERE SQR.RETURNED_GRANTEE_LEAST_ONCE_FLAG=1 AND S.SECT_ID IN ((select TRIM(j.name) AS SECTID
	from json_table(
	  replace(json_array(i_section_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j)))		
		
			
		SELECT H.ENTITY_NAME AS 'State_Territory',R.ENTITY_NAME AS REGION,S.SECT_NAME AS Section,SQ.SUBQUES_NAME AS Question,B.RETURNED_RO_LEAST_ONCE_FLAG AS 'Sent_to_RO_RPM_At_Least_Once'
			,C.RETURNED_GRANTEE_LEAST_ONCE_FLAG AS 'Sent_to_State_Territory_at_Least_Once' 
			
            FROM (SELECT SUBQUES_ID,HDR_AMEND_ID FROM RO
		UNION SELECT  SUBQUES_ID,HDR_AMEND_ID FROM GRANTEE) AS A
		LEFT JOIN RO B ON A.SUBQUES_ID=B.SUBQUES_ID AND A.HDR_AMEND_ID=B.HDR_AMEND_ID
		LEFT JOIN GRANTEE C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID	        
		LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
        AND A.SUBQUES_ID=SQR.SUBQUES_ID
		JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
        	JOIN CARS_218_QUES Q ON SQ.QUES_ID=Q.QUES_ID 
        JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_HDR_AMEND CC ON A.HDR_AMEND_ID=CC.HDR_AMEND_ID            
			JOIN CARS_MODULE_PERIOD_HDR H
			ON H.MODULE_HDR_ID = CC.MODULE_HDR_ID
			JOIN CARS_ENTITY E
			ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
			JOIN CARS_ENTITY R
			ON E.REGION_ID = R.ENTITY_ID
			AND R.ENTITY_TYPE_CD = 'REGION'
			ORDER BY A.HDR_AMEND_ID,A.SUBQUES_ID,SQ.SUBQUES_ID;		

		SELECT 'State/Territory' AS 'State/Territory','Region' AS REGION,'Section' AS Section,
		'Question' AS Question,'Sent to RO/RPM At Least Once' AS 'Sent to RO/RPM_At Least Once'
			,'Sent to State/Territory at Least Once' AS 'Sent to State/Territory at Least Once';
			
	ELSE
		WITH RO AS(SELECT
			 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_RO_LEAST_ONCE_FLAG
			FROM CARS_218_QUES  Q
			JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
			JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
			JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
			WHERE SQR.RETURNED_RO_LEAST_ONCE_FLAG=1),
		GRANTEE AS(SELECT
			 DISTINCT SQ.SUBQUES_ID,SQR.HDR_AMEND_ID,'Yes' AS RETURNED_GRANTEE_LEAST_ONCE_FLAG
			FROM CARS_218_QUES  Q
			JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_SUBQUES SQ ON SQ.QUES_ID=Q.QUES_ID
			JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
			JOIN CARS_218_HDR_AMEND A ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
		    JOIN CARS_MODULE_PERIOD_HDR H ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=period_id
			WHERE SQR.RETURNED_GRANTEE_LEAST_ONCE_FLAG=1)		
		
			
		SELECT H.ENTITY_NAME AS 'State_Territory',R.ENTITY_NAME AS REGION,S.SECT_NAME AS Section,SQ.SUBQUES_NAME AS Question,B.RETURNED_RO_LEAST_ONCE_FLAG AS 'Sent_to_RO_RPM_At_Least_Once'
			,C.RETURNED_GRANTEE_LEAST_ONCE_FLAG AS 'Sent_to_State_Territory_at_Least_Once' 
			
            FROM (SELECT SUBQUES_ID,HDR_AMEND_ID FROM RO
		UNION SELECT  SUBQUES_ID,HDR_AMEND_ID FROM GRANTEE) AS A
		LEFT JOIN RO B ON A.SUBQUES_ID=B.SUBQUES_ID AND A.HDR_AMEND_ID=B.HDR_AMEND_ID
		LEFT JOIN GRANTEE C ON  C.SUBQUES_ID=A.SUBQUES_ID AND C.HDR_AMEND_ID=A.HDR_AMEND_ID	        
		LEFT JOIN (SELECT DISTINCT HDR_AMEND_ID,SUBQUES_ID FROM CARS_218_HDR_SUBQUES_REVIEW) SQR ON A.HDR_AMEND_ID=SQR.HDR_AMEND_ID
        AND A.SUBQUES_ID=SQR.SUBQUES_ID
		JOIN CARS_218_SUBQUES SQ ON  SQR.SUBQUES_ID=SQ.SUBQUES_ID
        	JOIN CARS_218_QUES Q ON SQ.QUES_ID=Q.QUES_ID 
        JOIN CARS_218_SUBSECT SS
			ON SS.SUBSECT_ID = Q.SUBSECT_ID
			JOIN CARS_218_SECT S
			ON S.SECT_ID = SS.SECT_ID
			JOIN CARS_218_HDR_AMEND CC ON A.HDR_AMEND_ID=CC.HDR_AMEND_ID            
			JOIN CARS_MODULE_PERIOD_HDR H
			ON H.MODULE_HDR_ID = CC.MODULE_HDR_ID
			JOIN CARS_ENTITY E
			ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
			JOIN CARS_ENTITY R
			ON E.REGION_ID = R.ENTITY_ID
			AND R.ENTITY_TYPE_CD = 'REGION'
			ORDER BY A.HDR_AMEND_ID,A.SUBQUES_ID,SQ.SUBQUES_ID;		

		SELECT 'State/Territory' AS 'State/Territory','Region' AS REGION,'Section' AS Section,
		'Question' AS Question,'Sent to RO/RPM At Least Once' AS 'Sent to RO/RPM_At Least Once'
			,'Sent to State/Territory at Least Once' AS 'Sent to State/Territory at Least Once';
END IF;

					  
UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_218_DECISION_HISTORY_REPORT');
		
END$$
DELIMITER ;