DROP PROCEDURE IF EXISTS CARS_800_RECORD_MANAGEMENT_DELETION;

DELIMITER $$
CREATE PROCEDURE `CARS_800_RECORD_MANAGEMENT_DELETION`(IN i_period_id INTEGER,IN i_modulemeta_id INTEGER)
proc_label: BEGIN
DECLARE v_tbl TEXT DEFAULT ''; 
DECLARE v_sql TEXT DEFAULT '';

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_800_RECORD_MANAGEMENT_DELETION');

			
		
	END;
	

	INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
	VALUES('CARS_800_RECORD_MANAGEMENT_DELETION', 'Started', NOW());
	
IF NOT EXISTS(SELECT 1 FROM CARS_MODULE_PERIOD_HDR WHERE PERIOD_ID!=i_period_id AND MODULE_META_ID=i_modulemeta_id) THEN
	CREATE OR REPLACE TEMPORARY TABLE CARS_MODULE_QUES_800_DELETED_ROWS AS 
	SELECT MODULE_QUES_ID FROM CARS_MODULE_QUES WHERE MODULE_META_ID=i_modulemeta_id;

	DELETE FROM CARS_MODULE_QUES WHERE MODULE_META_ID=i_modulemeta_id;

	DELETE FROM CARS_MODULE_QUES_MULTI_RESP WHERE EXISTS(SELECT 1 FROM CARS_MODULE_QUES_800_DELETED_ROWS AS A WHERE A.MODULE_QUES_ID=CARS_MODULE_QUES_MULTI_RESP.MODULE_QUES_ID);

	DELETE FROM CARS_MODULE_META WHERE MODULE_META_ID=i_modulemeta_id;
END IF;
		
CREATE OR REPLACE TEMPORARY TABLE CARS_MODULE_PERIOD_HDR_800_DELETED_ROWS AS 
SELECT DISTINCT MODULE_HDR_ID FROM CARS_MODULE_PERIOD_HDR WHERE PERIOD_ID=i_period_id AND MODULE_META_ID=i_modulemeta_id;

DELETE FROM CARS_MODULE_PERIOD_HDR WHERE PERIOD_ID=i_period_id AND MODULE_META_ID=i_modulemeta_id;

DELETE FROM CARS_MODULE_PERIOD_ANS WHERE EXISTS(SELECT 1 FROM CARS_MODULE_PERIOD_HDR_800_DELETED_ROWS AS A WHERE A.MODULE_HDR_ID=CARS_MODULE_PERIOD_ANS.MODULE_HDR_ID);

IF EXISTS(SELECT 1 FROM CARS_PERIOD WHERE PERIOD_ID=i_period_id AND (700_FLAG=1 OR 118A_FLAG=1 OR 901_FLAG=1 OR 118_FLAG=1 OR 801_FLAG=1 OR 218_FLAG=1)) THEN
	    UPDATE CARS_PERIOD SET 800_FLAG=0 WHERE PERIOD_ID=i_period_id;
	ELSE
	    DELETE FROM CARS_PERIOD WHERE PERIOD_ID=i_period_id;
END IF;

UPDATE CARS_RECORD_MANAGEMENT_AUDIT
SET COMPLETED_TS=NOW()
WHERE MODULE_NAME='ACF-800' AND MODULE_META_ID=i_modulemeta_id AND PERIOD_ID=i_period_id;

UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_800_RECORD_MANAGEMENT_DELETION');
		
	
END$$
DELIMITER ;