DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_218_RELEASE_ALL_LOCKS`(IN i_module_period_hdr_id INTEGER)
proc_label: BEGIN



	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_218_RELEASE_ALL_LOCKS');

			
		
	END;
	
	
	INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_218_RELEASE_ALL_LOCKS', 'Started', NOW());	



DELETE FROM CARS_218_HDR_QUES_PAGE_LOCK WHERE MODULE_HDR_ID=i_module_period_hdr_id;


UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_218_RELEASE_ALL_LOCKS');
		
	
END$$
DELIMITER ;