DROP PROCEDURE IF EXISTS CARS_801_AGGN_SP_RACE_ETHNICITY;
DELIMITER $$
CREATE PROCEDURE `CARS_801_AGGN_SP_RACE_ETHNICITY`( IN i_aggn_ref_id INT)
BEGIN

DECLARE v_rec_cnt INTEGER DEFAULT 0 ;
DECLARE v_total_rows_deleted INTEGER DEFAULT 0; 
DECLARE v_total_rows_inserted INTEGER DEFAULT 0; 
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
			 
			UPDATE CARS_801_SP_LOG
				SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
			WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_801_SP_LOG WHERE SP_NAME='CARS_801_AGGN_SP_RACE_ETHNICITY' );
			COMMIT;
		END;	
		
	INSERT INTO CARS_801_SP_LOG ( SP_NAME, START_TS)
		VALUES( 'CARS_801_AGGN_SP_RACE_ETHNICITY', NOW());	
		
		
	SELECT COUNT(*) INTO v_rec_cnt FROM CARS_801_AGGN_RACE_ETHNICITY WHERE  AGGN_REF_ID = i_aggn_ref_id;
 
		DELETE FROM CARS_801_AGGN_RACE_ETHNICITY
		WHERE AGGN_REF_ID = i_aggn_ref_id;
        
		SET v_total_rows_deleted = ROW_COUNT();
		
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_INIT;
CREATE TEMPORARY TABLE CARS_TMP_RACE_INIT AS  
SELECT
    H.MODULE_HDR_ID, 
	H.ENTITY_NAME, 
	H.ENTITY_ID,
	F.POOLING_FACTOR,
	R.FISCAL_YEAR, 
	H.FAMILY_COUNT AS FAMILY_UNADJ_AVG_COUNT, 
	C.CHILD_COUNT,
	C.POP_SAM_CHILD_COUNT AS CHILD_UNADJ_COUNT,
	SR.POPULATION_SAMPLE_CODE
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_PERIOD P
ON H.PERIOD_ID = P.PERIOD_ID
AND 801_FLAG = 1
JOIN CARS_801_AGGN_REF R
ON CAST(SUBSTR(P.PERIOD_DESC, 5, 4) AS INTEGER) = R.FISCAL_YEAR
AND R.AGGN_REF_ID = i_aggn_ref_id
JOIN CARS_801_REC_COUNTS C
ON H.MODULE_HDR_ID = C.MODULE_HDR_ID
JOIN VW_CARS_801_POOLING_FACTOR F
ON SUBSTR(P.PERIOD_DESC, 2, 7) = F.PERIOD_DESC
AND H.ENTITY_ID = F.ENTITY_ID
JOIN CARS_801_STATE_REF SR
ON H.ENTITY_ID = SR.ENTITY_ID
AND SUBSTR(P.PERIOD_DESC, 5, 4) = SR.FISCAL_YEAR
;


DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_UNADJ_DATA;
CREATE TEMPORARY TABLE CARS_TMP_RACE_UNADJ_DATA AS  
SELECT
B.MODULE_HDR_ID, B.ENTITY_ID, B.ENTITY_NAME, 
CHILD_COUNT, CHILD_UNADJ_COUNT, POOLING_FACTOR,
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (MULTI_RACE_HISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE MULTI_RACE_HISPANIC END AS MULTI_RACE_HISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (MULTI_RACE_NONHISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE MULTI_RACE_NONHISPANIC END AS MULTI_RACE_NONHISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (WHITE_HISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE WHITE_HISPANIC END AS WHITE_HISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (WHITE_NONHISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE WHITE_NONHISPANIC END AS WHITE_NONHISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (NHPI_HISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE NHPI_HISPANIC END AS NHPI_HISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (NHPI_NONHISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE NHPI_NONHISPANIC END AS NHPI_NONHISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (AA_HISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE AA_HISPANIC END AS AA_HISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (AA_NONHISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE AA_NONHISPANIC END AS AA_NONHISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (ASIAN_HISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE ASIAN_HISPANIC END AS ASIAN_HISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (ASIAN_NONHISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE ASIAN_NONHISPANIC END AS ASIAN_NONHISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (AIAN_HISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE AIAN_HISPANIC END AS AIAN_HISPANIC, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (AIAN_NONHISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE AIAN_NONHISPANIC END AS AIAN_NONHISPANIC, 

CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (INV_HISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT 
ELSE INV_HISPANIC  END AS INVALID_HISPANIC,

CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (INV_NONHISPANIC / CHILD_COUNT) * CHILD_UNADJ_COUNT 
ELSE INV_NONHISPANIC END AS INVALID_NONHISPANIC

FROM
(
SELECT MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME,
SUM(CASE WHEN AIAN_CD=1 AND HISPANIC_CD=1 THEN 1 ELSE 0 END) AS AIAN_HISPANIC,
SUM(CASE WHEN AIAN_CD=1 AND HISPANIC_CD=0 THEN 1 ELSE 0 END) AS AIAN_NONHISPANIC,

SUM(CASE WHEN ASIAN_CD=1 AND HISPANIC_CD=1 THEN 1 ELSE 0 END) AS ASIAN_HISPANIC,
SUM(CASE WHEN ASIAN_CD=1 AND HISPANIC_CD=0 THEN 1 ELSE 0 END) AS ASIAN_NONHISPANIC,

SUM(CASE WHEN AA_CD=1 AND HISPANIC_CD=1 THEN 1 ELSE 0 END) AS AA_HISPANIC,
SUM(CASE WHEN AA_CD=1 AND HISPANIC_CD=0 THEN 1 ELSE 0 END) AS AA_NONHISPANIC,

SUM(CASE WHEN NHPI_CD=1 AND HISPANIC_CD=1 THEN 1 ELSE 0 END) AS NHPI_HISPANIC,
SUM(CASE WHEN NHPI_CD=1 AND HISPANIC_CD=0 THEN 1 ELSE 0 END) AS NHPI_NONHISPANIC,

SUM(CASE WHEN WHITE_CD=1 AND HISPANIC_CD=1 THEN 1 ELSE 0 END) AS WHITE_HISPANIC,
SUM(CASE WHEN WHITE_CD=1 AND HISPANIC_CD=0 THEN 1 ELSE 0 END) AS WHITE_NONHISPANIC,

SUM(CASE WHEN MULTI_RACE_CD=1 AND HISPANIC_CD=1 THEN 1 ELSE 0 END) AS MULTI_RACE_HISPANIC,
SUM(CASE WHEN MULTI_RACE_CD=1 AND HISPANIC_CD=0 THEN 1 ELSE 0 END) AS MULTI_RACE_NONHISPANIC,

SUM(CASE WHEN INV_CD=1 AND HISPANIC_CD=1 THEN 1 ELSE 0 END) AS INV_HISPANIC,
SUM(CASE WHEN INV_CD=1 AND HISPANIC_CD=0 THEN 1 ELSE 0 END) AS INV_NONHISPANIC

FROM
(
	SELECT
	MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME,

    CASE WHEN COUNTRACE=1 AND AIAN_CD=1 THEN 1 ELSE 0 END AS AIAN_CD,
	CASE WHEN COUNTRACE=1 AND ASIAN_CD=1 THEN 1 ELSE 0 END AS ASIAN_CD,
	CASE WHEN COUNTRACE=1 AND AA_CD=1 THEN 1 ELSE 0 END AS AA_CD,
	CASE WHEN COUNTRACE=1 AND NHPI_CD=1 THEN 1 ELSE 0 END AS NHPI_CD,
	CASE WHEN COUNTRACE=1 AND WHITE_CD=1 THEN 1 ELSE 0 END AS WHITE_CD,
	CASE WHEN COUNTRACE>1 THEN 1 ELSE 0 END AS MULTI_RACE_CD,
	CASE WHEN COUNTRACE=0 THEN 1 ELSE 0 END AS INV_CD,IFNULL(HISPANIC_CD,0) AS HISPANIC_CD
	
	

	FROM 
	(
		SELECT H.MODULE_HDR_ID, H.ENTITY_ID, H.ENTITY_NAME, CHILD_ID, 
		AIAN_CD, ASIAN_CD, AA_CD, NHPI_CD, WHITE_CD, HISPANIC_CD,
		IFNULL(AIAN_CD, 0) + IFNULL(ASIAN_CD, 0) + IFNULL(AA_CD, 0) + IFNULL(NHPI_CD, 0) 
		+ IFNULL(WHITE_CD, 0) AS COUNTRACE
			

		
		FROM CARS_MODULE_PERIOD_HDR H
		JOIN CARS_PERIOD P
		ON H.PERIOD_ID = P.PERIOD_ID
		AND 801_FLAG = 1
		JOIN CARS_801_AGGN_REF R
		ON CAST(SUBSTR(P.PERIOD_DESC, 5, 4) AS INTEGER) = R.FISCAL_YEAR
		AND R.AGGN_REF_ID = i_aggn_ref_id
		JOIN CARS_801_REC_COUNTS RC
		ON H.MODULE_HDR_ID = RC.MODULE_HDR_ID
		JOIN CARS_801_CHILD C
		ON H.MODULE_HDR_ID = C.MODULE_HDR_ID
	) C ) C
	GROUP BY MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME
) B
JOIN CARS_TMP_RACE_INIT I
ON B.MODULE_HDR_ID = I.MODULE_HDR_ID
;



DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_ADJ_DATA;
CREATE TEMPORARY TABLE CARS_TMP_RACE_ADJ_DATA AS  

SELECT
MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME,
MULTI_RACE_HISPANIC_UNADJ_CNT, MULTI_RACE_HISPANIC_ADJ_CNT,
MULTI_RACE_NONHISPANIC_UNADJ_CNT, MULTI_RACE_NONHISPANIC_ADJ_CNT,

WHITE_RACE_HISPANIC_UNADJ_CNT, WHITE_RACE_HISPANIC_ADJ_CNT,
WHITE_RACE_NONHISPANIC_UNADJ_CNT, WHITE_RACE_NONHISPANIC_ADJ_CNT,

ASIAN_RACE_HISPANIC_UNADJ_CNT, ASIAN_RACE_HISPANIC_ADJ_CNT,
ASIAN_RACE_NONHISPANIC_UNADJ_CNT, ASIAN_RACE_NONHISPANIC_ADJ_CNT,

AA_RACE_HISPANIC_UNADJ_CNT, AA_RACE_HISPANIC_ADJ_CNT,
AA_RACE_NONHISPANIC_UNADJ_CNT, AA_RACE_NONHISPANIC_ADJ_CNT,

AIAN_RACE_HISPANIC_UNADJ_CNT, AIAN_RACE_HISPANIC_ADJ_CNT,
AIAN_RACE_NONHISPANIC_UNADJ_CNT, AIAN_RACE_NONHISPANIC_ADJ_CNT,

NHPI_RACE_HISPANIC_UNADJ_CNT, NHPI_RACE_HISPANIC_ADJ_CNT,
NHPI_RACE_NONHISPANIC_UNADJ_CNT, NHPI_RACE_NONHISPANIC_ADJ_CNT,

INVALID_RACE_HISPANIC_UNADJ_CNT, INVALID_RACE_HISPANIC_ADJ_CNT,
INVALID_RACE_NONHISPANIC_UNADJ_CNT, INVALID_RACE_NONHISPANIC_ADJ_CNT,

MULTI_RACE_HISPANIC_UNADJ_CNT + WHITE_RACE_HISPANIC_UNADJ_CNT + ASIAN_RACE_HISPANIC_UNADJ_CNT + AA_RACE_HISPANIC_UNADJ_CNT + AIAN_RACE_HISPANIC_UNADJ_CNT + NHPI_RACE_HISPANIC_UNADJ_CNT + INVALID_RACE_HISPANIC_UNADJ_CNT AS TOT_HISPANIC_UNADJ_CNT,
MULTI_RACE_NONHISPANIC_UNADJ_CNT + WHITE_RACE_NONHISPANIC_UNADJ_CNT + ASIAN_RACE_NONHISPANIC_UNADJ_CNT + AA_RACE_NONHISPANIC_UNADJ_CNT + AIAN_RACE_NONHISPANIC_UNADJ_CNT + NHPI_RACE_NONHISPANIC_UNADJ_CNT + INVALID_RACE_NONHISPANIC_UNADJ_CNT AS TOT_NONHISPANIC_UNADJ_CNT,

MULTI_RACE_HISPANIC_ADJ_CNT + WHITE_RACE_HISPANIC_ADJ_CNT + ASIAN_RACE_HISPANIC_ADJ_CNT + AA_RACE_HISPANIC_ADJ_CNT + AIAN_RACE_HISPANIC_ADJ_CNT + NHPI_RACE_HISPANIC_ADJ_CNT + INVALID_RACE_HISPANIC_ADJ_CNT AS TOT_HISPANIC_ADJ_CNT,
MULTI_RACE_NONHISPANIC_ADJ_CNT + WHITE_RACE_NONHISPANIC_ADJ_CNT + ASIAN_RACE_NONHISPANIC_ADJ_CNT + AA_RACE_NONHISPANIC_ADJ_CNT + AIAN_RACE_NONHISPANIC_ADJ_CNT + NHPI_RACE_NONHISPANIC_ADJ_CNT + INVALID_RACE_NONHISPANIC_ADJ_CNT AS TOT_NONHISPANIC_ADJ_CNT


FROM
(
	SELECT
	MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME,
	MULTI_RACE_HISPANIC AS MULTI_RACE_HISPANIC_UNADJ_CNT,
	WHITE_HISPANIC AS WHITE_RACE_HISPANIC_UNADJ_CNT,
	ASIAN_HISPANIC AS ASIAN_RACE_HISPANIC_UNADJ_CNT,
	AA_HISPANIC AS AA_RACE_HISPANIC_UNADJ_CNT,
	AIAN_HISPANIC AS AIAN_RACE_HISPANIC_UNADJ_CNT,
	NHPI_HISPANIC AS NHPI_RACE_HISPANIC_UNADJ_CNT,
	INVALID_HISPANIC AS INVALID_RACE_HISPANIC_UNADJ_CNT,
	
	MULTI_RACE_NONHISPANIC AS MULTI_RACE_NONHISPANIC_UNADJ_CNT,
	WHITE_NONHISPANIC AS WHITE_RACE_NONHISPANIC_UNADJ_CNT,
	ASIAN_NONHISPANIC AS ASIAN_RACE_NONHISPANIC_UNADJ_CNT,
	AA_NONHISPANIC AS AA_RACE_NONHISPANIC_UNADJ_CNT,
	AIAN_NONHISPANIC AS AIAN_RACE_NONHISPANIC_UNADJ_CNT,
	NHPI_NONHISPANIC AS NHPI_RACE_NONHISPANIC_UNADJ_CNT,
	INVALID_NONHISPANIC AS INVALID_RACE_NONHISPANIC_UNADJ_CNT,


	MULTI_RACE_HISPANIC * POOLING_FACTOR * .01 AS MULTI_RACE_HISPANIC_ADJ_CNT,
	WHITE_HISPANIC * POOLING_FACTOR * .01 AS WHITE_RACE_HISPANIC_ADJ_CNT,
	ASIAN_HISPANIC * POOLING_FACTOR * .01 AS ASIAN_RACE_HISPANIC_ADJ_CNT,
	AA_HISPANIC * POOLING_FACTOR * .01 AS AA_RACE_HISPANIC_ADJ_CNT,
	AIAN_HISPANIC * POOLING_FACTOR * .01 AS AIAN_RACE_HISPANIC_ADJ_CNT,
	NHPI_HISPANIC * POOLING_FACTOR * .01 AS NHPI_RACE_HISPANIC_ADJ_CNT,
	INVALID_HISPANIC * POOLING_FACTOR * .01 AS INVALID_RACE_HISPANIC_ADJ_CNT,
	
	MULTI_RACE_NONHISPANIC * POOLING_FACTOR * .01 AS MULTI_RACE_NONHISPANIC_ADJ_CNT,
	WHITE_NONHISPANIC * POOLING_FACTOR * .01 AS WHITE_RACE_NONHISPANIC_ADJ_CNT,
	ASIAN_NONHISPANIC * POOLING_FACTOR * .01 AS ASIAN_RACE_NONHISPANIC_ADJ_CNT,
	AA_NONHISPANIC * POOLING_FACTOR * .01 AS AA_RACE_NONHISPANIC_ADJ_CNT,
	AIAN_NONHISPANIC * POOLING_FACTOR * .01 AS AIAN_RACE_NONHISPANIC_ADJ_CNT,
	NHPI_NONHISPANIC * POOLING_FACTOR * .01 AS NHPI_RACE_NONHISPANIC_ADJ_CNT,
	INVALID_NONHISPANIC * POOLING_FACTOR * .01 AS INVALID_RACE_NONHISPANIC_ADJ_CNT

	FROM CARS_TMP_RACE_UNADJ_DATA
) A
;

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_AVG;
CREATE TEMPORARY TABLE CARS_TMP_RACE_AVG AS  
SELECT
ENTITY_ID, ENTITY_NAME,
ROUND(AVG(MULTI_RACE_HISPANIC_UNADJ_CNT), 0) AS MULTI_RACE_HISPANIC_UNADJ_CNT, ROUND(AVG(MULTI_RACE_HISPANIC_ADJ_CNT), 0) AS MULTI_RACE_HISPANIC_ADJ_CNT,
ROUND(AVG(MULTI_RACE_NONHISPANIC_UNADJ_CNT), 0) AS MULTI_RACE_NONHISPANIC_UNADJ_CNT, ROUND(AVG(MULTI_RACE_NONHISPANIC_ADJ_CNT), 0) AS MULTI_RACE_NONHISPANIC_ADJ_CNT,

ROUND(AVG(WHITE_RACE_HISPANIC_UNADJ_CNT), 0) AS WHITE_RACE_HISPANIC_UNADJ_CNT, ROUND(AVG(WHITE_RACE_HISPANIC_ADJ_CNT), 0) AS WHITE_RACE_HISPANIC_ADJ_CNT,
ROUND(AVG(WHITE_RACE_NONHISPANIC_UNADJ_CNT), 0) AS WHITE_RACE_NONHISPANIC_UNADJ_CNT, ROUND(AVG(WHITE_RACE_NONHISPANIC_ADJ_CNT), 0) AS WHITE_RACE_NONHISPANIC_ADJ_CNT,

ROUND(AVG(ASIAN_RACE_HISPANIC_UNADJ_CNT), 0) AS ASIAN_RACE_HISPANIC_UNADJ_CNT, ROUND(AVG(ASIAN_RACE_HISPANIC_ADJ_CNT), 0) AS ASIAN_RACE_HISPANIC_ADJ_CNT,
ROUND(AVG(ASIAN_RACE_NONHISPANIC_UNADJ_CNT), 0) AS ASIAN_RACE_NONHISPANIC_UNADJ_CNT, ROUND(AVG(ASIAN_RACE_NONHISPANIC_ADJ_CNT), 0) AS ASIAN_RACE_NONHISPANIC_ADJ_CNT,

ROUND(AVG(AA_RACE_HISPANIC_UNADJ_CNT), 0) AS AA_RACE_HISPANIC_UNADJ_CNT, ROUND(AVG(AA_RACE_HISPANIC_ADJ_CNT), 0) AS AA_RACE_HISPANIC_ADJ_CNT,
ROUND(AVG(AA_RACE_NONHISPANIC_UNADJ_CNT), 0) AS AA_RACE_NONHISPANIC_UNADJ_CNT, ROUND(AVG(AA_RACE_NONHISPANIC_ADJ_CNT), 0) AS AA_RACE_NONHISPANIC_ADJ_CNT,

ROUND(AVG(AIAN_RACE_HISPANIC_UNADJ_CNT), 0) AS AIAN_RACE_HISPANIC_UNADJ_CNT, ROUND(AVG(AIAN_RACE_HISPANIC_ADJ_CNT), 0) AS AIAN_RACE_HISPANIC_ADJ_CNT,
ROUND(AVG(AIAN_RACE_NONHISPANIC_UNADJ_CNT), 0) AS AIAN_RACE_NONHISPANIC_UNADJ_CNT, ROUND(AVG(AIAN_RACE_NONHISPANIC_ADJ_CNT), 0) AS AIAN_RACE_NONHISPANIC_ADJ_CNT,

ROUND(AVG(NHPI_RACE_HISPANIC_UNADJ_CNT), 0) AS NHPI_RACE_HISPANIC_UNADJ_CNT, ROUND(AVG(NHPI_RACE_HISPANIC_ADJ_CNT), 0) AS NHPI_RACE_HISPANIC_ADJ_CNT,
ROUND(AVG(NHPI_RACE_NONHISPANIC_UNADJ_CNT), 0) AS NHPI_RACE_NONHISPANIC_UNADJ_CNT, ROUND(AVG(NHPI_RACE_NONHISPANIC_ADJ_CNT), 0) AS NHPI_RACE_NONHISPANIC_ADJ_CNT,

ROUND(AVG(INVALID_RACE_HISPANIC_UNADJ_CNT), 0) AS INVALID_RACE_HISPANIC_UNADJ_CNT, ROUND(AVG(INVALID_RACE_HISPANIC_ADJ_CNT), 0) AS INVALID_RACE_HISPANIC_ADJ_CNT,
ROUND(AVG(INVALID_RACE_NONHISPANIC_UNADJ_CNT), 0) AS INVALID_RACE_NONHISPANIC_UNADJ_CNT, ROUND(AVG(INVALID_RACE_NONHISPANIC_ADJ_CNT), 0) AS INVALID_RACE_NONHISPANIC_ADJ_CNT,

ROUND(AVG(MULTI_RACE_HISPANIC_UNADJ_CNT), 0) + ROUND(AVG(WHITE_RACE_HISPANIC_UNADJ_CNT), 0) + ROUND(AVG(ASIAN_RACE_HISPANIC_UNADJ_CNT), 0) + ROUND(AVG(AA_RACE_HISPANIC_UNADJ_CNT), 0) 
+ ROUND(AVG(AIAN_RACE_HISPANIC_UNADJ_CNT), 0) + ROUND(AVG(NHPI_RACE_HISPANIC_UNADJ_CNT), 0) + ROUND(AVG(INVALID_RACE_HISPANIC_UNADJ_CNT), 0)
+ ROUND(AVG(MULTI_RACE_NONHISPANIC_UNADJ_CNT), 0) + ROUND(AVG(WHITE_RACE_NONHISPANIC_UNADJ_CNT), 0) + ROUND(AVG(ASIAN_RACE_NONHISPANIC_UNADJ_CNT), 0) + ROUND(AVG(AA_RACE_NONHISPANIC_UNADJ_CNT), 0) 
+ ROUND(AVG(AIAN_RACE_NONHISPANIC_UNADJ_CNT), 0) + ROUND(AVG(NHPI_RACE_NONHISPANIC_UNADJ_CNT), 0) + ROUND(AVG(INVALID_RACE_NONHISPANIC_UNADJ_CNT), 0) 
 AS TOT_UNADJ_CNT,

ROUND(AVG(MULTI_RACE_HISPANIC_ADJ_CNT), 0) + ROUND(AVG(WHITE_RACE_HISPANIC_ADJ_CNT), 0) + ROUND(AVG(ASIAN_RACE_HISPANIC_ADJ_CNT), 0) + ROUND(AVG(AA_RACE_HISPANIC_ADJ_CNT), 0) 
+ ROUND(AVG(AIAN_RACE_HISPANIC_ADJ_CNT), 0) + ROUND(AVG(NHPI_RACE_HISPANIC_ADJ_CNT), 0) + ROUND(AVG(INVALID_RACE_HISPANIC_ADJ_CNT), 0)
+ ROUND(AVG(MULTI_RACE_NONHISPANIC_ADJ_CNT), 0) + ROUND(AVG(WHITE_RACE_NONHISPANIC_ADJ_CNT), 0) + ROUND(AVG(ASIAN_RACE_NONHISPANIC_ADJ_CNT), 0) + ROUND(AVG(AA_RACE_NONHISPANIC_ADJ_CNT), 0) 
+ ROUND(AVG(AIAN_RACE_NONHISPANIC_ADJ_CNT), 0) + ROUND(AVG(NHPI_RACE_NONHISPANIC_ADJ_CNT), 0) + ROUND(AVG(INVALID_RACE_NONHISPANIC_ADJ_CNT), 0)
 AS TOT_ADJ_CNT

FROM CARS_TMP_RACE_ADJ_DATA
GROUP BY ENTITY_ID, ENTITY_NAME;


DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_NATIONAL;
CREATE TEMPORARY TABLE CARS_TMP_RACE_NATIONAL AS  
SELECT
0 AS ENTITY_ID, 'National' AS ENTITY_NAME,
SUM(MULTI_RACE_HISPANIC_UNADJ_CNT) AS MULTI_RACE_HISPANIC_UNADJ_CNT, SUM(MULTI_RACE_HISPANIC_ADJ_CNT) AS MULTI_RACE_HISPANIC_ADJ_CNT,
SUM(MULTI_RACE_NONHISPANIC_UNADJ_CNT) AS MULTI_RACE_NONHISPANIC_UNADJ_CNT, SUM(MULTI_RACE_NONHISPANIC_ADJ_CNT) AS MULTI_RACE_NONHISPANIC_ADJ_CNT,

SUM(WHITE_RACE_HISPANIC_UNADJ_CNT) AS WHITE_RACE_HISPANIC_UNADJ_CNT, SUM(WHITE_RACE_HISPANIC_ADJ_CNT) AS WHITE_RACE_HISPANIC_ADJ_CNT,
SUM(WHITE_RACE_NONHISPANIC_UNADJ_CNT) AS WHITE_RACE_NONHISPANIC_UNADJ_CNT, SUM(WHITE_RACE_NONHISPANIC_ADJ_CNT) AS WHITE_RACE_NONHISPANIC_ADJ_CNT,

SUM(ASIAN_RACE_HISPANIC_UNADJ_CNT) AS ASIAN_RACE_HISPANIC_UNADJ_CNT, SUM(ASIAN_RACE_HISPANIC_ADJ_CNT) AS ASIAN_RACE_HISPANIC_ADJ_CNT,
SUM(ASIAN_RACE_NONHISPANIC_UNADJ_CNT) AS ASIAN_RACE_NONHISPANIC_UNADJ_CNT, SUM(ASIAN_RACE_NONHISPANIC_ADJ_CNT) AS ASIAN_RACE_NONHISPANIC_ADJ_CNT,

SUM(AA_RACE_HISPANIC_UNADJ_CNT) AS AA_RACE_HISPANIC_UNADJ_CNT, SUM(AA_RACE_HISPANIC_ADJ_CNT) AS AA_RACE_HISPANIC_ADJ_CNT,
SUM(AA_RACE_NONHISPANIC_UNADJ_CNT) AS AA_RACE_NONHISPANIC_UNADJ_CNT, SUM(AA_RACE_NONHISPANIC_ADJ_CNT) AS AA_RACE_NONHISPANIC_ADJ_CNT,

SUM(AIAN_RACE_HISPANIC_UNADJ_CNT) AS AIAN_RACE_HISPANIC_UNADJ_CNT, SUM(AIAN_RACE_HISPANIC_ADJ_CNT) AS AIAN_RACE_HISPANIC_ADJ_CNT,
SUM(AIAN_RACE_NONHISPANIC_UNADJ_CNT) AS AIAN_RACE_NONHISPANIC_UNADJ_CNT, SUM(AIAN_RACE_NONHISPANIC_ADJ_CNT) AS AIAN_RACE_NONHISPANIC_ADJ_CNT,

SUM(NHPI_RACE_HISPANIC_UNADJ_CNT) AS NHPI_RACE_HISPANIC_UNADJ_CNT, SUM(NHPI_RACE_HISPANIC_ADJ_CNT) AS NHPI_RACE_HISPANIC_ADJ_CNT,
SUM(NHPI_RACE_NONHISPANIC_UNADJ_CNT) AS NHPI_RACE_NONHISPANIC_UNADJ_CNT, SUM(NHPI_RACE_NONHISPANIC_ADJ_CNT) AS NHPI_RACE_NONHISPANIC_ADJ_CNT,

SUM(INVALID_RACE_HISPANIC_UNADJ_CNT) AS INVALID_RACE_HISPANIC_UNADJ_CNT, SUM(INVALID_RACE_HISPANIC_ADJ_CNT) AS INVALID_RACE_HISPANIC_ADJ_CNT,
SUM(INVALID_RACE_NONHISPANIC_UNADJ_CNT) AS INVALID_RACE_NONHISPANIC_UNADJ_CNT, SUM(INVALID_RACE_NONHISPANIC_ADJ_CNT) AS INVALID_RACE_NONHISPANIC_ADJ_CNT,

SUM(TOT_UNADJ_CNT) AS TOT_UNADJ_CNT, SUM(TOT_ADJ_CNT) AS TOT_ADJ_CNT

FROM CARS_TMP_RACE_AVG;

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_PCT;
CREATE TEMPORARY TABLE CARS_TMP_RACE_PCT AS  
SELECT
ENTITY_ID, ENTITY_NAME,
ROUND((MULTI_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS MULTI_RACE_HISPANIC_PCT,
ROUND((MULTI_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS MULTI_RACE_NONHISPANIC_PCT,

ROUND((WHITE_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS WHITE_RACE_HISPANIC_PCT,
ROUND((WHITE_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS WHITE_RACE_NONHISPANIC_PCT,

ROUND((ASIAN_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS ASIAN_RACE_HISPANIC_PCT,
ROUND((ASIAN_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS ASIAN_RACE_NONHISPANIC_PCT,

ROUND((AA_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AA_RACE_HISPANIC_PCT,
ROUND((AA_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AA_RACE_NONHISPANIC_PCT,

ROUND((AIAN_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AIAN_RACE_HISPANIC_PCT,
ROUND((AIAN_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AIAN_RACE_NONHISPANIC_PCT,

ROUND((NHPI_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS NHPI_RACE_HISPANIC_PCT,
ROUND((NHPI_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS NHPI_RACE_NONHISPANIC_PCT,

ROUND((INVALID_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS INVALID_RACE_HISPANIC_PCT,
ROUND((INVALID_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS INVALID_RACE_NONHISPANIC_PCT,

CASE WHEN WHITE_RACE_HISPANIC_ADJ_CNT IS NULL THEN NULL ELSE 100.00 END AS TOT_RACE_PCT /* IF POOLING FACTOR IS NULL */

FROM CARS_TMP_RACE_AVG

UNION ALL

SELECT
ENTITY_ID, ENTITY_NAME,
ROUND((MULTI_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS MULTI_RACE_HISPANIC_PCT,
ROUND((MULTI_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS MULTI_RACE_NONHISPANIC_PCT,

ROUND((WHITE_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS WHITE_RACE_HISPANIC_PCT,
ROUND((WHITE_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS WHITE_RACE_NONHISPANIC_PCT,

ROUND((ASIAN_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS ASIAN_RACE_HISPANIC_PCT,
ROUND((ASIAN_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS ASIAN_RACE_NONHISPANIC_PCT,

ROUND((AA_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AA_RACE_HISPANIC_PCT,
ROUND((AA_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AA_RACE_NONHISPANIC_PCT,

ROUND((AIAN_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AIAN_RACE_HISPANIC_PCT,
ROUND((AIAN_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AIAN_RACE_NONHISPANIC_PCT,

ROUND((NHPI_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS NHPI_RACE_HISPANIC_PCT,
ROUND((NHPI_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS NHPI_RACE_NONHISPANIC_PCT,

ROUND((INVALID_RACE_HISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS INVALID_RACE_HISPANIC_PCT,
ROUND((INVALID_RACE_NONHISPANIC_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS INVALID_RACE_NONHISPANIC_PCT,

100.00 AS TOT_RACE_PCT
FROM CARS_TMP_RACE_NATIONAL;

INSERT INTO CARS_801_AGGN_RACE_ETHNICITY
(
AGGN_REF_ID, 
ENTITY_ID, 
ENTITY_NAME, 
INVALID_RACE_HISPANIC_CHILD_UNADJ_COUNT, 
INVALID_RACE_NONHISPANIC_CHILD_UNADJ_COUNT, 

INVALID_RACE_HISPANIC_CHILD_ADJ_COUNT, 
INVALID_RACE_NONHISPANIC_CHILD_ADJ_COUNT, 


INVALID_RACE_HISPANIC_CHILD_PERCENT, 
INVALID_RACE_NONHISPANIC_CHILD_PERCENT, 

AIAN_HISPANIC_CHILD_UNADJ_COUNT, 
AIAN_NONHISPANIC_CHILD_UNADJ_COUNT, 

AIAN_HISPANIC_CHILD_ADJ_COUNT, 
AIAN_NONHISPANIC_CHILD_ADJ_COUNT, 

AIAN_HISPANIC_CHILD_PERCENT, 
AIAN_NONHISPANIC_CHILD_PERCENT, 

ASIAN_HISPANIC_CHILD_UNADJ_COUNT, 
ASIAN_NONHISPANIC_CHILD_UNADJ_COUNT, 

ASIAN_HISPANIC_CHILD_ADJ_COUNT, 
ASIAN_NONHISPANIC_CHILD_ADJ_COUNT, 

ASIAN_HISPANIC_CHILD_PERCENT, 
ASIAN_NONHISPANIC_CHILD_PERCENT, 

AA_HISPANIC_CHILD_UNADJ_COUNT, 
AA_NONHISPANIC_CHILD_UNADJ_COUNT, 

AA_HISPANIC_CHILD_ADJ_COUNT, 
AA_NONHISPANIC_CHILD_ADJ_COUNT, 

AA_HISPANIC_CHILD_PERCENT, 
AA_NONHISPANIC_CHILD_PERCENT, 

NHPI_HISPANIC_CHILD_UNADJ_COUNT, 
NHPI_NONHISPANIC_CHILD_UNADJ_COUNT, 

NHPI_HISPANIC_CHILD_ADJ_COUNT, 
NHPI_NONHISPANIC_CHILD_ADJ_COUNT, 

NHPI_HISPANIC_CHILD_PERCENT, 
NHPI_NONHISPANIC_CHILD_PERCENT, 

WHITE_HISPANIC_CHILD_UNADJ_COUNT, 
WHITE_NONHISPANIC_CHILD_UNADJ_COUNT, 

WHITE_HISPANIC_CHILD_ADJ_COUNT, 
WHITE_NONHISPANIC_CHILD_ADJ_COUNT, 

WHITE_HISPANIC_CHILD_PERCENT, 
WHITE_NONHISPANIC_CHILD_PERCENT, 

MULTI_RACE_HISPANIC_CHILD_UNADJ_COUNT, 
MULTI_RACE_NONHISPANIC_CHILD_UNADJ_COUNT, 

MULTI_RACE_HISPANIC_CHILD_ADJ_COUNT, 
MULTI_RACE_NONHISPANIC_CHILD_ADJ_COUNT, 

MULTI_RACE_HISPANIC_CHILD_PERCENT, 
MULTI_RACE_NONHISPANIC_CHILD_PERCENT, 

TOTAL_CHILD_UNADJ_COUNT,

TOTAL_CHILD_ADJ_COUNT,

TOTAL_CHILD_PERCENT
)
SELECT
i_aggn_ref_id,
A.ENTITY_ID, 
A.ENTITY_NAME, 
INVALID_RACE_HISPANIC_UNADJ_CNT,
INVALID_RACE_NONHISPANIC_UNADJ_CNT,

INVALID_RACE_HISPANIC_ADJ_CNT,
INVALID_RACE_NONHISPANIC_ADJ_CNT,

INVALID_RACE_HISPANIC_PCT,
INVALID_RACE_NONHISPANIC_PCT,

AIAN_RACE_HISPANIC_UNADJ_CNT,
AIAN_RACE_NONHISPANIC_UNADJ_CNT,

AIAN_RACE_HISPANIC_ADJ_CNT,
AIAN_RACE_NONHISPANIC_ADJ_CNT,

AIAN_RACE_HISPANIC_PCT,
AIAN_RACE_NONHISPANIC_PCT,

ASIAN_RACE_HISPANIC_UNADJ_CNT,
ASIAN_RACE_NONHISPANIC_UNADJ_CNT,

ASIAN_RACE_HISPANIC_ADJ_CNT,
ASIAN_RACE_NONHISPANIC_ADJ_CNT,

ASIAN_RACE_HISPANIC_PCT,
ASIAN_RACE_NONHISPANIC_PCT,

AA_RACE_HISPANIC_UNADJ_CNT,
AA_RACE_NONHISPANIC_UNADJ_CNT,

AA_RACE_HISPANIC_ADJ_CNT,
AA_RACE_NONHISPANIC_ADJ_CNT,

AA_RACE_HISPANIC_PCT,
AA_RACE_NONHISPANIC_PCT,

NHPI_RACE_HISPANIC_UNADJ_CNT,
NHPI_RACE_NONHISPANIC_UNADJ_CNT,

NHPI_RACE_HISPANIC_ADJ_CNT,
NHPI_RACE_NONHISPANIC_ADJ_CNT,

NHPI_RACE_HISPANIC_PCT,
NHPI_RACE_NONHISPANIC_PCT,

WHITE_RACE_HISPANIC_UNADJ_CNT,
WHITE_RACE_NONHISPANIC_UNADJ_CNT,

WHITE_RACE_HISPANIC_ADJ_CNT,
WHITE_RACE_NONHISPANIC_ADJ_CNT,

WHITE_RACE_HISPANIC_PCT,
WHITE_RACE_NONHISPANIC_PCT,

MULTI_RACE_HISPANIC_UNADJ_CNT,
MULTI_RACE_NONHISPANIC_UNADJ_CNT,

MULTI_RACE_HISPANIC_ADJ_CNT,
MULTI_RACE_NONHISPANIC_ADJ_CNT,

MULTI_RACE_HISPANIC_PCT,
MULTI_RACE_NONHISPANIC_PCT,

TOT_UNADJ_CNT,  

TOT_ADJ_CNT, 

TOT_RACE_PCT

FROM CARS_TMP_RACE_AVG A
JOIN CARS_TMP_RACE_PCT P
ON A.ENTITY_ID = P.ENTITY_ID

UNION ALL 

SELECT
i_aggn_ref_id,
A.ENTITY_ID, 
A.ENTITY_NAME, 
INVALID_RACE_HISPANIC_UNADJ_CNT,
INVALID_RACE_NONHISPANIC_UNADJ_CNT,

INVALID_RACE_HISPANIC_ADJ_CNT,
INVALID_RACE_NONHISPANIC_ADJ_CNT,

INVALID_RACE_HISPANIC_PCT,
INVALID_RACE_NONHISPANIC_PCT,

AIAN_RACE_HISPANIC_UNADJ_CNT,
AIAN_RACE_NONHISPANIC_UNADJ_CNT,

AIAN_RACE_HISPANIC_ADJ_CNT,
AIAN_RACE_NONHISPANIC_ADJ_CNT,

AIAN_RACE_HISPANIC_PCT,
AIAN_RACE_NONHISPANIC_PCT,

ASIAN_RACE_HISPANIC_UNADJ_CNT,
ASIAN_RACE_NONHISPANIC_UNADJ_CNT,

ASIAN_RACE_HISPANIC_ADJ_CNT,
ASIAN_RACE_NONHISPANIC_ADJ_CNT,

ASIAN_RACE_HISPANIC_PCT,
ASIAN_RACE_NONHISPANIC_PCT,

AA_RACE_HISPANIC_UNADJ_CNT,
AA_RACE_NONHISPANIC_UNADJ_CNT,

AA_RACE_HISPANIC_ADJ_CNT,
AA_RACE_NONHISPANIC_ADJ_CNT,

AA_RACE_HISPANIC_PCT,
AA_RACE_NONHISPANIC_PCT,

NHPI_RACE_HISPANIC_UNADJ_CNT,
NHPI_RACE_NONHISPANIC_UNADJ_CNT,

NHPI_RACE_HISPANIC_ADJ_CNT,
NHPI_RACE_NONHISPANIC_ADJ_CNT,

NHPI_RACE_HISPANIC_PCT,
NHPI_RACE_NONHISPANIC_PCT,

WHITE_RACE_HISPANIC_UNADJ_CNT,
WHITE_RACE_NONHISPANIC_UNADJ_CNT,

WHITE_RACE_HISPANIC_ADJ_CNT,
WHITE_RACE_NONHISPANIC_ADJ_CNT,

WHITE_RACE_HISPANIC_PCT,
WHITE_RACE_NONHISPANIC_PCT,

MULTI_RACE_HISPANIC_UNADJ_CNT,
MULTI_RACE_NONHISPANIC_UNADJ_CNT,

MULTI_RACE_HISPANIC_ADJ_CNT,
MULTI_RACE_NONHISPANIC_ADJ_CNT,

MULTI_RACE_HISPANIC_PCT,
MULTI_RACE_NONHISPANIC_PCT,

TOT_UNADJ_CNT, 

TOT_ADJ_CNT, 

TOT_RACE_PCT
FROM CARS_TMP_RACE_NATIONAL A
JOIN CARS_TMP_RACE_PCT P
ON A.ENTITY_ID = P.ENTITY_ID

UNION ALL
        
SELECT 
i_aggn_ref_id, 
E.ENTITY_ID,
E.ENTITY_NAME,  
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM CARS_ENTITY E
LEFT OUTER JOIN CARS_TMP_RACE_AVG C
ON E.ENTITY_ID = C.ENTITY_ID
WHERE E.ENTITY_TYPE_CD = 'STATE-TER'
AND C.ENTITY_ID IS NULL 
;

		SET v_total_rows_inserted = ROW_COUNT();

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_INIT;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_UNADJ_DATA;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_ADJ_DATA;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_AVG;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_NATIONAL;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_PCT;

UPDATE CARS_801_SP_LOG
SET SP_STATUS_TEXT= CONCAT('Success. Rows inserted: ',v_total_rows_inserted, ' Rows Deleted :', v_total_rows_deleted), END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME ='CARS_801_AGGN_SP_RACE_ETHNICITY');
COMMIT;		
	
END$$
DELIMITER ;