DROP PROCEDURE CARS_MODULE_PERIOD_ANS_CLEANUP;
DELIMITER $$
CREATE  PROCEDURE `CARS_MODULE_PERIOD_ANS_CLEANUP`()
BEGIN DECLARE exit handler for SQLEXCEPTION
 BEGIN
  GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
   @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
  SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
  UPDATE CARS_KE_SP_LOG
  SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
  WHERE  SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_KE_SP_LOG WHERE SP_NAME='CARS_MODULE_PERIOD_ANS_CLEANUP');
 END;
 /*Log run of the SP*/
   INSERT INTO CARS_SP_LOG(SP_NAME,START_TS,SP_STATUS_TEXT) 
  SELECT 'CARS_MODULE_PERIOD_ANS_CLEANUP',NOW(),'Running';
  
 /*SP body*/
 DELETE FROM `CARS_MODULE_PERIOD_ANS` WHERE MODULE_QUES_ID=0;
 
 /*Log success of the SP*/
 UPDATE CARS_SP_LOG
  SET SP_STATUS_TEXT='Success',END_TS=NOW()
  WHERE  SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_MODULE_PERIOD_ANS_CLEANUP');
 
 END$$
DELIMITER ;