DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_218_QPR_REVIEW_PROGRESS_REPORT`(IN i_amend_id TEXT)
proc_label: BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_218_QPR_REVIEW_PROGRESS_REPORT');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_218_QPR_REVIEW_PROGRESS_REPORT', 'Started', NOW());	
SET SESSION group_concat_max_len = 10000000;



WITH RECOMMENDCNT AS(
SELECT COUNT(1) AS RECOMMEND_CNT,SQR.HDR_AMEND_ID
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_218_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID
JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON SQR.HDR_AMEND_ID=A.HDR_AMEND_ID
WHERE SQR.HDR_AMEND_ID IN ((select TRIM(j.name) AS HDR_AMEND_ID
from json_table(
  replace(json_array(i_amend_id), ',', '","'),
  '$[*]' columns (name varchar(10) path '$')
) j)) AND SQR.REVIEW_DECISION_TEXT = 'Recommend for Acceptance'
GROUP BY SQR.HDR_AMEND_ID),

RECOMMENDFORACCEPTCNT AS(
SELECT COUNT(1) AS RECOMMEND_FOR_ACCEPT_CNT,SQR.HDR_AMEND_ID
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_218_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID
JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON SQR.HDR_AMEND_ID=A.HDR_AMEND_ID
WHERE SQR.HDR_AMEND_ID IN ((select TRIM(j.name) AS HDR_AMEND_ID
from json_table(
  replace(json_array(i_amend_id), ',', '","'),
  '$[*]' columns (name varchar(10) path '$')
) j)) AND SQR.REVIEW_STATUS_TEXT = 'Recommend for Acceptance Review'
GROUP BY SQR.HDR_AMEND_ID),


NEEDSMOREINFO AS(
SELECT COUNT(1) AS NEED_MORE_INFO_CNT,SQR.HDR_AMEND_ID
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_218_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID
JOIN CARS_218_HDR_SUBQUES_REVIEW SQR ON SQR.HDR_AMEND_ID=A.HDR_AMEND_ID
WHERE SQR.HDR_AMEND_ID IN ((select TRIM(j.name) AS HDR_AMEND_ID
from json_table(
  replace(json_array(i_amend_id), ',', '","'),
  '$[*]' columns (name varchar(10) path '$')
) j)) AND SQR.REVIEW_DECISION_TEXT = 'Need more Information from State/Territory'
GROUP BY SQR.HDR_AMEND_ID),



CTE1 AS(SELECT IFNULL(A.RECOMMEND_CNT,1)/IFNULL(B.RECOMMEND_FOR_ACCEPT_CNT,1) AS Recommend,A.HDR_AMEND_ID
       FROM RECOMMENDCNT A
	   JOIN RECOMMENDFORACCEPTCNT B ON A.HDR_AMEND_ID=B.HDR_AMEND_ID
	   GROUP BY A.HDR_AMEND_ID),
CTE2 AS(SELECT IFNULL(A.NEED_MORE_INFO_CNT,1)/IFNULL(B.RECOMMEND_FOR_ACCEPT_CNT,1)
AS 'Need more Information for State/Territory',A.HDR_AMEND_ID
                      FROM NEEDSMOREINFO A
                      JOIN RECOMMENDFORACCEPTCNT B ON A.HDR_AMEND_ID=B.HDR_AMEND_ID
					  GROUP BY A.HDR_AMEND_ID)		  

SELECT H.ENTITY_NAME AS 'State/Territory',R.ENTITY_NAME AS REGION,E.REGION_ID AS REGIONID, 
CASE WHEN H.STATUS_TEXT IN ('Returned for Updates','Updates in Progress','Certified') THEN NULL ELSE CASE WHEN CA.Recommend=1 THEN '100%' ELSE CONCAT(ROUND(CA.Recommend*100,2),'%') END END AS Recommend,
CASE WHEN CB.`Need more Information for State/Territory`=1 THEN '100%' ELSE CONCAT(ROUND(CB.`Need more Information for State/Territory`*100,2),'%') END AS 'Need more Information for State/Territory',
NULL AS Undecided,
NULL AS 'Recommend For Acceptance - No Decision',
NULL AS Agree,
NULL AS Disagree,
NULL AS 'Acceptance - No Decision'

FROM (select TRIM(j.name) AS HDR_AMEND_ID
from json_table(
  replace(json_array(i_amend_id), ',', '","'),
  '$[*]' columns (name varchar(10) path '$')
) j) AS D LEFT JOIN CTE1 CA ON CA.HDR_AMEND_ID=D.HDR_AMEND_ID
LEFT JOIN CTE2 CB ON CB.HDR_AMEND_ID=D.HDR_AMEND_ID

 JOIN CARS_218_HDR_AMEND C ON D.HDR_AMEND_ID=C.HDR_AMEND_ID
JOIN CARS_MODULE_PERIOD_HDR H
ON H.MODULE_HDR_ID = C.MODULE_HDR_ID
JOIN CARS_ENTITY E
ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'STATE-TER'
JOIN CARS_ENTITY R
ON E.REGION_ID = R.ENTITY_ID
AND R.ENTITY_TYPE_CD = 'REGION';
					  
UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_218_QPR_REVIEW_PROGRESS_REPORT');
		
END$$
DELIMITER ;
                            