DELIMITER $$
CREATE OR REPLACE PROCEDURE CARS_118_LEGACY_VALIDATION_STATUS_PROC(IN i_period_id INTEGER,IN i_entity_id TEXT)
BEGIN
DECLARE v_sql TEXT DEFAULT NULL ; 
DECLARE v_entities TEXT DEFAULT NULL;
DECLARE v_period_desc INTEGER DEFAULT NULL;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_118_LEGACY_VALIDATION_STATUS_PROC');
			
		
	END;
	
		INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_118_LEGACY_VALIDATION_STATUS_PROC', 'Started', NOW());	
		
SELECT 
CAST(SUBSTR(PERIOD_DESC, 4,4) AS INTEGER) INTO v_period_desc
FROM CARS_PERIOD P
WHERE PERIOD_ID = i_period_id
;

IF i_entity_id IS NULL OR i_entity_id = '' 
THEN SET v_entities = ' ';
ELSE SET v_entities = CONCAT(' AND E.ENTITY_ID IN (', i_entity_id, ')');
END IF;

IF v_period_desc = 2014 THEN

CREATE OR REPLACE TEMPORARY TABLE QUERY_R
AS
SELECT DISTINCT 
ST.STATE_CODE, 
STPLAN_VALID_USER_ID, 
R.STPLAN_VALID_DATE AS VALID_DATE, 
CNT.CNT1 CNT1
FROM  CARS_LEGACY_118_STPLAN_VALIDATION_RESP R 
JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID 
AND S.STPLAN_VALID_REQ = 1

JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE

JOIN 
(
	SELECT  ST.STATE_CODE STATE_CODE, COUNT(DISTINCT STPLAN_VALID_RESP_ID) CNT1
	FROM CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
    JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
    ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
    AND S.STPLAN_VALID_REQ = 1
    
	JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
    ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE
	
	WHERE R.STPLAN_VALID_RESP_VALUE = 1
	AND R.STPLAN_VALID_USER_TITLE = 'R' 
	AND R.STPLAN_GROUP_ID = 3  
	AND R.STPLAN_VALID_YEAR = 2014 
	GROUP BY ST.STATE_CODE
) CNT
ON R.STPLAN_VALID_STATE_CODE= CNT.STATE_CODE  
AND CNT.CNT1 = 32

WHERE R.STPLAN_VALID_RESP_VALUE = 1
AND R.STPLAN_VALID_USER_TITLE = 'R' 
AND R.STPLAN_GROUP_ID = 3 
AND R.STPLAN_VALID_YEAR = 2014
ORDER BY STATE_CODE
;

CREATE OR REPLACE TEMPORARY TABLE QUERY_RPM
AS
SELECT DISTINCT 
ST.STATE_CODE, 
STPLAN_VALID_USER_ID, 
R.STPLAN_VALID_DATE AS VALID_DATE, 
CNT.CNT2 CNT2
FROM CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
AND S.STPLAN_VALID_REQ = 1

JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE

JOIN 
(
	SELECT  ST.STATE_CODE STATE_CODE, COUNT(DISTINCT STPLAN_VALID_RESP_ID) CNT2
	FROM CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
	JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
	ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
	AND S.STPLAN_VALID_REQ = 1 
	
	JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
	ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE
	
	WHERE R.STPLAN_VALID_RESP_VALUE = 1
	AND R.STPLAN_VALID_USER_TITLE = 'RPM' 
	AND R.STPLAN_GROUP_ID = 3  
	AND R.STPLAN_VALID_YEAR = 2014 
	GROUP BY ST.STATE_CODE
) CNT
ON R.STPLAN_VALID_STATE_CODE= CNT.STATE_CODE
AND CNT.CNT2 = 32

WHERE R.STPLAN_VALID_RESP_VALUE = 1
AND R.STPLAN_VALID_USER_TITLE = 'RPM' 
AND R.STPLAN_GROUP_ID = 3 
AND R.STPLAN_VALID_YEAR = 2014 
ORDER BY STATE_CODE
;


CREATE OR REPLACE TEMPORARY TABLE QUERY_C
AS
SELECT DISTINCT 
ST.STATE_CODE STATE_CODE, 
STPLAN_VALID_USER_ID, 
R.STPLAN_VALID_DATE AS VALID_DATE, 
CNT.CNT3 CNT3
FROM  CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID 
AND S.STPLAN_VALID_REQ = 1 

JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE

JOIN 
(
	SELECT  ST.STATE_CODE, COUNT(DISTINCT STPLAN_VALID_RESP_ID) CNT3
	FROM CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
	JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
	ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
	AND S.STPLAN_VALID_REQ = 1 
	
	JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
	ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE
	
	WHERE R.STPLAN_VALID_RESP_VALUE = 1
	AND R.STPLAN_VALID_USER_TITLE = 'C' 
	AND R.STPLAN_GROUP_ID = 2  
	AND R.STPLAN_VALID_YEAR = 2014
	GROUP BY ST.STATE_CODE
) CNT
ON R.STPLAN_VALID_STATE_CODE= CNT.STATE_CODE 
AND CNT.CNT3 = 32

WHERE R.STPLAN_VALID_RESP_VALUE = 1
AND R.STPLAN_VALID_USER_TITLE = 'C' 
AND R.STPLAN_GROUP_ID = 2 
AND R.STPLAN_VALID_YEAR = 2014
ORDER BY STATE_CODE
;


SET v_sql = '
SELECT 
STATES.STATE_NAME AS ''State_Territory'',
R.ENTITY_NAME AS ''Region'',
R.ENTITY_ID AS ''REGION_ID'',
QUERY_R.STPLAN_VALID_USER_ID AS ''Regional_Staff_Name'',
QUERY_R.VALID_DATE AS ''Regional_Staff_Date'', 
QUERY_RPM.STPLAN_VALID_USER_ID AS ''Regional_RPM_Name'',
QUERY_RPM.VALID_DATE AS ''Regional_RPM_Date'',
QUERY_C.STPLAN_VALID_USER_ID AS ''Central_Office_Name'',
QUERY_C.VALID_DATE AS ''Central_Office_Date''
FROM (SELECT DISTINCT STATE_CODE, STATE_NAME FROM CARS_LEGACY_118_STPLAN_STATE_INFO_REF) STATES
JOIN CARS_ENTITY E
ON STATES.STATE_NAME = E.ENTITY_NAME
AND E.ENTITY_TYPE_CD = ''STATE-TER''
entity_list

JOIN CARS_ENTITY R
ON E.REGION_ID = R.ENTITY_ID
AND R.ENTITY_TYPE_CD = ''REGION''

LEFT OUTER JOIN QUERY_R
ON STATES.STATE_CODE = QUERY_R.STATE_CODE

LEFT OUTER JOIN QUERY_RPM
ON STATES.STATE_CODE = QUERY_RPM.STATE_CODE

LEFT OUTER JOIN QUERY_C
ON STATES.STATE_CODE = QUERY_C.STATE_CODE

ORDER BY STATES.STATE_NAME
'
;

EXECUTE IMMEDIATE REPLACE(v_sql, 'entity_list', v_entities);

SELECT 'State/Territory' AS 'State/Territory','Region' AS 'Region', 'Region_ID' AS 'Region_ID', 'Regional Staff Name' AS 'Regional_Staff_Name', 'Regional Staff Date' AS 'Regional_Staff_Date', 'Regional RPM Name' as 'Regional_RPM_Name',
	   'Regional RPM Date' AS 'Regional_RPM_Date', 'Central Office Name' as 'Central_Office_Name',
	   'Central Office Date' AS 'Central_Office_Date';

ELSE

CREATE OR REPLACE TEMPORARY TABLE QUERY_R
AS
SELECT DISTINCT 
ST.STATE_CODE, 
STPLAN_VALID_USER_ID, 
R.STPLAN_VALID_DATE  AS VALID_DATE, 
CNT.CNT1 CNT1
FROM  CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
AND S.STPLAN_VALID_REQ = 1 

JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE

JOIN 
(
	SELECT  ST.STATE_CODE STATE_CODE, COUNT(DISTINCT STPLAN_VALID_RESP_ID) CNT1
	FROM CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
	JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
	ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
	AND S.STPLAN_VALID_REQ = 1
	
	JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
	ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE
	WHERE R.STPLAN_VALID_RESP_VALUE = 1
	AND R.STPLAN_VALID_USER_TITLE = 'R' 
	AND R.STPLAN_GROUP_ID = 3  
	AND R.STPLAN_VALID_YEAR = v_period_desc
	GROUP BY ST.STATE_CODE
) CNT
ON R.STPLAN_VALID_STATE_CODE= CNT.STATE_CODE 
AND ( 	(CNT.CNT1 = 125 and R.STPLAN_VALID_YEAR=2016) or 
					(CNT.CNT1 = 215 and R.STPLAN_VALID_YEAR=2019) or 
					(CNT.CNT1 = 9 and R.STPLAN_VALID_YEAR=2022) )
					
WHERE R.STPLAN_VALID_RESP_VALUE = 1
AND R.STPLAN_VALID_USER_TITLE = 'R' 
AND R.STPLAN_GROUP_ID = 3 
AND R.STPLAN_VALID_YEAR = v_period_desc
ORDER BY STATE_CODE
;

CREATE OR REPLACE TEMPORARY TABLE QUERY_RPM
AS
SELECT DISTINCT 
ST.STATE_CODE, 
STPLAN_VALID_USER_ID, 
R.STPLAN_VALID_DATE AS VALID_DATE, 
CNT.CNT2 CNT2
FROM  CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
AND S.STPLAN_VALID_REQ = 1
JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE

JOIN
(
	SELECT ST.STATE_CODE STATE_CODE, COUNT(DISTINCT STPLAN_VALID_RESP_ID) CNT2
	FROM CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
	JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
	ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID 
	AND S.STPLAN_VALID_REQ = 1 
	
	JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
	ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE
	
	WHERE R.STPLAN_VALID_RESP_VALUE = 1
	AND R.STPLAN_VALID_USER_TITLE = 'RPM' 
	AND R.STPLAN_GROUP_ID = 3  
	AND R.STPLAN_VALID_YEAR = v_period_desc
	GROUP BY ST.STATE_CODE
) CNT
ON R.STPLAN_VALID_STATE_CODE= CNT.STATE_CODE 
AND (	(CNT.CNT2 = 125 and R.STPLAN_VALID_YEAR=2016) or 
				(CNT.CNT2 = 215 and R.STPLAN_VALID_YEAR=2019) or 
				(CNT.CNT2 = 9 and R.STPLAN_VALID_YEAR=2022) )
				
WHERE R.STPLAN_VALID_RESP_VALUE = 1
AND R.STPLAN_VALID_USER_TITLE = 'RPM' 
AND R.STPLAN_GROUP_ID = 3 
AND R.STPLAN_VALID_YEAR = v_period_desc
ORDER BY STATE_CODE
;

CREATE OR REPLACE TEMPORARY TABLE QUERY_C
AS
SELECT DISTINCT 
ST.STATE_CODE STATE_CODE, 
STPLAN_VALID_USER_ID, 
R.STPLAN_VALID_DATE AS VALID_DATE, 
CNT.CNT3 CNT3
FROM  CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
AND S.STPLAN_VALID_REQ = 1

JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE

JOIN 
(
	SELECT ST.STATE_CODE, COUNT(DISTINCT STPLAN_VALID_RESP_ID) CNT3
	FROM CARS_LEGACY_118_STPLAN_VALIDATION_RESP R
	JOIN CARS_LEGACY_118_STPLAN_VALIDATION_SECT S
	ON R.STPLAN_VALID_SECT_ID = S.STPLAN_VALID_SECT_ID
	AND S.STPLAN_VALID_REQ = 1
	
	JOIN CARS_LEGACY_118_STPLAN_STATE_INFO_REF ST
	ON R.STPLAN_VALID_STATE_CODE = ST.STATE_CODE
	
	WHERE R.STPLAN_VALID_RESP_VALUE = 1
	AND R.STPLAN_VALID_USER_TITLE = 'C' 
	AND R.STPLAN_GROUP_ID = 2  
	AND R.STPLAN_VALID_YEAR = v_period_desc
	GROUP BY ST.STATE_CODE
) CNT
ON R.STPLAN_VALID_STATE_CODE= CNT.STATE_CODE

WHERE R.STPLAN_VALID_RESP_VALUE = 1
AND R.STPLAN_VALID_USER_TITLE = 'C' 
AND R.STPLAN_GROUP_ID = 2 
AND R.STPLAN_VALID_YEAR = v_period_desc
AND (	(CNT.CNT3 = 125 and R.STPLAN_VALID_YEAR=2016) or
		(CNT.CNT3 = 215 and R.STPLAN_VALID_YEAR=2019) or 
		(CNT.CNT3 = 9 and R.STPLAN_VALID_YEAR=2022) )
ORDER BY STATE_CODE
;

SET v_sql = '
SELECT 
STATES.STATE_NAME AS ''State_Territory'',
R.ENTITY_NAME AS ''Region'',
R.ENTITY_ID AS ''REGION_ID'',
QUERY_R.STPLAN_VALID_USER_ID AS ''Regional_Staff_Name'',
QUERY_R.VALID_DATE AS ''Regional_Staff_Date'', 
QUERY_RPM.STPLAN_VALID_USER_ID AS ''Regional_RPM_Name'',
QUERY_RPM.VALID_DATE AS ''Regional_RPM_Date'',
QUERY_C.STPLAN_VALID_USER_ID AS ''Central_Office_Name'',
QUERY_C.VALID_DATE AS ''Central_Office_Date''
FROM (SELECT DISTINCT STATE_CODE, STATE_NAME FROM CARS_LEGACY_118_STPLAN_STATE_INFO_REF ) STATES
JOIN CARS_ENTITY E
ON STATES.STATE_NAME = E.ENTITY_NAME
AND E.ENTITY_TYPE_CD = ''STATE-TER''
entity_list

JOIN CARS_ENTITY R
ON E.REGION_ID = R.ENTITY_ID
AND R.ENTITY_TYPE_CD = ''REGION''

LEFT OUTER JOIN QUERY_R
ON STATES.STATE_CODE = QUERY_R.STATE_CODE

LEFT OUTER JOIN QUERY_RPM
ON STATES.STATE_CODE = QUERY_RPM.STATE_CODE

LEFT OUTER JOIN QUERY_C
ON STATES.STATE_CODE = QUERY_C.STATE_CODE

ORDER BY	STATES.STATE_NAME
'
;

EXECUTE IMMEDIATE REPLACE(v_sql, 'entity_list', v_entities);

SELECT 'State/Territory' AS 'State/Territory','Region' AS 'Region', 'Region_ID' AS 'Region_ID', 'Regional Staff Name' AS 'Regional_Staff_Name','Regional Staff Date' AS 'Regional_Staff_Date', 'Regional RPM Name' as 'Regional_RPM_Name', 'Regional RPM Date' AS 'Regional_RPM_Date', 'Central Office Name' as 'Central_Office_Name', 'Central Office Date' AS 'Central_Office_Date';

END IF;


UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_118_LEGACY_VALIDATION_STATUS_PROC');
		
END$$
DELIMITER ;