DELIMITER $$
CREATE OR REPLACE PROCEDURE CARS_801_AGGN_SP_ETHNICITY( IN i_aggn_ref_id INT)
BEGIN
/**********************************************************
 * Author: Zohreh Torabian
 * Report Name: Average Monthly Counts 
				and Percentages of Children by Latino Ethnicity
 * Report Number: 320
 * Desc: It populates data for table, 
 *		 CARS_801_AGGN_ETHNICITY.
 **********************************************************/
DECLARE v_rec_cnt INTEGER DEFAULT 0 ;
DECLARE v_total_rows_deleted INTEGER DEFAULT 0; 
DECLARE v_total_rows_inserted INTEGER DEFAULT 0; 
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
			 
			UPDATE CARS_801_SP_LOG
				SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
			WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_801_SP_LOG WHERE SP_NAME='CARS_801_AGGN_SP_ETHNICITY' );
			COMMIT;
		END;	
		
	INSERT INTO CARS_801_SP_LOG ( SP_NAME, START_TS)
		VALUES( 'CARS_801_AGGN_SP_ETHNICITY',  NOW());	
		
		
	SELECT COUNT(*) INTO v_rec_cnt FROM CARS_801_AGGN_ETHNICITY WHERE  AGGN_REF_ID = i_aggn_ref_id;
 
		DELETE FROM CARS_801_AGGN_ETHNICITY
		WHERE AGGN_REF_ID = i_aggn_ref_id;
        
		SET v_total_rows_deleted = ROW_COUNT();


DROP TEMPORARY TABLE IF EXISTS TMP_MOD_HDR_M;
CREATE TEMPORARY TABLE TMP_MOD_HDR_M AS
				    SELECT 	DISTINCT HDR.MODULE_HDR_ID 
						   
						   ,AGGN_REF_ID
						   ,HDR.ENTITY_ID
						   ,HDR.ENTITY_NAME	
						   ,REC.POP_SAM_CHILD_COUNT AS CHILD_MO_UNADJ_CNT
						   ,REC.CHILD_COUNT 		AS CHILD_CNT
						   ,AGGN_RF.FISCAL_YEAR 
						   ,SR.POPULATION_SAMPLE_CODE
							FROM CARS_MODULE_PERIOD_HDR HDR 
								JOIN CARS_PERIOD P 
							ON P.PERIOD_ID=HDR.PERIOD_ID 
							AND P.801_FLAG = 1
								JOIN CARS_801_REC_COUNTS REC
							ON REC.MODULE_HDR_ID=HDR.MODULE_HDR_ID
								JOIN CARS_801_AGGN_REF AGGN_RF 
							ON CAST(SUBSTR(P.PERIOD_DESC,5,4) AS INTEGER) =AGGN_RF.FISCAL_YEAR
							AND AGGN_RF.AGGN_REF_ID= i_aggn_ref_id
							   JOIN CARS_801_STATE_REF SR
							ON HDR.ENTITY_ID = SR.ENTITY_ID
							AND SUBSTR(P.PERIOD_DESC, 5, 4) = SR.FISCAL_YEAR;
							



 DROP TEMPORARY TABLE IF EXISTS TMP_ETH_CNT;
CREATE TEMPORARY TABLE  TMP_ETH_CNT AS
 SELECT 
					HDR.MODULE_HDR_ID
					
					,HDR.ENTITY_NAME
					,HDR.FISCAL_YEAR
                    ,COUNT(CASE WHEN CHD.HISPANIC_CD=1 THEN 1 END ) 										HISP_CNT
                    ,COUNT(CASE WHEN CHD.HISPANIC_CD=0 THEN 1 END ) 										NON_HSP_CNT
                     ,COUNT(CASE WHEN CHD.HISPANIC_CD IS NULL OR CHD.HISPANIC_CD NOT IN (1,0) THEN  1 END ) INVAL_CNT 
				
                     FROM  TMP_MOD_HDR_M HDR
						JOIN CARS_801_CHILD CHD 
					ON CHD.MODULE_HDR_ID=HDR.MODULE_HDR_ID GROUP BY 1,2,3;
               
DROP TEMPORARY TABLE IF EXISTS TMP_ETH_SM;
CREATE TEMPORARY TABLE  TMP_ETH_SM AS
		SELECT 
			RAT.ENTITY_NAME
            ,C_CNT.ENTITY_ID
			,RAT.FISCAL_YEAR 
           
			,CASE WHEN POPULATION_SAMPLE_CODE ='S' THEN IFNULL(RAT.HISPANIC_RATIO,0)*IFNULL(C_CNT.CHILD_MO_UNADJ_CNT,0) 	ELSE RAT.HISPANIC_RATIO END    		HISPANIC_VAL 
			,CASE WHEN POPULATION_SAMPLE_CODE ='S' THEN IFNULL(RAT.NON_HISPANIC_RATIO,0)*IFNULL(C_CNT.CHILD_MO_UNADJ_CNT,0) ELSE RAT.NON_HISPANIC_RATIO END   	NON_HISPANIC_VAL
            ,CASE WHEN POPULATION_SAMPLE_CODE ='S' THEN IFNULL(RAT.INVALID,0)*IFNULL(C_CNT.CHILD_MO_UNADJ_CNT,0) 			ELSE RAT.INVALID END  				INVALID_VAL
			
			
			                   
		FROM (                
          SELECT 			
					HDR.MODULE_HDR_ID
					
					,HDR.ENTITY_NAME
					,HDR.FISCAL_YEAR	
					,CASE WHEN HDR.CHILD_CNT>0  AND HDR.POPULATION_SAMPLE_CODE='S' THEN  
																	
								HISP_CNT/HDR.CHILD_CNT 
					 WHEN CHILD_MO_UNADJ_CNT >0 AND HDR.POPULATION_SAMPLE_CODE='P' THEN HISP_CNT
				 
					ELSE 0  END 
                    AS HISPANIC_RATIO
                    
					,CASE WHEN HDR.CHILD_CNT>0  
							AND  HDR.POPULATION_SAMPLE_CODE='S' THEN  
																	
								NON_HSP_CNT/HDR.CHILD_CNT 
					WHEN CHILD_MO_UNADJ_CNT >0  
							AND   HDR.POPULATION_SAMPLE_CODE='P' THEN NON_HSP_CNT 
				 
					ELSE 0 END AS NON_HISPANIC_RATIO
                    , CASE WHEN HDR.CHILD_CNT>0 AND  HDR.POPULATION_SAMPLE_CODE='S' THEN
                	INVAL_CNT/HDR.CHILD_CNT
                    WHEN  CHILD_MO_UNADJ_CNT >0 AND HDR.POPULATION_SAMPLE_CODE='P' THEN  INVAL_CNT
																								
                    ELSE 0  
                                                                                             
                                                                                             
                    END INVALID 
					FROM  TMP_ETH_CNT CHD
						JOIN TMP_MOD_HDR_M HDR  
					ON CHD.MODULE_HDR_ID=HDR.MODULE_HDR_ID
					        
		) RAT 
        JOIN (
								SELECT DISTINCT HDR2.MODULE_HDR_ID
            					   ,HDR2.ENTITY_ID
								   ,HDR2.ENTITY_NAME
            					   ,HDR2.FISCAL_YEAR
								   ,HDR2.CHILD_MO_UNADJ_CNT
								   ,HDR2.POPULATION_SAMPLE_CODE
								 FROM TMP_MOD_HDR_M HDR2  
								 
							) C_CNT
			ON RAT.MODULE_HDR_ID=C_CNT.MODULE_HDR_ID
			AND RAT.ENTITY_NAME=C_CNT.ENTITY_NAME ;
			
		

DROP TEMPORARY TABLE IF EXISTS CARS_801_TEMP_ETHNICITY_TOT;
CREATE TEMPORARY TABLE  CARS_801_TEMP_ETHNICITY_TOT AS           
       
                    SELECT

						 ETH_SM.ENTITY_NAME
						,ETH_SM.ENTITY_ID
						/* ,ETH_SM.FISCAL_YEAR */

						 
						/* child count w/ hispanic or non-hispanic ethnicity. */
						/* in this section, it uses formula to populate child unadjusted/adjusted count per state and fiscal year w/ hispanic/non-hispanic enthnicity and invalid values*/
						/* in this section, it uses formula to populate child count percentage per state and fiscal year w/ hispanic/non-hispanic enthnicity*/
						/*Hispanic ethnicity*/
						,ROUND(IFNULL(ETH_SM.HISPANIC_AVG,0)) 																								LATINO_CHILD_UNADJ_COUNT
						,CASE WHEN FACT.PFACTOR>0  THEN  ROUND(IFNULL(ETH_SM.HISPANIC_AVG,0)*FACT.PFACTOR) ELSE NULL END  									LATINO_CHILD_ADJ_COUNT
						,CASE WHEN FACT.PFACTOR>0  THEN CASE WHEN TOTAL_WGHT>0 	THEN  ROUND((ETH_SM.HISPANIC_SUM/TOTAL_WGHT) * 100,2) ELSE 0 END 
                        		ELSE NULL END 																												LATINO_PCT
						/*Non-Hispanic ethnicity*/
						,ROUND(IFNULL(ETH_SM.NON_HISPANIC_AVG,0))  																							NON_LATINO_CHILD_UNADJ_COUNT
						,CASE WHEN FACT.PFACTOR>0 	THEN ROUND(IFNULL(ETH_SM.NON_HISPANIC_AVG,0)*FACT.PFACTOR) ELSE NULL END 								NON_LATINO_CHILD_ADJ_COUNT
					    ,CASE WHEN FACT.PFACTOR>0  THEN CASE WHEN TOTAL_WGHT>0 	THEN ROUND((ETH_SM.NON_HISPANIC_SUM/TOTAL_WGHT) * 100,2) ELSE 0 END 
                        	  ELSE NULL END  																												NON_LATINO_PCT
						/*Invalid values */
						,ROUND(IFNULL(ETH_SM.INVALID_AVG,0))  																						   		INVALID_ETH_CHILD_UNADJ_COUNT
						,CASE WHEN FACT.PFACTOR>0 	THEN ROUND(IFNULL(ETH_SM.INVALID_AVG,0)*FACT.PFACTOR) ELSE NULL END										INVALID_ETH_CHILD_ADJ_COUNT
						,CASE WHEN FACT.PFACTOR>0  THEN CASE WHEN TOTAL_WGHT>0 	THEN ROUND((ETH_SM.INVALID_SUM/TOTAL_WGHT),2) * 100  ELSE 0 END 
                        	ELSE NULL END 																													INVALID_PCT
						
                    FROM (
					SELECT 
						ENTITY_NAME
						,ENTITY_ID
						,FISCAL_YEAR 
						,AVG(HISPANIC_VAL) 				HISPANIC_AVG
						,AVG(NON_HISPANIC_VAL) 			NON_HISPANIC_AVG
						,AVG(INVALID_VAL) 				INVALID_AVG
						,SUM(HISPANIC_VAL)				HISPANIC_SUM
						,SUM(NON_HISPANIC_VAL) 			NON_HISPANIC_SUM
						,SUM(INVALID_VAL) 				INVALID_SUM
						,(SUM(HISPANIC_VAL) + 
						 SUM(NON_HISPANIC_VAL)+
						 SUM(INVALID_VAL))				TOTAL_WGHT
						FROM  TMP_ETH_SM 
						
						GROUP BY 1,2,3
						) ETH_SM


                    LEFT JOIN ( SELECT ENTITY_ID
                                ,ENTITY_NAME
                                ,PERIOD_DESC
                                ,IFNULL(POOLING_FACTOR,0)*.01 AS PFACTOR 
                                FROM VW_CARS_801_POOLING_FACTOR FACT 
                          ) FACT

                ON 	FACT.PERIOD_DESC LIKE CONCAT('%',ETH_SM.FISCAL_YEAR)
                AND FACT.ENTITY_NAME=ETH_SM.ENTITY_NAME;

 INSERT INTO CARS_801_AGGN_ETHNICITY
(
	AGGN_REF_ID, 
	ENTITY_ID, 
	ENTITY_NAME, 
	INVALID_ETHNICITY_CHILD_UNADJ_COUNT, 
	INVALID_ETHNICITY_CHILD_ADJ_COUNT, 
	INVALID_ETHNICITY_CHILD_PERCENT, 
	LATINO_CHILD_UNADJ_COUNT, 
	LATINO_CHILD_ADJ_COUNT, 
	LATINO_CHILD_PERCENT, 
	NOT_LATINO_CHILD_UNADJ_COUNT, 
	NOT_LATINO_CHILD_ADJ_COUNT, 
	NOT_LATINO_CHILD_PERCENT 


)
       SELECT 
       i_aggn_ref_id
       	,ENTITY_ID
        ,ENTITY_NAME
		,ROUND(INVALID_ETH_CHILD_UNADJ_COUNT,2)			INVALID_ETH_CHILD_UNADJ_COUNT
        ,ROUND(INVALID_ETH_CHILD_ADJ_COUNT,2)			INVALID_ETH_CHILD_ADJ_COUNT
        ,ROUND(INVALID_PCT,2)							INVALID_PCT
        ,ROUND(LATINO_CHILD_UNADJ_COUNT,2)				LATINO_CHILD_UNADJ_COUNT
        ,ROUND(LATINO_CHILD_ADJ_COUNT,2)				LATINO_CHILD_ADJ_COUNT
        ,ROUND(LATINO_PCT,2)							LATINO_PCT
        
        ,ROUND(NON_LATINO_CHILD_UNADJ_COUNT,2)			NON_LATINO_CHILD_UNADJ_COUNT
        ,ROUND(NON_LATINO_CHILD_ADJ_COUNT,2)			NON_LATINO_CHILD_ADJ_COUNT
        ,ROUND(NON_LATINO_PCT,2)						NON_LATINO_PCT
        
       
        FROM CARS_801_TEMP_ETHNICITY_TOT
        UNION ALL 
        SELECT
        i_aggn_ref_id
         ,0
         ,'National'
       
        ,ROUND(NAT_INVALID_ETH_CHILD_UNADJ_COUNT,2)
        ,ROUND(NAT_INVALID_ETH_CHILD_ADJ_COUNT,2)
        ,CASE WHEN  TOTAL_ADJ_CNT> 0 THEN ROUND((NAT_INVALID_ETH_CHILD_ADJ_COUNT/TOTAL_ADJ_CNT)*100,2) ELSE NULL END			NAT_INVALID_PCT
       
		,ROUND(NAT_LATINO_CHILD_UNADJ_COUNT,2)
        ,ROUND(NAT_LATINO_CHILD_ADJ_COUNT,2)
        ,CASE WHEN  TOTAL_ADJ_CNT> 0 THEN ROUND((NAT_LATINO_CHILD_ADJ_COUNT/TOTAL_ADJ_CNT)*100,2) ELSE NULL END 				NAT_LATINO_PCT
         
        ,ROUND(NAT_NON_LATINO_CHILD_UNADJ_COUNT,2)
        ,ROUND(NAT_NON_LATINO_CHILD_ADJ_COUNT,2)
        ,CASE WHEN TOTAL_ADJ_CNT> 0 THEN ROUND((NAT_NON_LATINO_CHILD_ADJ_COUNT/TOTAL_ADJ_CNT)*100,2)  ELSE NULL END 				NAT_NOT_LATINO_PCT
        
        
       
        
         FROM 
         (
                 SELECT
                 SUM(INVALID_ETH_CHILD_UNADJ_COUNT) 			AS NAT_INVALID_ETH_CHILD_UNADJ_COUNT
                ,SUM(INVALID_ETH_CHILD_ADJ_COUNT) 				AS NAT_INVALID_ETH_CHILD_ADJ_COUNT

                ,SUM(LATINO_CHILD_UNADJ_COUNT) 					AS NAT_LATINO_CHILD_UNADJ_COUNT
                ,SUM(LATINO_CHILD_ADJ_COUNT) 					AS NAT_LATINO_CHILD_ADJ_COUNT
                ,SUM(NON_LATINO_CHILD_UNADJ_COUNT)				AS NAT_NON_LATINO_CHILD_UNADJ_COUNT
                ,SUM(NON_LATINO_CHILD_ADJ_COUNT)				AS NAT_NON_LATINO_CHILD_ADJ_COUNT
                ,SUM(LATINO_CHILD_ADJ_COUNT)+
				SUM(NON_LATINO_CHILD_ADJ_COUNT)+
				SUM(INVALID_ETH_CHILD_ADJ_COUNT)				AS TOTAL_ADJ_CNT						
                FROM CARS_801_TEMP_ETHNICITY_TOT
        ) NAT_DAT
	UNION ALL
		SELECT 
			i_aggn_ref_id
			,E.ENTITY_ID		   
			,E.ENTITY_NAME
			
			,NULL
			,NULL
			,NULL
			
			,NULL
			,NULL
			,NULL
			
			,NULL
			,NULL
			,NULL
		 FROM CARS_ENTITY E
			  LEFT OUTER JOIN CARS_801_TEMP_ETHNICITY_TOT C
		 ON E.ENTITY_ID = C.ENTITY_ID
		 WHERE E.ENTITY_TYPE_CD = 'STATE-TER'
		 AND C.ENTITY_ID IS NULL ;
SET v_total_rows_inserted = ROW_COUNT();

DROP TEMPORARY TABLE IF EXISTS TMP_MOD_HDR_M;
DROP TEMPORARY TABLE IF EXISTS TMP_ETH_CNT;
DROP TEMPORARY TABLE IF EXISTS TMP_ETH_SM;
DROP TEMPORARY TABLE IF EXISTS CARS_801_TEMP_ETHNICITY_TOT;


UPDATE CARS_801_SP_LOG
SET SP_STATUS_TEXT= CONCAT('Success. Rows inserted: ',v_total_rows_inserted, ' Rows Deleted :', v_total_rows_deleted), END_TS=NOW()
 
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME ='CARS_801_AGGN_SP_ETHNICITY');
COMMIT;		
	
END$$
DELIMITER ;