DROP PROCEDURE IF EXISTS CARS_118A_REVIEW_COMMENT_REPORT;
DELIMITER $$

CREATE PROCEDURE CARS_118A_REVIEW_COMMENT_REPORT(IN i_period_id INTEGER,IN i_lead_agency_entity_ids TEXT,IN i_sect_ids TEXT,IN i_amend_id TEXT)
proc_label: BEGIN


	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_118A_REVIEW_COMMENT_REPORT');

			
		
	END;
	
	
	INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_118A_REVIEW_COMMENT_REPORT', 'Started', NOW());

CREATE OR REPLACE TEMPORARY TABLE CARS_118A_HDR_SUBQUES_REVIEW_COMMENT_TMP AS
SELECT 	C.COMMENT_TYPE_CD, 
	C.COMMENT_TEXT, 
	C.GRANTEE_VISIBLE_FLAG, 
	C.LAST_UPD_BY, 
	C.LAST_UPD_TS, 		
	C.ROLE_NAME,
	C.HDR_SUBQUES_REVIEW_ID
FROM CARS_118A_HDR_SUBQUES_REVIEW_COMMENT C 	
WHERE EXISTS ((select TRIM(j.name) AS HDR_AMEND_ID
	from json_table(
	  replace(json_array(i_amend_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j WHERE TRIM(j.name)=C.HDR_AMEND_ID));

CREATE INDEX CARS_118A_HDR_SUBQUES_REVIEW_COMMENT_TMP_IXP ON CARS_118A_HDR_SUBQUES_REVIEW_COMMENT_TMP(HDR_SUBQUES_REVIEW_ID);
		
CREATE OR REPLACE TEMPORARY TABLE CARS_118A_REVIEW_COMMENT_REPORT_TMP AS
SELECT  row_number() OVER() AS ROW_SEQ_NUM, 
    HDR_AMEND_ID, 
	PERIOD_ID, 
	LEAD_AGENCY_ENTITY_ID, 
	LEAD_AGENCY_NAME, 
	STATE, 
	REGION_ID, 
	REGION, 
	ALLOCATION_SIZE, 
	Plan_Version,
	SECT_NAME, 
	COMMENT_TYPE_CD, 
	COMMENT_TEXT, 
	GRANTEE_VISIBLE_FLAG, 
	LAST_UPD_BY, 
	LAST_UPD_TS, 
	OGM_TRIBAL_CD,
	ROLE,
	SECT_ID,
	QUES_NAME,
	QUES_ID
	FROM(
SELECT DISTINCT 
	A.HDR_AMEND_ID AS HDR_AMEND_ID, 
	H.PERIOD_ID AS PERIOD_ID, 
	H.ENTITY_ID AS LEAD_AGENCY_ENTITY_ID, 
	E.ENTITY_NAME AS LEAD_AGENCY_NAME, 
	ST.ENTITY_NAME AS STATE, 
	E.REGION_ID AS REGION_ID, 
	R.ENTITY_NAME AS REGION, 
	I.ALLOCATION_SIZE AS ALLOCATION_SIZE, 
	CASE WHEN A.AMEND_SEQ_NUM>1 THEN CONCAT('Amendment #',A.AMEND_SEQ_NUM-1) ELSE 'Initial Plan' END AS 'Plan_Version',
	S.SECT_NAME AS SECT_NAME, 
	C.COMMENT_TYPE_CD AS COMMENT_TYPE_CD, 
	C.COMMENT_TEXT AS COMMENT_TEXT, 
	C.GRANTEE_VISIBLE_FLAG AS GRANTEE_VISIBLE_FLAG, 
	C.LAST_UPD_BY AS LAST_UPD_BY, 
	C.LAST_UPD_TS AS LAST_UPD_TS, 
	E.OGM_TRIBAL_CD AS OGM_TRIBAL_CD,
	C.ROLE_NAME AS ROLE,
	S.SECT_ID,
	Q.QUES_NAME,
	Q.QUES_ID
FROM
CARS_MODULE_PERIOD_HDR H
JOIN CARS_118A_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID AND H.PERIOD_ID=i_period_id
JOIN CARS_ENTITY E
ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = 'TRIBE'
JOIN CARS_TRIBE_INFO I
ON H.ENTITY_ID = I.TRIBE_ID AND H.PERIOD_ID = I.PERIOD_ID
JOIN CARS_ENTITY R
ON E.REGION_ID = R.ENTITY_ID AND R.ENTITY_TYPE_CD = 'REGION'
JOIN CARS_ENTITY ST
ON E.ENTITY_STATE_CD = ST.ENTITY_STATE_CD AND ST.ENTITY_TYPE_CD = 'STATE-TER'
JOIN CARS_118A_HDR_SUBQUES_REVIEW W
ON A.HDR_AMEND_ID = W.HDR_AMEND_ID
JOIN CARS_118A_HDR_SUBQUES_REVIEW_COMMENT_TMP C 
ON W.HDR_SUBQUES_REVIEW_ID = C.HDR_SUBQUES_REVIEW_ID
JOIN CARS_118A_SUBQUES SQ ON W.SUBQUES_ID=SQ.SUBQUES_ID
JOIN CARS_118A_QUES Q ON SQ.QUES_ID=Q.QUES_ID
JOIN CARS_118A_SUBSECT SS
ON SS.SUBSECT_ID = Q.SUBSECT_ID
JOIN CARS_118A_SECT S
ON S.SECT_ID = SS.SECT_ID
WHERE H.ENTITY_ID IN ((select TRIM(j.name) AS ENTITY_ID
		from json_table(
		  replace(json_array(i_lead_agency_entity_ids), ',', '","'),
		  '$[*]' columns (name varchar(10) path '$')
		) j)) AND A.HDR_AMEND_ID IN ((select TRIM(j.name) AS HDR_AMEND_ID
	from json_table(
	  replace(json_array(i_amend_id), ',', '","'),
	  '$[*]' columns (name varchar(10) path '$')
	) j))
) AS G;

IF TRIM(i_sect_ids)!='' THEN	
	SELECT * FROM CARS_118A_REVIEW_COMMENT_REPORT_TMP
	WHERE SECT_ID IN ((select TRIM(j.name) AS SECT_ID
			from json_table(
			  replace(json_array(i_sect_ids), ',', '","'),
			  '$[*]' columns (name varchar(10) path '$')
			) j));
		
ELSE
    SELECT * FROM CARS_118A_REVIEW_COMMENT_REPORT_TMP;

END IF;

					  
UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_118A_REVIEW_COMMENT_REPORT');
		
END$$
DELIMITER ;