DELIMITER $$
CREATE OR REPLACE PROCEDURE CARS_801_AGGN_SP_AGE_GROUP_HOURS_SUBSIDY( IN i_aggn_ref_id INT)
BEGIN

DECLARE v_rec_cnt INTEGER DEFAULT 0 ;
DECLARE v_total_rows_deleted INTEGER DEFAULT 0; 
DECLARE v_total_rows_inserted INTEGER DEFAULT 0; 
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
			 
			UPDATE CARS_801_SP_LOG
				SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
			WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_801_SP_LOG WHERE SP_NAME='CARS_801_AGGN_SP_AGE_GROUP_HOURS_SUBSIDY' );
			COMMIT;
		END;	
		
	INSERT INTO CARS_801_SP_LOG ( SP_NAME, START_TS)
		VALUES( 'CARS_801_AGGN_SP_AGE_GROUP_HOURS_SUBSIDY', NOW());	
	
		
		
	SELECT COUNT(*) INTO v_rec_cnt FROM CARS_801_AGGN_AGE_GROUP_HOURS_SUBSIDY WHERE  AGGN_REF_ID = i_aggn_ref_id;
 
		DELETE FROM CARS_801_AGGN_AGE_GROUP_HOURS_SUBSIDY
		WHERE AGGN_REF_ID = i_aggn_ref_id;
        
		SET v_total_rows_deleted = ROW_COUNT();
		
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_INIT;
CREATE TEMPORARY TABLE CARS_TMP_AGE_GROUP_HS_INIT AS  
SELECT
    H.MODULE_HDR_ID, 
	H.ENTITY_NAME, 
	H.ENTITY_ID,
	F.POOLING_FACTOR,
	R.FISCAL_YEAR, 
	H.FAMILY_COUNT AS FAMILY_UNADJ_AVG_COUNT, 
	C.CHILD_COUNT,
	C.POP_SAM_CHILD_COUNT AS CHILD_UNADJ_COUNT,
	SR.POPULATION_SAMPLE_CODE
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_PERIOD P
ON H.PERIOD_ID = P.PERIOD_ID
AND 801_FLAG = 1
JOIN CARS_801_AGGN_REF R
ON CAST(SUBSTR(P.PERIOD_DESC, 5, 4) AS INTEGER) = R.FISCAL_YEAR
AND R.AGGN_REF_ID = i_aggn_ref_id
JOIN CARS_801_REC_COUNTS C
ON H.MODULE_HDR_ID = C.MODULE_HDR_ID
JOIN VW_CARS_801_POOLING_FACTOR F
ON SUBSTR(P.PERIOD_DESC, 2, 7) = F.PERIOD_DESC
AND H.ENTITY_ID = F.ENTITY_ID
JOIN CARS_801_STATE_REF SR
ON H.ENTITY_ID = SR.ENTITY_ID
AND SUBSTR(P.PERIOD_DESC, 5, 4) = SR.FISCAL_YEAR
;


DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_BASE;
CREATE TEMPORARY TABLE CARS_TMP_AGE_GROUP_HS_BASE AS  
SELECT
MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME, CHILD_ID,AGE_CALC, SUM(CHILD_CARE_HOURS) AS HOURS, SUM(MONTHLY_AMOUNT) AS SUBSIDY,
CASE WHEN AGE_CALC < 0 OR BIRTH_YYYYMM IS NULL OR REP_YYYYMM IS NULL 
OR MAX(CASE WHEN CHILD_CARE_HOURS IS NULL THEN 1 ELSE 0 END) = 1 OR MAX(CASE WHEN MONTHLY_AMOUNT IS NULL THEN 1 ELSE 0 END) = 1 OR MAX(INVALID_CARE_TYPE) = 1
THEN 'I' ELSE NULL END AS INVALID_IND
FROM

(
		SELECT H.MODULE_HDR_ID, H.ENTITY_ID, H.ENTITY_NAME, C.CHILD_ID, S.CHILD_CARE_HOURS, S.MONTHLY_AMOUNT, C.BIRTH_YYYYMM, F.REP_YYYYMM,
		((SUBSTRING(F.REP_YYYYMM, 1, 4) * 12) + SUBSTRING(F.REP_YYYYMM,5,2)) - ((SUBSTRING(C.BIRTH_YYYYMM, 1, 4) * 12) + SUBSTRING(C.BIRTH_YYYYMM,5,2)) AS AGE_CALC, 
		CASE WHEN S.CHILD_CARE_TYPE_CD IS NULL THEN 1 ELSE 0 END AS INVALID_CARE_TYPE
		FROM CARS_MODULE_PERIOD_HDR H
		JOIN CARS_PERIOD P
		ON H.PERIOD_ID = P.PERIOD_ID
		AND 801_FLAG = 1
		JOIN CARS_801_AGGN_REF R
		ON CAST(SUBSTR(P.PERIOD_DESC, 5, 4) AS INTEGER) = R.FISCAL_YEAR
		AND R.AGGN_REF_ID = i_aggn_ref_id
		JOIN CARS_801_REC_COUNTS RC
		ON H.MODULE_HDR_ID = RC.MODULE_HDR_ID
		JOIN CARS_801_FAMILY F
		ON H.MODULE_HDR_ID = F.MODULE_HDR_ID
		JOIN CARS_801_CHILD C
		ON H.MODULE_HDR_ID = C.MODULE_HDR_ID
		AND F.FAMILY_ID = C.FAMILY_ID
		JOIN CARS_801_SETTING S
		ON C.CHILD_ID = S.CHILD_ID
		AND H.MODULE_HDR_ID = S.MODULE_HDR_ID
) A
GROUP BY MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME, CHILD_ID, AGE_CALC
;

CREATE INDEX IX1 ON CARS_TMP_AGE_GROUP_HS_BASE (INVALID_IND);

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_UNADJ_DATA;
CREATE TEMPORARY TABLE CARS_TMP_AGE_GROUP_HS_UNADJ_DATA AS  
SELECT
I.MODULE_HDR_ID, I.ENTITY_ID, I.ENTITY_NAME, 
CASE WHEN A.INVALID_CHILD_UNADJ_COUNT IS NULL THEN 0
	 WHEN POPULATION_SAMPLE_CODE = 'S' THEN INVALID_CHILD_UNADJ_COUNT / CHILD_COUNT * CHILD_UNADJ_COUNT 
	 ELSE INVALID_CHILD_UNADJ_COUNT END AS INVALID_CHILD_UNADJ_COUNT,
CHILD_UNADJ_COUNT, POOLING_FACTOR

FROM CARS_TMP_AGE_GROUP_HS_INIT I
LEFT OUTER JOIN 
(
SELECT
MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME, COUNT(DISTINCT CHILD_ID) AS INVALID_CHILD_UNADJ_COUNT
FROM CARS_TMP_AGE_GROUP_HS_BASE
WHERE INVALID_IND = 'I'
GROUP BY MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME
) A
ON I.MODULE_HDR_ID = A.MODULE_HDR_ID

;

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_INVALID;
CREATE TEMPORARY TABLE CARS_TMP_AGE_GROUP_HS_INVALID AS  
SELECT
ENTITY_ID, ENTITY_NAME, 
SUM(CHILD_UNADJ_COUNT) AS CHILD_UNADJ_COUNT,
ROUND(AVG(INVALID_CHILD_UNADJ_COUNT),0) AS INVALID_CHILD_UNADJ_COUNT,
CASE WHEN POOLING_FACTOR IS NULL THEN NULL ELSE ROUND(AVG(INVALID_CHILD_UNADJ_COUNT) * POOLING_FACTOR * .01, 0) END AS INVALID_CHILD_ADJ_COUNT, 
ROUND(SUM(INVALID_CHILD_UNADJ_COUNT) / SUM(CHILD_UNADJ_COUNT) * 100, 2) AS INVALID_PCT
FROM CARS_TMP_AGE_GROUP_HS_UNADJ_DATA
GROUP BY ENTITY_ID, ENTITY_NAME
;

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_INVALID_NATIONAL;
CREATE TEMPORARY TABLE CARS_TMP_AGE_GROUP_HS_INVALID_NATIONAL AS  
SELECT
0 AS ENTITY_ID, 'National' AS ENTITY_NAME,
SUM(INVALID_CHILD_UNADJ_COUNT) AS INVALID_CHILD_UNADJ_COUNT,
SUM(INVALID_CHILD_ADJ_COUNT) AS INVALID_CHILD_ADJ_COUNT, 
ROUND(SUM(INVALID_CHILD_UNADJ_COUNT) / SUM(CHILD_UNADJ_COUNT) * 100, 2) AS INVALID_PCT
FROM CARS_TMP_AGE_GROUP_HS_INVALID
;
		

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_DATA;
CREATE TEMPORARY TABLE CARS_TMP_AGE_GROUP_HS_DATA AS  
SELECT
ENTITY_ID, ENTITY_NAME, 
AGE_0_TO_1, HOURS_0_TO_1, SUBSIDY_0_TO_1,
AGE_1_TO_2, HOURS_1_TO_2, SUBSIDY_1_TO_2,
AGE_2_TO_3, HOURS_2_TO_3, SUBSIDY_2_TO_3, 
AGE_3_TO_4, HOURS_3_TO_4, SUBSIDY_3_TO_4,
AGE_4_TO_5, HOURS_4_TO_5, SUBSIDY_4_TO_5,
AGE_5_TO_6, HOURS_5_TO_6, SUBSIDY_5_TO_6,
AGE_6_TO_13, HOURS_6_TO_13, SUBSIDY_6_TO_13, 
AGE_GT_13, HOURS_GT_13, SUBSIDY_GT_13,
ALL_AGES, HOURS_ALL_AGES, SUBSIDY_ALL_AGES,


ROUND(HOURS_0_TO_1 / AGE_0_TO_1,0) AS HOURS_AGE_0_TO_1, 
ROUND(HOURS_1_TO_2 / AGE_1_TO_2,0) AS HOURS_AGE_1_TO_2, 
ROUND(HOURS_2_TO_3 / AGE_2_TO_3,0) AS HOURS_AGE_2_TO_3, 
ROUND(HOURS_3_TO_4 / AGE_3_TO_4,0) AS HOURS_AGE_3_TO_4, 
ROUND(HOURS_4_TO_5 / AGE_4_TO_5,0) AS HOURS_AGE_4_TO_5, 
ROUND(HOURS_5_TO_6 / AGE_5_TO_6,0) AS HOURS_AGE_5_TO_6, 
ROUND(HOURS_6_TO_13 / AGE_6_TO_13,0) AS HOURS_AGE_6_TO_13, 
ROUND(HOURS_GT_13 / AGE_GT_13,0) AS HOURS_AGE_GT_13,
ROUND(HOURS_ALL_AGES / ALL_AGES,0) AS HOURS_AGE_ALL_AGES,


ROUND(SUBSIDY_0_TO_1 / AGE_0_TO_1,0) AS SUBSIDY_AGE_0_TO_1, 
ROUND(SUBSIDY_1_TO_2 / AGE_1_TO_2,0) AS SUBSIDY_AGE_1_TO_2, 
ROUND(SUBSIDY_2_TO_3 / AGE_2_TO_3,0) AS SUBSIDY_AGE_2_TO_3, 
ROUND(SUBSIDY_3_TO_4 / AGE_3_TO_4,0) AS SUBSIDY_AGE_3_TO_4, 
ROUND(SUBSIDY_4_TO_5 / AGE_4_TO_5,0) AS SUBSIDY_AGE_4_TO_5, 
ROUND(SUBSIDY_5_TO_6 / AGE_5_TO_6,0) AS SUBSIDY_AGE_5_TO_6, 
ROUND(SUBSIDY_6_TO_13 / AGE_6_TO_13,0) AS SUBSIDY_AGE_6_TO_13, 
ROUND(SUBSIDY_GT_13 / AGE_GT_13,0) AS SUBSIDY_AGE_GT_13,
ROUND(SUBSIDY_ALL_AGES / ALL_AGES,0) AS SUBSIDY_AGE_ALL_AGES


FROM

(
	SELECT
	ENTITY_ID, ENTITY_NAME, 
	SUM(CASE WHEN INVALID_IND = 'I' THEN 1 ELSE 0 END) AS INVALID_CNT,
	SUM(CASE WHEN AGE_CALC BETWEEN 0 AND 11 THEN 1 ELSE 0 END) AS AGE_0_TO_1,
	SUM(CASE WHEN AGE_CALC BETWEEN 0 AND 11 THEN HOURS ELSE 0 END) AS HOURS_0_TO_1,
	SUM(CASE WHEN AGE_CALC BETWEEN 0 AND 11 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_0_TO_1,

	SUM(CASE WHEN AGE_CALC BETWEEN 12 AND 23 THEN 1 ELSE 0 END) AS AGE_1_TO_2,
	SUM(CASE WHEN AGE_CALC BETWEEN 12 AND 23 THEN HOURS ELSE 0 END) AS HOURS_1_TO_2,
	SUM(CASE WHEN AGE_CALC BETWEEN 12 AND 23 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_1_TO_2,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 24 AND 35 THEN 1 ELSE 0 END) AS AGE_2_TO_3,
	SUM(CASE WHEN AGE_CALC BETWEEN 24 AND 35 THEN HOURS ELSE 0 END) AS HOURS_2_TO_3,
	SUM(CASE WHEN AGE_CALC BETWEEN 24 AND 35 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_2_TO_3,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 36 AND 47 THEN 1 ELSE 0 END) AS AGE_3_TO_4,
	SUM(CASE WHEN AGE_CALC BETWEEN 36 AND 47 THEN HOURS ELSE 0 END) AS HOURS_3_TO_4,
	SUM(CASE WHEN AGE_CALC BETWEEN 36 AND 47 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_3_TO_4,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 48 AND 59 THEN 1 ELSE 0 END) AS AGE_4_TO_5,
	SUM(CASE WHEN AGE_CALC BETWEEN 48 AND 59 THEN HOURS ELSE 0 END) AS HOURS_4_TO_5,
	SUM(CASE WHEN AGE_CALC BETWEEN 48 AND 59 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_4_TO_5,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 60 AND 71 THEN 1 ELSE 0 END) AS AGE_5_TO_6,
	SUM(CASE WHEN AGE_CALC BETWEEN 60 AND 71 THEN HOURS ELSE 0 END) AS HOURS_5_TO_6,
	SUM(CASE WHEN AGE_CALC BETWEEN 60 AND 71 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_5_TO_6,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 72 AND 155 THEN 1 ELSE 0 END) AS AGE_6_TO_13,
	SUM(CASE WHEN AGE_CALC BETWEEN 72 AND 155 THEN HOURS ELSE 0 END) AS HOURS_6_TO_13,
	SUM(CASE WHEN AGE_CALC BETWEEN 72 AND 155 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_6_TO_13,
	
	SUM(CASE WHEN AGE_CALC >= 156 THEN 1 ELSE 0 END) AS AGE_GT_13,
	SUM(CASE WHEN AGE_CALC >= 156 THEN HOURS ELSE 0 END) AS HOURS_GT_13,
	SUM(CASE WHEN AGE_CALC >= 156 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_GT_13,
	
	SUM(1) AS ALL_AGES,
	SUM(HOURS) AS HOURS_ALL_AGES,
	SUM(SUBSIDY) AS SUBSIDY_ALL_AGES
	
	FROM CARS_TMP_AGE_GROUP_HS_BASE
	WHERE INVALID_IND IS NULL
	GROUP BY ENTITY_ID, ENTITY_NAME
) A
;

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_NATDATA;
CREATE TEMPORARY TABLE CARS_TMP_AGE_GROUP_HS_NATDATA AS  
SELECT
ENTITY_ID, ENTITY_NAME, 
AGE_0_TO_1, HOURS_0_TO_1, SUBSIDY_0_TO_1,
AGE_1_TO_2, HOURS_1_TO_2, SUBSIDY_1_TO_2,
AGE_2_TO_3, HOURS_2_TO_3, SUBSIDY_2_TO_3, 
AGE_3_TO_4, HOURS_3_TO_4, SUBSIDY_3_TO_4,
AGE_4_TO_5, HOURS_4_TO_5, SUBSIDY_4_TO_5,
AGE_5_TO_6, HOURS_5_TO_6, SUBSIDY_5_TO_6,
AGE_6_TO_13, HOURS_6_TO_13, SUBSIDY_6_TO_13, 
AGE_GT_13, HOURS_GT_13, SUBSIDY_GT_13,
ALL_AGES, HOURS_ALL_AGES, SUBSIDY_ALL_AGES,

ROUND(HOURS_0_TO_1 / AGE_0_TO_1,0) AS HOURS_AGE_0_TO_1, 
ROUND(HOURS_1_TO_2 / AGE_1_TO_2,0) AS HOURS_AGE_1_TO_2, 
ROUND(HOURS_2_TO_3 / AGE_2_TO_3,0) AS HOURS_AGE_2_TO_3, 
ROUND(HOURS_3_TO_4 / AGE_3_TO_4,0) AS HOURS_AGE_3_TO_4, 
ROUND(HOURS_4_TO_5 / AGE_4_TO_5,0) AS HOURS_AGE_4_TO_5, 
ROUND(HOURS_5_TO_6 / AGE_5_TO_6,0) AS HOURS_AGE_5_TO_6, 
ROUND(HOURS_6_TO_13 / AGE_6_TO_13,0) AS HOURS_AGE_6_TO_13, 
ROUND(HOURS_GT_13 / AGE_GT_13,0) AS HOURS_AGE_GT_13,
ROUND(HOURS_ALL_AGES / ALL_AGES,0) AS HOURS_AGE_ALL_AGES,

ROUND(SUBSIDY_0_TO_1 / AGE_0_TO_1,0) AS SUBSIDY_AGE_0_TO_1, 
ROUND(SUBSIDY_1_TO_2 / AGE_1_TO_2,0) AS SUBSIDY_AGE_1_TO_2, 
ROUND(SUBSIDY_2_TO_3 / AGE_2_TO_3,0) AS SUBSIDY_AGE_2_TO_3, 
ROUND(SUBSIDY_3_TO_4 / AGE_3_TO_4,0) AS SUBSIDY_AGE_3_TO_4, 
ROUND(SUBSIDY_4_TO_5 / AGE_4_TO_5,0) AS SUBSIDY_AGE_4_TO_5, 
ROUND(SUBSIDY_5_TO_6 / AGE_5_TO_6,0) AS SUBSIDY_AGE_5_TO_6, 
ROUND(SUBSIDY_6_TO_13 / AGE_6_TO_13,0) AS SUBSIDY_AGE_6_TO_13, 
ROUND(SUBSIDY_GT_13 / AGE_GT_13,0) AS SUBSIDY_AGE_GT_13,
ROUND(SUBSIDY_ALL_AGES / ALL_AGES,0) AS SUBSIDY_AGE_ALL_AGES

FROM

(
	SELECT
	0 AS ENTITY_ID, 'National' AS ENTITY_NAME, 
	SUM(CASE WHEN INVALID_IND = 'I' THEN 1 ELSE 0 END) AS INVALID_CNT,
	SUM(CASE WHEN AGE_CALC BETWEEN 0 AND 11 THEN 1 ELSE 0 END) AS AGE_0_TO_1,
	SUM(CASE WHEN AGE_CALC BETWEEN 0 AND 11 THEN HOURS ELSE 0 END) AS HOURS_0_TO_1,
	SUM(CASE WHEN AGE_CALC BETWEEN 0 AND 11 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_0_TO_1,

	SUM(CASE WHEN AGE_CALC BETWEEN 12 AND 23 THEN 1 ELSE 0 END) AS AGE_1_TO_2,
	SUM(CASE WHEN AGE_CALC BETWEEN 12 AND 23 THEN HOURS ELSE 0 END) AS HOURS_1_TO_2,
	SUM(CASE WHEN AGE_CALC BETWEEN 12 AND 23 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_1_TO_2,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 24 AND 35 THEN 1 ELSE 0 END) AS AGE_2_TO_3,
	SUM(CASE WHEN AGE_CALC BETWEEN 24 AND 35 THEN HOURS ELSE 0 END) AS HOURS_2_TO_3,
	SUM(CASE WHEN AGE_CALC BETWEEN 24 AND 35 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_2_TO_3,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 36 AND 47 THEN 1 ELSE 0 END) AS AGE_3_TO_4,
	SUM(CASE WHEN AGE_CALC BETWEEN 36 AND 47 THEN HOURS ELSE 0 END) AS HOURS_3_TO_4,
	SUM(CASE WHEN AGE_CALC BETWEEN 36 AND 47 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_3_TO_4,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 48 AND 59 THEN 1 ELSE 0 END) AS AGE_4_TO_5,
	SUM(CASE WHEN AGE_CALC BETWEEN 48 AND 59 THEN HOURS ELSE 0 END) AS HOURS_4_TO_5,
	SUM(CASE WHEN AGE_CALC BETWEEN 48 AND 59 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_4_TO_5,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 60 AND 71 THEN 1 ELSE 0 END) AS AGE_5_TO_6,
	SUM(CASE WHEN AGE_CALC BETWEEN 60 AND 71 THEN HOURS ELSE 0 END) AS HOURS_5_TO_6,
	SUM(CASE WHEN AGE_CALC BETWEEN 60 AND 71 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_5_TO_6,
	
	SUM(CASE WHEN AGE_CALC BETWEEN 72 AND 155 THEN 1 ELSE 0 END) AS AGE_6_TO_13,
	SUM(CASE WHEN AGE_CALC BETWEEN 72 AND 155 THEN HOURS ELSE 0 END) AS HOURS_6_TO_13,
	SUM(CASE WHEN AGE_CALC BETWEEN 72 AND 155 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_6_TO_13,
	
	SUM(CASE WHEN AGE_CALC >= 156 THEN 1 ELSE 0 END) AS AGE_GT_13,
	SUM(CASE WHEN AGE_CALC >= 156 THEN HOURS ELSE 0 END) AS HOURS_GT_13,
	SUM(CASE WHEN AGE_CALC >= 156 THEN SUBSIDY ELSE 0 END) AS SUBSIDY_GT_13,
	
	SUM(1) AS ALL_AGES,
	SUM(HOURS) AS HOURS_ALL_AGES,
	SUM(SUBSIDY) AS SUBSIDY_ALL_AGES
	
	
	FROM CARS_TMP_AGE_GROUP_HS_BASE
	WHERE INVALID_IND IS NULL
) A
;
		

INSERT INTO CARS_801_AGGN_AGE_GROUP_HOURS_SUBSIDY 
(
AGGN_REF_ID, 
ENTITY_ID, 
ENTITY_NAME, 
AGE_0_TO_1_AVERAGE_HOURS, 
AGE_0_TO_1_AVERAGE_SUBSIDY, 
AGE_1_TO_2_AVERAGE_HOURS, 
AGE_1_TO_2_AVERAGE_SUBSIDY, 
AGE_2_TO_3_AVERAGE_HOURS, 
AGE_2_TO_3_AVERAGE_SUBSIDY, 
AGE_3_TO_4_AVERAGE_HOURS, 
AGE_3_TO_4_AVERAGE_SUBSIDY, 
AGE_4_TO_5_AVERAGE_HOURS, 
AGE_4_TO_5_AVERAGE_SUBSIDY, 
AGE_5_TO_6_AVERAGE_HOURS, 
AGE_5_TO_6_AVERAGE_SUBSIDY, 
AGE_6_TO_13_AVERAGE_HOURS, 
AGE_6_TO_13_AVERAGE_SUBSIDY, 
AGE_GT_13_AVERAGE_HOURS, 
AGE_GT_13_AVERAGE_SUBSIDY, 
ALL_AGES_AVERAGE_HOURS,
ALL_AGES_AVERAGE_SUBSIDY,
INVALID_UNADJ_CHILD_COUNT, 
INVALID_ADJ_CHILD_COUNT, 
INVALID_CHILD_PERCENT
) 
SELECT
i_aggn_ref_id,
A.ENTITY_ID, 
A.ENTITY_NAME, 
HOURS_AGE_0_TO_1,
SUBSIDY_AGE_0_TO_1,
HOURS_AGE_1_TO_2,
SUBSIDY_AGE_1_TO_2,
HOURS_AGE_2_TO_3,
SUBSIDY_AGE_2_TO_3,
HOURS_AGE_3_TO_4,
SUBSIDY_AGE_3_TO_4,
HOURS_AGE_4_TO_5,
SUBSIDY_AGE_4_TO_5,
HOURS_AGE_5_TO_6,
SUBSIDY_AGE_5_TO_6,
HOURS_AGE_6_TO_13,
SUBSIDY_AGE_6_TO_13,
HOURS_AGE_GT_13,
SUBSIDY_AGE_GT_13,
HOURS_AGE_ALL_AGES,
SUBSIDY_AGE_ALL_AGES,
CASE WHEN INVALID_CHILD_UNADJ_COUNT IS NULL THEN 0 ELSE INVALID_CHILD_UNADJ_COUNT END,
CASE WHEN INVALID_CHILD_ADJ_COUNT IS NULL THEN 0 ELSE INVALID_CHILD_ADJ_COUNT END,
CASE WHEN INVALID_PCT IS NULL THEN 0 ELSE INVALID_PCT END

FROM CARS_TMP_AGE_GROUP_HS_DATA A
LEFT OUTER JOIN CARS_TMP_AGE_GROUP_HS_INVALID I
ON A.ENTITY_ID = I.ENTITY_ID

UNION ALL 

SELECT
i_aggn_ref_id,
A.ENTITY_ID, 
A.ENTITY_NAME, 
HOURS_AGE_0_TO_1,
SUBSIDY_AGE_0_TO_1,
HOURS_AGE_1_TO_2,
SUBSIDY_AGE_1_TO_2,
HOURS_AGE_2_TO_3,
SUBSIDY_AGE_2_TO_3,
HOURS_AGE_3_TO_4,
SUBSIDY_AGE_3_TO_4,
HOURS_AGE_4_TO_5,
SUBSIDY_AGE_4_TO_5,
HOURS_AGE_5_TO_6,
SUBSIDY_AGE_5_TO_6,
HOURS_AGE_6_TO_13,
SUBSIDY_AGE_6_TO_13,
HOURS_AGE_GT_13,
SUBSIDY_AGE_GT_13,
HOURS_AGE_ALL_AGES,
SUBSIDY_AGE_ALL_AGES,
CASE WHEN INVALID_CHILD_UNADJ_COUNT IS NULL THEN 0 ELSE INVALID_CHILD_UNADJ_COUNT END,
CASE WHEN INVALID_CHILD_ADJ_COUNT IS NULL THEN 0 ELSE INVALID_CHILD_ADJ_COUNT END,
CASE WHEN INVALID_PCT IS NULL THEN 0 ELSE INVALID_PCT END

FROM CARS_TMP_AGE_GROUP_HS_NATDATA A
LEFT OUTER JOIN CARS_TMP_AGE_GROUP_HS_INVALID_NATIONAL I
ON A.ENTITY_ID = I.ENTITY_ID

UNION ALL
        
SELECT 
i_aggn_ref_id, 
E.ENTITY_ID,
E.ENTITY_NAME,  
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM CARS_ENTITY E
LEFT OUTER JOIN CARS_TMP_AGE_GROUP_HS_DATA C
ON E.ENTITY_ID = C.ENTITY_ID
WHERE E.ENTITY_TYPE_CD = 'STATE-TER'
AND C.ENTITY_ID IS NULL 

;

		SET v_total_rows_inserted = ROW_COUNT();

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_INIT;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_BASE;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_INVALID;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_AGE_GROUP_HS_DATA;

UPDATE CARS_801_SP_LOG
SET SP_STATUS_TEXT= CONCAT('Success. Rows inserted: ',v_total_rows_inserted, ' Rows Deleted :', v_total_rows_deleted), END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME ='CARS_801_AGGN_SP_AGE_GROUP_HOURS_SUBSIDY');
COMMIT;		
	
END$$
DELIMITER ;