DELIMITER $$
CREATE OR REPLACE PROCEDURE CARS_801_AGGN_SP_RACE( IN i_aggn_ref_id INT)
BEGIN

DECLARE v_rec_cnt INTEGER DEFAULT 0 ;
DECLARE v_total_rows_deleted INTEGER DEFAULT 0; 
DECLARE v_total_rows_inserted INTEGER DEFAULT 0; 
		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
			 
			UPDATE CARS_801_SP_LOG
				SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
			WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_801_SP_LOG WHERE SP_NAME='CARS_801_AGGN_SP_RACE' );
			COMMIT;
		END;	
		
	INSERT INTO CARS_801_SP_LOG ( SP_NAME, START_TS)
		VALUES( 'CARS_801_AGGN_SP_RACE', NOW());	
		
		
	SELECT COUNT(*) INTO v_rec_cnt FROM CARS_801_AGGN_RACE WHERE  AGGN_REF_ID = i_aggn_ref_id;
 
		DELETE FROM CARS_801_AGGN_RACE
		WHERE AGGN_REF_ID = i_aggn_ref_id;
        
		SET v_total_rows_deleted = ROW_COUNT();
		
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_INIT;
CREATE TEMPORARY TABLE CARS_TMP_RACE_INIT AS  
SELECT
    H.MODULE_HDR_ID, 
	H.ENTITY_NAME, 
	H.ENTITY_ID,
	F.POOLING_FACTOR,
	R.FISCAL_YEAR, 
	H.FAMILY_COUNT AS FAMILY_UNADJ_AVG_COUNT, 
	C.CHILD_COUNT,
	C.POP_SAM_CHILD_COUNT AS CHILD_UNADJ_COUNT,
	SR.POPULATION_SAMPLE_CODE
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_PERIOD P
ON H.PERIOD_ID = P.PERIOD_ID
AND 801_FLAG = 1
JOIN CARS_801_AGGN_REF R
ON CAST(SUBSTR(P.PERIOD_DESC, 5, 4) AS INTEGER) = R.FISCAL_YEAR
AND R.AGGN_REF_ID = i_aggn_ref_id
JOIN CARS_801_REC_COUNTS C
ON H.MODULE_HDR_ID = C.MODULE_HDR_ID
JOIN VW_CARS_801_POOLING_FACTOR F
ON SUBSTR(P.PERIOD_DESC, 2, 7) = F.PERIOD_DESC
AND H.ENTITY_ID = F.ENTITY_ID
JOIN CARS_801_STATE_REF SR
ON H.ENTITY_ID = SR.ENTITY_ID
AND SUBSTR(P.PERIOD_DESC, 5, 4) = SR.FISCAL_YEAR
;


DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_UNADJ_DATA;
CREATE TEMPORARY TABLE CARS_TMP_RACE_UNADJ_DATA AS  
SELECT
B.MODULE_HDR_ID, B.ENTITY_ID, B.ENTITY_NAME, 
CHILD_COUNT, CHILD_UNADJ_COUNT, POOLING_FACTOR,
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (MULTI_RACE / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE MULTI_RACE END AS MULTI_RACE, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (WHITE / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE WHITE END AS WHITE, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (NHPI / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE NHPI END AS NHPI, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (AA / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE AA END AS AA, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (ASIAN / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE ASIAN END AS ASIAN, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN (AIAN / CHILD_COUNT) * CHILD_UNADJ_COUNT ELSE AIAN END AS AIAN, 
CASE WHEN POPULATION_SAMPLE_CODE = 'S' THEN ((CHILD_COUNT - MULTI_RACE - WHITE - NHPI - AA - ASIAN - AIAN) / CHILD_COUNT) * CHILD_UNADJ_COUNT 
ELSE CHILD_COUNT - MULTI_RACE - WHITE - NHPI - AA - ASIAN - AIAN END AS INVALID

FROM
(
	SELECT
	MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME,
	SUM(CASE WHEN MULTI_RACE = 1 THEN 1 ELSE 0 END) AS MULTI_RACE,
	SUM(CASE WHEN WHITE_CD = 1 AND MULTI_RACE <> 1 THEN 1 ELSE 0 END) AS WHITE,
	SUM(CASE WHEN NHPI_CD = 1 AND MULTI_RACE <> 1 THEN 1 ELSE 0 END) AS NHPI,
	SUM(CASE WHEN AA_CD = 1 AND MULTI_RACE <> 1 THEN 1 ELSE 0 END) AS AA,
	SUM(CASE WHEN ASIAN_CD = 1 AND MULTI_RACE <> 1 THEN 1 ELSE 0 END) AS ASIAN,
	SUM(CASE WHEN AIAN_CD = 1 AND MULTI_RACE <> 1 THEN 1 ELSE 0 END) AS AIAN

	FROM 
	(
		SELECT H.MODULE_HDR_ID, H.ENTITY_ID, H.ENTITY_NAME, CHILD_ID, 
		AIAN_CD, ASIAN_CD, AA_CD, NHPI_CD, WHITE_CD, HISPANIC_CD, 
		CASE WHEN (COALESCE(AIAN_CD, 0) + COALESCE(ASIAN_CD, 0) + COALESCE(AA_CD, 0) + COALESCE(NHPI_CD, 0) 
		+ COALESCE(WHITE_CD, 0)) BETWEEN 2 AND 5 THEN 1 ELSE 0 END AS MULTI_RACE
		FROM CARS_MODULE_PERIOD_HDR H
		JOIN CARS_PERIOD P
		ON H.PERIOD_ID = P.PERIOD_ID
		AND 801_FLAG = 1
		JOIN CARS_801_AGGN_REF R
		ON CAST(SUBSTR(P.PERIOD_DESC, 5, 4) AS INTEGER) = R.FISCAL_YEAR
		AND R.AGGN_REF_ID = i_aggn_ref_id
		JOIN CARS_801_REC_COUNTS RC
		ON H.MODULE_HDR_ID = RC.MODULE_HDR_ID
		JOIN CARS_801_CHILD C
		ON H.MODULE_HDR_ID = C.MODULE_HDR_ID
	) C
	GROUP BY MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME
) B
JOIN CARS_TMP_RACE_INIT I
ON B.MODULE_HDR_ID = I.MODULE_HDR_ID
;



DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_ADJ_DATA;
CREATE TEMPORARY TABLE CARS_TMP_RACE_ADJ_DATA AS  

SELECT
MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME,
MULTI_RACE_UNADJ_CNT, MULTI_RACE_ADJ_CNT,
WHITE_RACE_UNADJ_CNT, WHITE_RACE_ADJ_CNT,
ASIAN_RACE_UNADJ_CNT, ASIAN_RACE_ADJ_CNT,
AA_RACE_UNADJ_CNT, AA_RACE_ADJ_CNT,
AIAN_RACE_UNADJ_CNT, AIAN_RACE_ADJ_CNT,
NHPI_RACE_UNADJ_CNT, NHPI_RACE_ADJ_CNT,
INVALID_RACE_UNADJ_CNT, INVALID_RACE_ADJ_CNT,
MULTI_RACE_UNADJ_CNT + WHITE_RACE_UNADJ_CNT + ASIAN_RACE_UNADJ_CNT + AA_RACE_UNADJ_CNT + AIAN_RACE_UNADJ_CNT + NHPI_RACE_UNADJ_CNT + INVALID_RACE_UNADJ_CNT AS TOT_UNADJ_CNT,
MULTI_RACE_ADJ_CNT + WHITE_RACE_ADJ_CNT + ASIAN_RACE_ADJ_CNT + AA_RACE_ADJ_CNT + AIAN_RACE_ADJ_CNT + NHPI_RACE_ADJ_CNT + INVALID_RACE_ADJ_CNT AS TOT_ADJ_CNT


FROM
(
	SELECT
	MODULE_HDR_ID, ENTITY_ID, ENTITY_NAME,
	MULTI_RACE AS MULTI_RACE_UNADJ_CNT,
	WHITE AS WHITE_RACE_UNADJ_CNT,
	ASIAN AS ASIAN_RACE_UNADJ_CNT,
	AA AS AA_RACE_UNADJ_CNT,
	AIAN AS AIAN_RACE_UNADJ_CNT,
	NHPI AS NHPI_RACE_UNADJ_CNT,
	INVALID AS INVALID_RACE_UNADJ_CNT,


	MULTI_RACE * POOLING_FACTOR * .01 AS MULTI_RACE_ADJ_CNT,
	WHITE * POOLING_FACTOR * .01 AS WHITE_RACE_ADJ_CNT,
	ASIAN * POOLING_FACTOR * .01 AS ASIAN_RACE_ADJ_CNT,
	AA * POOLING_FACTOR * .01 AS AA_RACE_ADJ_CNT,
	AIAN * POOLING_FACTOR * .01 AS AIAN_RACE_ADJ_CNT,
	NHPI * POOLING_FACTOR * .01 AS NHPI_RACE_ADJ_CNT,
	INVALID * POOLING_FACTOR * .01 AS INVALID_RACE_ADJ_CNT

	FROM CARS_TMP_RACE_UNADJ_DATA
) A
;

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_AVG;
CREATE TEMPORARY TABLE CARS_TMP_RACE_AVG AS  
SELECT
ENTITY_ID, ENTITY_NAME,
ROUND(AVG(MULTI_RACE_UNADJ_CNT), 0) AS MULTI_RACE_UNADJ_CNT, ROUND(AVG(MULTI_RACE_ADJ_CNT), 0) AS MULTI_RACE_ADJ_CNT,
ROUND(AVG(WHITE_RACE_UNADJ_CNT), 0) AS WHITE_RACE_UNADJ_CNT, ROUND(AVG(WHITE_RACE_ADJ_CNT), 0) AS WHITE_RACE_ADJ_CNT,
ROUND(AVG(ASIAN_RACE_UNADJ_CNT), 0) AS ASIAN_RACE_UNADJ_CNT, ROUND(AVG(ASIAN_RACE_ADJ_CNT), 0) AS ASIAN_RACE_ADJ_CNT,
ROUND(AVG(AA_RACE_UNADJ_CNT), 0) AS AA_RACE_UNADJ_CNT, ROUND(AVG(AA_RACE_ADJ_CNT), 0) AS AA_RACE_ADJ_CNT,
ROUND(AVG(AIAN_RACE_UNADJ_CNT), 0) AS AIAN_RACE_UNADJ_CNT, ROUND(AVG(AIAN_RACE_ADJ_CNT), 0) AS AIAN_RACE_ADJ_CNT,
ROUND(AVG(NHPI_RACE_UNADJ_CNT), 0) AS NHPI_RACE_UNADJ_CNT, ROUND(AVG(NHPI_RACE_ADJ_CNT), 0) AS NHPI_RACE_ADJ_CNT,
ROUND(AVG(INVALID_RACE_UNADJ_CNT), 0) AS INVALID_RACE_UNADJ_CNT, ROUND(AVG(INVALID_RACE_ADJ_CNT), 0) AS INVALID_RACE_ADJ_CNT,

ROUND(AVG(MULTI_RACE_UNADJ_CNT), 0) + ROUND(AVG(WHITE_RACE_UNADJ_CNT), 0) + ROUND(AVG(ASIAN_RACE_UNADJ_CNT), 0) + ROUND(AVG(AA_RACE_UNADJ_CNT), 0) 
+ ROUND(AVG(AIAN_RACE_UNADJ_CNT), 0) + ROUND(AVG(NHPI_RACE_UNADJ_CNT), 0) + ROUND(AVG(INVALID_RACE_UNADJ_CNT), 0) AS TOT_UNADJ_CNT,

ROUND(AVG(MULTI_RACE_ADJ_CNT), 0) + ROUND(AVG(WHITE_RACE_ADJ_CNT), 0) + ROUND(AVG(ASIAN_RACE_ADJ_CNT), 0) + ROUND(AVG(AA_RACE_ADJ_CNT), 0) 
+ ROUND(AVG(AIAN_RACE_ADJ_CNT), 0) + ROUND(AVG(NHPI_RACE_ADJ_CNT), 0) + ROUND(AVG(INVALID_RACE_ADJ_CNT), 0) AS TOT_ADJ_CNT

FROM CARS_TMP_RACE_ADJ_DATA
GROUP BY ENTITY_ID, ENTITY_NAME;


DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_NATIONAL;
CREATE TEMPORARY TABLE CARS_TMP_RACE_NATIONAL AS  
SELECT
0 AS ENTITY_ID, 'National' AS ENTITY_NAME,
SUM(MULTI_RACE_UNADJ_CNT) AS MULTI_RACE_UNADJ_CNT, SUM(MULTI_RACE_ADJ_CNT) AS MULTI_RACE_ADJ_CNT,
SUM(WHITE_RACE_UNADJ_CNT) AS WHITE_RACE_UNADJ_CNT, SUM(WHITE_RACE_ADJ_CNT) AS WHITE_RACE_ADJ_CNT,
SUM(ASIAN_RACE_UNADJ_CNT) AS ASIAN_RACE_UNADJ_CNT, SUM(ASIAN_RACE_ADJ_CNT) AS ASIAN_RACE_ADJ_CNT,
SUM(AA_RACE_UNADJ_CNT) AS AA_RACE_UNADJ_CNT, SUM(AA_RACE_ADJ_CNT) AS AA_RACE_ADJ_CNT,
SUM(AIAN_RACE_UNADJ_CNT) AS AIAN_RACE_UNADJ_CNT, SUM(AIAN_RACE_ADJ_CNT) AS AIAN_RACE_ADJ_CNT,
SUM(NHPI_RACE_UNADJ_CNT) AS NHPI_RACE_UNADJ_CNT, SUM(NHPI_RACE_ADJ_CNT) AS NHPI_RACE_ADJ_CNT,
SUM(INVALID_RACE_UNADJ_CNT) AS INVALID_RACE_UNADJ_CNT, SUM(INVALID_RACE_ADJ_CNT) AS INVALID_RACE_ADJ_CNT,
SUM(TOT_UNADJ_CNT) AS TOT_UNADJ_CNT, SUM(TOT_ADJ_CNT) AS TOT_ADJ_CNT
FROM CARS_TMP_RACE_AVG;

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_PCT;
CREATE TEMPORARY TABLE CARS_TMP_RACE_PCT AS  
SELECT
ENTITY_ID, ENTITY_NAME,
ROUND((MULTI_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS MULTI_RACE_PCT,
ROUND((WHITE_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS WHITE_RACE_PCT,
ROUND((ASIAN_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS ASIAN_RACE_PCT,
ROUND((AA_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AA_RACE_PCT,
ROUND((AIAN_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AIAN_RACE_PCT,
ROUND((NHPI_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS NHPI_RACE_PCT,
ROUND((INVALID_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS INVALID_RACE_PCT,
CASE WHEN WHITE_RACE_ADJ_CNT IS NULL THEN NULL ELSE 100.00 END AS TOT_RACE_PCT /* IF POOLING FACTOR IS NULL */
FROM CARS_TMP_RACE_AVG

UNION ALL

SELECT
ENTITY_ID, ENTITY_NAME, 
ROUND((MULTI_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS MULTI_RACE_PCT,
ROUND((WHITE_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS WHITE_RACE_PCT,
ROUND((ASIAN_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS ASIAN_RACE_PCT,
ROUND((AA_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AA_RACE_PCT,
ROUND((AIAN_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS AIAN_RACE_PCT,
ROUND((NHPI_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS NHPI_RACE_PCT,
ROUND((INVALID_RACE_ADJ_CNT / TOT_ADJ_CNT) * 100, 2) AS INVALID_RACE_PCT,
100.00 AS TOTAL_RACE_PCT
FROM CARS_TMP_RACE_NATIONAL;

INSERT INTO CARS_801_AGGN_RACE
(
AGGN_REF_ID, 
ENTITY_ID, 
ENTITY_NAME, 
INVALID_RACE_CHILD_UNADJ_COUNT, 
INVALID_RACE_CHILD_ADJ_COUNT, 
INVALID_RACE_CHILD_PERCENT, 
AIAN_CHILD_UNADJ_COUNT, 
AIAN_CHILD_ADJ_COUNT, 
AIAN_CHILD_PERCENT, 
ASIAN_CHILD_UNADJ_COUNT, 
ASIAN_CHILD_ADJ_COUNT, 
ASIAN_CHILD_PERCENT, 
AA_CHILD_UNADJ_COUNT, 
AA_CHILD_ADJ_COUNT, 
AA_CHILD_PERCENT, 
NHPI_CHILD_UNADJ_COUNT, 
NHPI_CHILD_ADJ_COUNT, 
NHPI_CHILD_PERCENT, 
WHITE_CHILD_UNADJ_COUNT, 
WHITE_CHILD_ADJ_COUNT, 
WHITE_CHILD_PERCENT, 
MULTI_RACE_CHILD_UNADJ_COUNT, 
MULTI_RACE_CHILD_ADJ_COUNT, 
MULTI_RACE_CHILD_PERCENT, 
TOTAL_CHILD_UNADJ_COUNT,
TOTAL_CHILD_ADJ_COUNT,
TOTAL_CHILD_PERCENT
)
SELECT
i_aggn_ref_id,
A.ENTITY_ID, 
A.ENTITY_NAME, 
INVALID_RACE_UNADJ_CNT,
INVALID_RACE_ADJ_CNT,
INVALID_RACE_PCT,
AIAN_RACE_UNADJ_CNT,
AIAN_RACE_ADJ_CNT,
AIAN_RACE_PCT,
ASIAN_RACE_UNADJ_CNT,
ASIAN_RACE_ADJ_CNT,
ASIAN_RACE_PCT,
AA_RACE_UNADJ_CNT,
AA_RACE_ADJ_CNT,
AA_RACE_PCT,
NHPI_RACE_UNADJ_CNT,
NHPI_RACE_ADJ_CNT,
NHPI_RACE_PCT,
WHITE_RACE_UNADJ_CNT,
WHITE_RACE_ADJ_CNT,
WHITE_RACE_PCT,
MULTI_RACE_UNADJ_CNT,
MULTI_RACE_ADJ_CNT,
MULTI_RACE_PCT,
TOT_UNADJ_CNT, 
TOT_ADJ_CNT, 
TOT_RACE_PCT

FROM CARS_TMP_RACE_AVG A
JOIN CARS_TMP_RACE_PCT P
ON A.ENTITY_ID = P.ENTITY_ID

UNION ALL 

SELECT
i_aggn_ref_id,
A.ENTITY_ID, 
A.ENTITY_NAME, 
INVALID_RACE_UNADJ_CNT,
INVALID_RACE_ADJ_CNT,
INVALID_RACE_PCT,
AIAN_RACE_UNADJ_CNT,
AIAN_RACE_ADJ_CNT,
AIAN_RACE_PCT,
ASIAN_RACE_UNADJ_CNT,
ASIAN_RACE_ADJ_CNT,
ASIAN_RACE_PCT,
AA_RACE_UNADJ_CNT,
AA_RACE_ADJ_CNT,
AA_RACE_PCT,
NHPI_RACE_UNADJ_CNT,
NHPI_RACE_ADJ_CNT,
NHPI_RACE_PCT,
WHITE_RACE_UNADJ_CNT,
WHITE_RACE_ADJ_CNT,
WHITE_RACE_PCT,
MULTI_RACE_UNADJ_CNT,
MULTI_RACE_ADJ_CNT,
MULTI_RACE_PCT,
TOT_UNADJ_CNT, 
TOT_ADJ_CNT, 
TOT_RACE_PCT
FROM CARS_TMP_RACE_NATIONAL A
JOIN CARS_TMP_RACE_PCT P
ON A.ENTITY_ID = P.ENTITY_ID

UNION ALL
        
SELECT 
i_aggn_ref_id, 
E.ENTITY_ID,
E.ENTITY_NAME,  
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
FROM CARS_ENTITY E
LEFT OUTER JOIN CARS_TMP_RACE_AVG C
ON E.ENTITY_ID = C.ENTITY_ID
WHERE E.ENTITY_TYPE_CD = 'STATE-TER'
AND C.ENTITY_ID IS NULL 
;

		SET v_total_rows_inserted = ROW_COUNT();

DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_INIT;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_UNADJ_DATA;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_ADJ_DATA;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_AVG;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_NATIONAL;
DROP TEMPORARY TABLE IF EXISTS CARS_TMP_RACE_PCT;

UPDATE CARS_801_SP_LOG
SET SP_STATUS_TEXT= CONCAT('Success. Rows inserted: ',v_total_rows_inserted, ' Rows Deleted :', v_total_rows_deleted), END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_801_SP_LOG WHERE SP_NAME ='CARS_801_AGGN_SP_RACE');
COMMIT;		
	
END$$
DELIMITER ;