DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_218_COMMENT_REPORT`(
p_PERIOD_ID INT
,p_ENTITY_ID TEXT
,p_COMMENT_TYPE_CD VARCHAR(100)
,p_SECT_ID TEXT)

proc_label: BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_218_COMMENT_REPORT');		
	END;
	
	
	INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_218_COMMENT_REPORT', 'Started', NOW());	


BEGIN
DECLARE v_COMMENT_TYPE_CD VARCHAR(100);
DECLARE v_SECT_ID TEXT;
DECLARE v_SQL_1 TEXT;
DECLARE v_SQL_2 TEXT;
DECLARE v_WHERECOND TEXT;


IF p_SECT_ID IS NULL THEN SET v_SECT_ID=' ';
END IF;
IF p_SECT_ID IS NOT NULL THEN SET v_SECT_ID = CONCAT(' AND R.SECT_ID IN (',  p_SECT_ID ,') ');
END IF;

IF p_COMMENT_TYPE_CD IS NULL THEN SET v_COMMENT_TYPE_CD=' ';
END IF;
IF p_COMMENT_TYPE_CD IS NOT NULL THEN SET v_COMMENT_TYPE_CD = CONCAT(' AND R.COMMENT_TYPE_CD = (',  p_COMMENT_TYPE_CD ,') ');
END IF;

SET v_WHERECOND = CONCAT (v_SECT_ID, v_COMMENT_TYPE_CD);

SET v_SQL_2='
SELECT
  ''ROW_SEQ_NUM''
, ''HDR_AMEND_ID''
, ''PERIOD_ID''
, ''ENTITY_ID'' 
, ''ENTITY_NAME''
, ''STATE''
, ''REGION_ID''
, ''QUES_NAME''
, ''REGION_NAME''
, ''SECT_NAME''
, ''COMMENT_TYPE_CD''
, ''COMMENT_TEXT''
, ''GRANTEE_VISIBLE_FLAG'' 
, ''LAST_UPD_BY''
, ''LAST_UPD_TS''
, ''ROLE''
, ''SECT_ID''
,''SUBQUES_ID''
';

SET v_SQL_1=
'SELECT * FROM VW_CARS_218_COMMENT_REPORT R
WHERE R.PERIOD_ID=REPLACE_PERIOD_ID
AND R.ENTITY_ID IN (REPLACE_ENTITY_ID)
REPLACE_ME'
;

EXECUTE IMMEDIATE REPLACE(REPLACE(REPLACE(v_SQL_1,'REPLACE_ME',v_WHERECOND),'REPLACE_ENTITY_ID',p_ENTITY_ID),'REPLACE_PERIOD_ID',p_PERIOD_ID);
EXECUTE IMMEDIATE v_SQL_2;

END;
UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_218_COMMENT_REPORT');
		
	
END
$$ DELIMITER ;