DELIMITER $$
CREATE OR REPLACE PROCEDURE `CARS_218_CONTENT_REPORTS`(IN i_subques_list TEXT, IN i_subques_resp_list TEXT, IN i_amend_where_cond TEXT, IN period_id INTEGER)
proc_label: BEGIN

DECLARE v_iter INTEGER DEFAULT 0;
DECLARE v_createtable TEXT DEFAULT '';
DECLARE v_droptable TEXT DEFAULT '';
DECLARE v_whilecnt INTEGER DEFAULT 1;
DECLARE v_collist TEXT DEFAULT '';
DECLARE v_collist1 TEXT DEFAULT '';
DECLARE v_infinite INTEGER DEFAULT 0;
DECLARE v_comma CHAR(1) DEFAULT ',';
DECLARE v_sql TEXT DEFAULT '';
DECLARE v_union TEXT DEFAULT ' ';
DECLARE v_sqlhdr TEXT DEFAULT '';
DECLARE v_sqlans TEXT DEFAULT '';
DECLARE v_rand CHAR(7) DEFAULT '';
DECLARE v_dropsql TEXT DEFAULT '';
DECLARE v_crsql TEXT DEFAULT '';




	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, @errno = MYSQL_ERRNO, @text = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @text);
		
		UPDATE CARS_SP_LOG
			SET SP_STATUS_TEXT='Error',SP_LOG_MESSAGE_TEXT=@full_error,END_TS=NOW()
		WHERE SP_LOG_ID=(SELECT MAX(SP_LOG_ID)FROM CARS_SP_LOG WHERE SP_NAME='CARS_218_CONTENT_REPORTS_NEW');

			
		
	END;
	
	
	INSERT INTO CARS_SP_LOG (SP_NAME, SP_STATUS_TEXT, START_TS)
		VALUES('CARS_218_CONTENT_REPORTS_NEW', 'Started', NOW());	

SELECT SUBSTR(CAST(RAND() * 100000000 AS VARCHAR(50)), 1, 7) INTO v_rand FROM DUAL;

/*
SET v_dropsql = '';
SET v_dropsql = CONCAT('DROP TEMPORARY TABLE IF EXISTS CARS_TEMP_SUBQUES_RESP_LIST', v_rand);
EXECUTE IMMEDIATE (v_dropsql);
*/


DROP TEMPORARY TABLE IF EXISTS CARS_TEMP_SUBQUES_RESP_LIST;


SET v_sql = '';
SET v_sql = CONCAT('CREATE TEMPORARY TABLE CARS_TEMP_SUBQUES_RESP_LIST   
AS 
SELECT
DENSE_RANK() OVER(ORDER BY SUBQUES_ID, DISPLAY_ORDER, GROUP_COL) AS LIST_ORDER,
SUBQUES_ID, SUBQUES_RESP_ID, RESP_TYPE_CD, COL_HEADER, GROUP_COL
FROM
(
SELECT
SR.SUBQUES_ID, SR.RESP_SEQ_NUM, 
CASE WHEN P.SUBQUES_RESP_ID IS NOT NULL THEN SR1.SUBQUES_RESP_ID ELSE SR.SUBQUES_RESP_ID END AS SUBQUES_RESP_ID, 
CASE WHEN P.SUBQUES_RESP_ID IS NOT NULL THEN SR1.RESP_TYPE_CD ELSE SR.RESP_TYPE_CD END AS RESP_TYPE_CD,
SR.RESP_SHORT_LABEL_TEXT AS COL_HEADER, SR.RESP_SEQ_NUM AS DISPLAY_ORDER, SR.SUBQUES_RESP_ID AS GROUP_COL
FROM CARS_218_SUBQUES_RESP SR
LEFT OUTER JOIN CARS_218_REPORT_REF_SUBQUES_RESP P
ON SR.SUBQUES_RESP_ID = P.SUBQUES_RESP_ID
LEFT OUTER JOIN CARS_218_SUBQUES_RESP SR1
ON P.REPORT_REF_SUBQUES_RESP_ID = SR1.SUBQUES_RESP_ID
WHERE SR.SUBQUES_ID IN (', i_subques_list, ')  
AND SR.REPORT_COLUMN_FLAG = 1

UNION 

SELECT 
SQ.SUBQUES_ID, SR.RESP_SEQ_NUM, SR.SUBQUES_RESP_ID, SR.RESP_TYPE_CD, SQ.REPORT_COLUMN_LABEL AS COL_HEADER, MAX(RESP_SEQ_NUM) OVER(PARTITION BY CONCAT(SQ.SUBQUES_ID, '':'', SQ.REPORT_COLUMN_LABEL)) AS DISPLAY_ORDER, CONCAT(SQ.SUBQUES_ID, '':'', SQ.REPORT_COLUMN_LABEL) AS GROUP_COL
FROM CARS_218_SUBQUES SQ
JOIN CARS_218_REPORT_REF_SUBQUES_RESP P
ON SQ.SUBQUES_ID = P.SUBQUES_ID
JOIN CARS_218_SUBQUES_RESP SR
ON P.REPORT_REF_SUBQUES_RESP_ID = SR.SUBQUES_RESP_ID
WHERE SQ.SUBQUES_ID IN (', i_subques_list, ')  
AND SQ.REPORT_COLUMN_FLAG = 1


UNION

SELECT 
SR.SUBQUES_ID, SR.RESP_SEQ_NUM, 
CASE WHEN P.SUBQUES_RESP_ID IS NOT NULL THEN SR1.SUBQUES_RESP_ID ELSE SR.SUBQUES_RESP_ID END AS SUBQUES_RESP_ID,
CASE WHEN P.SUBQUES_RESP_ID IS NOT NULL THEN SR1.RESP_TYPE_CD ELSE SR.RESP_TYPE_CD END AS RESP_TYPE_CD,
SR.RESP_SHORT_LABEL_TEXT AS COL_HEADER, SR.RESP_SEQ_NUM AS DISPLAY_ORDER, SR.SUBQUES_RESP_ID AS GROUP_COL

FROM 
(
SELECT SUBQUES_RESP_ID, REPORT_COLUMN_FLAG, RESP_SEQ_NUM, RESP_SHORT_LABEL_TEXT, SUBQUES_ID, RESP_TYPE_CD
FROM CARS_218_SUBQUES_RESP 
WHERE SUBQUES_RESP_ID IN (', i_subques_resp_list, ') 


) SR
LEFT OUTER JOIN CARS_218_REPORT_REF_SUBQUES_RESP P
ON SR.SUBQUES_RESP_ID = P.SUBQUES_RESP_ID
LEFT OUTER JOIN CARS_218_SUBQUES_RESP SR1
ON P.REPORT_REF_SUBQUES_RESP_ID = SR1.SUBQUES_RESP_ID
WHERE SR.REPORT_COLUMN_FLAG = 1
) A'
)
;


EXECUTE IMMEDIATE(v_sql);


SELECT COUNT(DISTINCT LIST_ORDER) INTO v_iter FROM CARS_TEMP_SUBQUES_RESP_LIST;

IF v_iter > 37 THEN
	SELECT 'TOO MANY' FROM DUAL;
	SELECT 'TOO MANY' FROM DUAL;
	LEAVE proc_label;
END IF;


SET v_dropsql = '';
SET v_dropsql = CONCAT('DROP TEMPORARY TABLE IF EXISTS CARS_TEMP_ANS_COLS', v_rand);
EXECUTE IMMEDIATE (v_dropsql);



SET v_whilecnt = 1;
SET v_createtable = CONCAT('CREATE TEMPORARY TABLE CARS_TEMP_ANS_COLS', v_rand, '  
( ENTITY_NAME TEXT NULL, REGION_NAME TEXT NULL, REGION_ID INT NULL, ');

a_while:
	WHILE v_whilecnt <= v_iter DO
		SET v_infinite = v_infinite + 1;
		
		IF v_iter = 0 THEN 
			SET v_collist = '';
			LEAVE a_while;
		END IF;
		
		IF v_whilecnt = 1 THEN 
			SET v_collist = v_createtable;
		END IF;
		
		IF v_whilecnt = v_iter THEN
			SET v_comma = '';
		END IF;
		
		SET v_collist = CONCAT(v_collist, 'COL', v_whilecnt, ' TEXT NULL', v_comma);
		
		SET v_whilecnt = v_whilecnt + 1;
		
		IF v_infinite = 50 THEN
			LEAVE a_while;
		END IF;
		
	END WHILE a_while;

SET v_collist = CONCAT(v_collist, ');');



EXECUTE IMMEDIATE(v_collist);


SET v_dropsql = '';
SET v_dropsql = CONCAT('DROP TEMPORARY TABLE IF EXISTS CARS_TEMP_ANSWERS', v_rand);
EXECUTE IMMEDIATE (v_dropsql);


SET v_crsql = '';
SET v_crsql = CONCAT('CREATE TEMPORARY TABLE CARS_TEMP_ANSWERS', v_rand, ' AS SELECT * FROM CARS_TEMP_ANS_COLS', v_rand);

EXECUTE IMMEDIATE (v_crsql);

SET v_dropsql = '';
SET v_dropsql = CONCAT('DROP TEMPORARY TABLE IF EXISTS CARS_TEMP_HEADER_COLS', v_rand);
EXECUTE IMMEDIATE (v_dropsql);


SET v_whilecnt = 1;
SET v_comma = ',';
SET v_collist = '';
SET v_infinite = 0;
SET v_createtable = CONCAT('CREATE TEMPORARY TABLE CARS_TEMP_HEADER_COLS', v_rand, '  
( ENTITY_NAME TEXT NULL, REGION_NAME TEXT NULL, REGION_ID TEXT NULL, ');


a1_while:
	WHILE v_whilecnt <= v_iter DO
		SET v_infinite = v_infinite + 1;
		
		IF v_iter = 0 THEN 
			SET v_collist = '';
			LEAVE a1_while;
		END IF;
		
		IF v_whilecnt = 1 THEN 
			SET v_collist = v_createtable;
		END IF;
		
		IF v_whilecnt = v_iter THEN
			SET v_comma = '';
		END IF;
		
		SET v_collist = CONCAT(v_collist, 'HEADER', v_whilecnt, ' TEXT NULL', v_comma);
		
		SET v_whilecnt = v_whilecnt + 1;
		
		IF v_infinite = 50 THEN
			LEAVE a1_while;
		END IF;
		
	END WHILE a1_while;

SET v_collist = CONCAT(v_collist, ');');


EXECUTE IMMEDIATE(v_collist);

SET v_dropsql = '';
SET v_dropsql = CONCAT('DROP TEMPORARY TABLE IF EXISTS CARS_TEMP_HEADERS', v_rand);
EXECUTE IMMEDIATE (v_dropsql);


SET v_crsql = '';
SET v_crsql = CONCAT('CREATE TEMPORARY TABLE CARS_TEMP_HEADERS', v_rand, ' AS SELECT * FROM CARS_TEMP_HEADER_COLS', v_rand);

EXECUTE IMMEDIATE (v_crsql);


SET v_dropsql = '';
SET v_dropsql = CONCAT('DROP TEMPORARY TABLE IF EXISTS CARS_TEMP_AMEND_LIST', v_rand);
EXECUTE IMMEDIATE (v_dropsql);


SET v_sql = '';
SET v_sql = CONCAT('
CREATE TEMPORARY TABLE CARS_TEMP_AMEND_LIST', v_rand, ' 
AS 
SELECT
DISTINCT H.ENTITY_NAME, A.HDR_AMEND_ID, R.ENTITY_NAME AS REGION_NAME, E.REGION_ID AS REGION_ID
FROM CARS_MODULE_PERIOD_HDR H
JOIN CARS_218_HDR_AMEND A
ON H.MODULE_HDR_ID = A.MODULE_HDR_ID
JOIN CARS_ENTITY E
ON H.ENTITY_ID = E.ENTITY_ID AND E.ENTITY_TYPE_CD = ''STATE-TER''
JOIN CARS_ENTITY R
ON E.REGION_ID = R.ENTITY_ID
AND R.ENTITY_TYPE_CD = ''REGION''
WHERE H.ENTITY_ID IN (', i_amend_where_cond, ') AND H.PERIOD_ID=', period_id)
;

		
EXECUTE IMMEDIATE(v_sql);


SET v_infinite = 0;
SET v_whilecnt = 1;
SET v_sql = '';

b_while:
	WHILE v_whilecnt <= v_iter DO
		SET v_infinite = v_infinite + 1;
	

		SET v_sql = CONCAT(
		'INSERT INTO CARS_TEMP_ANS_COLS', v_rand, ' ( ENTITY_NAME, REGION_NAME, REGION_ID, COL', v_whilecnt, 
		') 
		SELECT
		ENTITY_NAME, REGION_NAME, REGION_ID,  
		MAX(
		CASE WHEN C.RESP_TYPE_CD = ''CHECKBOX'' AND ANS_TEXT IS NOT NULL AND TRIM(ANS_TEXT) <> '''' THEN ''X''
		 	 WHEN A.ANS_TEXT IS NOT NULL AND ANS_TEXT <> '''' THEN (CASE WHEN ANS_TEXT = '''' THEN NULL ELSE ANS_TEXT END)
			 WHEN A.ANS_DATE IS NOT NULL THEN ANS_DATE
			 WHEN A.ANS_INTEGER IS NOT NULL THEN ANS_INTEGER
			 WHEN A.ANS_DEC IS NOT NULL THEN ANS_DEC
		ELSE ANS_BOOL END
		) AS ANSWER
		FROM CARS_TEMP_AMEND_LIST', v_rand, ' M
		LEFT OUTER JOIN CARS_218_HDR_ANS A
		ON M.HDR_AMEND_ID = A.HDR_AMEND_ID
		JOIN CARS_TEMP_SUBQUES_RESP_LIST  C
		ON A.SUBQUES_RESP_ID = C.SUBQUES_RESP_ID
		WHERE C.LIST_ORDER = ', v_whilecnt, 
		' GROUP BY ENTITY_NAME, REGION_NAME, REGION_ID, C.GROUP_COL'
		)
		;
		
		EXECUTE IMMEDIATE (v_sql);
		
		SET v_whilecnt = v_whilecnt + 1;
		
		IF v_infinite = 50 THEN
			LEAVE b_while;
		END IF;

	END WHILE b_while;
	
	
SET v_sql = CONCAT(
		'INSERT INTO CARS_TEMP_ANS_COLS', v_rand, ' (ENTITY_NAME, REGION_NAME, REGION_ID)
		SELECT M.ENTITY_NAME, M.REGION_NAME, M.REGION_ID
		FROM CARS_TEMP_AMEND_LIST', v_rand, ' M
		LEFT OUTER JOIN CARS_TEMP_ANS_COLS', v_rand, ' A
		ON M.ENTITY_NAME = A.ENTITY_NAME
		WHERE A.ENTITY_NAME IS NULL'
		);
		
	EXECUTE IMMEDIATE (v_sql);


SET v_infinite = 0;
SET v_whilecnt = 1;
SET v_sql = '';

b1_while:
	WHILE v_whilecnt <= v_iter DO
		SET v_infinite = v_infinite + 1;
	

		SET v_sql = CONCAT(
		'INSERT INTO CARS_TEMP_HEADER_COLS', v_rand, ' ( ENTITY_NAME, REGION_NAME, REGION_ID, HEADER', v_whilecnt, 
		') 
		SELECT
		''HEADER ROW'', NULL, NULL,  
		COL_HEADER
		FROM CARS_TEMP_SUBQUES_RESP_LIST   
		WHERE LIST_ORDER = ', v_whilecnt
		)
		;
		
		EXECUTE IMMEDIATE (v_sql);
		
		SET v_whilecnt = v_whilecnt + 1;
		
		IF v_infinite = 50 THEN
			LEAVE b1_while;
		END IF;

	END WHILE b1_while;



SET v_infinite = 0;
SET v_whilecnt = 1;
SET v_comma = ',';


SET v_sqlhdr = CONCAT('INSERT INTO CARS_TEMP_HEADERS', v_rand, ' SELECT ''State/Territory'', ''Region'', ''REGION_ID'', ');
SET v_sqlans = CONCAT('INSERT INTO CARS_TEMP_ANSWERS', v_rand,' SELECT ENTITY_NAME, REGION_NAME, REGION_ID, ');


c1_while:
	WHILE v_whilecnt <= v_iter DO
		SET v_infinite = v_infinite + 1;
	
		IF v_whilecnt = v_iter THEN
			SET v_comma = '';
		END IF;
	
		SET v_sqlhdr = CONCAT(v_sqlhdr, ' MAX(HEADER', v_whilecnt, ')', v_comma);
		SET v_sqlans = CONCAT(v_sqlans, ' MAX(COL', v_whilecnt, ')', v_comma);
		
		SET v_whilecnt = v_whilecnt + 1;

		IF v_infinite = 50 THEN
			LEAVE c1_while;
		END IF;
	
	END WHILE c1_while;


SET v_sqlhdr = CONCAT(v_sqlhdr, ' FROM CARS_TEMP_HEADER_COLS', v_rand, ' GROUP BY ENTITY_NAME, REGION_NAME, REGION_ID ');
SET v_sqlans = CONCAT(v_sqlans, ' FROM CARS_TEMP_ANS_COLS', v_rand, ' GROUP BY ENTITY_NAME, REGION_NAME, REGION_ID ');



EXECUTE IMMEDIATE(v_sqlhdr);


EXECUTE IMMEDIATE(v_sqlans);


SET v_sql = '';
SET v_sql = CONCAT('SELECT * FROM CARS_TEMP_HEADERS', v_rand);

EXECUTE IMMEDIATE(v_sql);



SET v_sql = '';
SET v_sql = CONCAT('SELECT * FROM CARS_TEMP_ANSWERS', v_rand);


EXECUTE IMMEDIATE(v_sql);


UPDATE CARS_SP_LOG
SET SP_STATUS_TEXT= 'Success', END_TS=NOW()
WHERE  SP_LOG_ID=( SELECT MAX(SP_LOG_ID) FROM CARS_SP_LOG WHERE SP_NAME = 'CARS_218_CONTENT_REPORTS');
		
	
END$$
DELIMITER ;